const fs = require('fs');
const path = require('path');

function createMCQ(question, correctOption, wrongOption1, wrongOption2, explanation, mcqIndex) {
  const targetSlot = mcqIndex % 3;
  const options = [];
  if (targetSlot === 0) {
    options.push(correctOption, wrongOption1, wrongOption2);
  } else if (targetSlot === 1) {
    options.push(wrongOption1, correctOption, wrongOption2);
  } else {
    options.push(wrongOption1, wrongOption2, correctOption);
  }
  const cleanOptions = options.map(o => o.replace(/[()[\]{}]/g, '').trim());
  return {
    type: 'mcq',
    question: question.trim(),
    options: cleanOptions,
    correctIndex: targetSlot,
    explanation: explanation.trim()
  };
}

function createNumber(question, target, metricUnit, imperialDisplay, explanation) {
  return {
    type: 'number',
    question: question.trim(),
    target: typeof target === 'number' ? target : parseFloat(target),
    metricUnit: metricUnit.trim(),
    imperialDisplay: imperialDisplay ? imperialDisplay.trim() : undefined,
    explanation: explanation.trim()
  };
}

// -------------------------------------------------------------
// QUIZ 13: chess-grandmasters-strategy-60
// -------------------------------------------------------------
function getChessQuiz() {
  let mcqIdx = 0;
  const q = [];

  // Cycle 1: Origins, Chaturanga & Romantic Era
  q.push(createMCQ("In which ancient empire of India did the game of chess originate around the 6th century CE in the form of Chaturanga?", "Gupta Empire", "Maurya Empire", "Mughal Empire", "Chaturanga represented the four divisions of the Indian military: infantry, cavalry, elephants, and chariots, evolving later into Persian Shatranj.", mcqIdx++));
  q.push(createMCQ("Which legendary 1851 informal chess match played in London saw Adolf Anderssen sacrifice a bishop, both rooks, and his queen to deliver checkmate?", "The Immortal Game", "The Evergreen Game", "The Game of the Century", "Adolf Anderssen defeated Lionel Kieseritzky in London, demonstrating Romantic-era attacking brilliance where material was subordinated to pure mate.", mcqIdx++));
  q.push(createMCQ("Which American prodigy dominated European masters in 1858, playing the celebrated Opera Game from a royal box in Paris against noble opponents?", "Paul Morphy", "Wilhelm Steinitz", "Howard Staunton", "Paul Morphy conducted a clinic in rapid piece development and open lines, checkmating the Duke of Brunswick and Count Isouard in 17 moves.", mcqIdx++));
  q.push(createMCQ("Which English master championed the standard, universally recognized tournament chess piece design created by Nathaniel Cook in 1849?", "Howard Staunton", "Adolf Anderssen", "Henry Bird", "The Staunton pattern design provided stable, weighted, easily identifiable pieces that FIDE adopted as the mandatory standard worldwide.", mcqIdx++));
  q.push(createMCQ("What Persian word meaning 'the King is helpless or dead' is the etymological origin of the English word checkmate?", "Shah Mat", "Rukhad", "Farzin", "When a player's king is placed under attack with no legal move to escape, the game concludes immediately in checkmate.", mcqIdx++));
  q.push(createNumber("How many total alternating light and dark squares make up a standard international chessboard grid?", 64, "squares", "64 grid squares", "A standard chessboard consists of an 8x8 grid comprising exactly 64 alternating light and dark squares."));

  // Cycle 2: Early Official World Champions
  q.push(createMCQ("Which Austrian-American master defeated Johannes Zukertort in 1886 to become recognized as the first official World Chess Champion?", "Wilhelm Steinitz", "Emanuel Lasker", "Paul Morphy", "Steinitz formulated foundational scientific principles of positional play, emphasizing structural weaknesses, pawn outposts, and accumulation of small advantages.", mcqIdx++));
  q.push(createMCQ("Which German mathematician held the World Chess Champion title for an all-time record of 27 consecutive years between 1894 and 1921?", "Emanuel Lasker", "Wilhelm Steinitz", "Max Euwe", "Lasker was a pioneer of psychological chess, intentionally selecting moves that made his specific opponents uncomfortable rather than purely theoretical lines.", mcqIdx++));
  q.push(createMCQ("Which Cuban prodigy nicknamed The Chess Machine went undefeated in tournament play for eight years before losing to Alekhine in 1927?", "Jose Raul Capablanca", "Alexander Alekhine", "Mikhail Botvinnik", "Capablanca learned chess at age four by watching his father and was celebrated for effortless, crystal-clear positional and endgame mastery.", mcqIdx++));
  q.push(createMCQ("Which Russian-French master defeated Capablanca in 1927 and became the only world champion in history to die while holding the official title in 1946?", "Alexander Alekhine", "Max Euwe", "Mikhail Chigorin", "Alekhine was famed for deep calculating stamina, ferocious tactical complications, and dazzling blindfold simultaneous exhibitions.", mcqIdx++));
  q.push(createMCQ("Which Dutch mathematics teacher scored a massive upset against Alexander Alekhine in 1935 to become the fifth official World Chess Champion?", "Max Euwe", "Jan Timman", "Johannes Zukertort", "Max Euwe later served as President of FIDE from 1970 to 1978, managing the tense 1972 World Championship match during the Cold War.", mcqIdx++));
  q.push(createNumber("How many consecutive years did German grandmaster Emanuel Lasker hold the official World Chess Champion title from 1894 to 1921?", 27, "years", "27 consecutive years", "Lasker's 27-year reign as World Chess Champion remains the longest continuous world championship tenure in chess history."));

  // Cycle 3: The Soviet Chess Dynasty
  q.push(createMCQ("Which electrical engineer and patriarch of the Soviet Chess School won the world championship tournament in 1948 and held it across three decades?", "Mikhail Botvinnik", "Vasily Smyslov", "David Bronstein", "Botvinnik established scientific training regimens combining physical fitness, opening preparation, and rigorous endgame analysis in the USSR.", mcqIdx++));
  q.push(createMCQ("Which Latvian attacking genius, known as The Magician from Riga, became the youngest world champion of his time in 1960 through intuitive sacrifices?", "Mikhail Tal", "Tigran Petrosian", "Boris Spassky", "Tal unleashed complex tactical fireworks that overwhelmed opponents psychologically, declaring: You must take your opponent into a deep dark forest.", mcqIdx++));
  q.push(createMCQ("Which Armenian-Soviet world champion was nicknamed Iron Tigran for his impenetrable prophylactic defense and mastery of exchange sacrifices?", "Tigran Petrosian", "Vasily Smyslov", "Levon Aronian", "Petrosian dethroned Mikhail Botvinnik in 1963 by extinguishing opponent attacking chances before they could even materialize.", mcqIdx++));
  q.push(createMCQ("Which Russian grandmaster and baritone singer was celebrated for his sublime harmonious endgame technique, holding the world title in 1957?", "Vasily Smyslov", "Boris Spassky", "Paul Keres", "Smyslov authored classic endgame studies, famously remarking that he played 40 good moves and if his opponent did the same, a draw was fair.", mcqIdx++));
  q.push(createMCQ("Which universal Soviet champion defeated Tigran Petrosian in 1969 before defending his crown in the iconic 1972 Match of the Century against Fischer?", "Boris Spassky", "Efim Geller", "Viktor Korchnoi", "Spassky was admired for his flexible universal style, capable of sharp tactical gambits as well as patient positional maneuvering.", mcqIdx++));
  q.push(createNumber("At what young age in years did Mikhail Tal win the World Chess Championship in 1960 by defeating Mikhail Botvinnik?", 23, "years old", "23 years of age", "Mikhail Tal captured the world crown at just 23 years of age in May 1960, becoming the youngest world champion up to that time."));

  // Cycle 4: Bobby Fischer & Match of the Century
  q.push(createMCQ("In which capital city did American grandmaster Bobby Fischer defeat Boris Spassky in 1972 in the Cold War Match of the Century?", "Reykjavik", "Stockholm", "Helsinki", "Played in Iceland, the match captured global headlines as Fischer ended 24 years of unbroken Soviet chess hegemony.", mcqIdx++));
  q.push(createMCQ("During the 1971 Candidates Matches, what historic sweep score did Bobby Fischer achieve against both Mark Taimanov and Bent Larsen?", "6 to 0", "5 to 1", "6 to 2", "Fischer accomplished the unprecedented feat of winning twelve consecutive games without a single draw or loss against world-class grandmasters.", mcqIdx++));
  q.push(createMCQ("What variant of chess did Bobby Fischer patent in 1996 to eliminate opening memorization by randomly shuffling back-rank pieces?", "Fischer Random Chess (Chess960)", "Bughouse Chess", "Crazyhouse", "Chess960 creates 960 possible starting back-rank piece setups, forcing players to rely on pure creativity and principles from move one.", mcqIdx++));
  q.push(createMCQ("At what age did 13-year-old Bobby Fischer win the Game of the Century against Donald Byrne in New York in 1956, featuring a brilliant queen sacrifice?", "13 years old", "16 years old", "10 years old", "Fischer sacrificed his queen on move 17 with Be6!, coordinating his minor pieces and rooks in a devastating windmill attack.", mcqIdx++));
  q.push(createMCQ("Why was Bobby Fischer stripped of his World Chess Champion title by FIDE in 1975 without playing a game?", "He refused to play when match conditions were not met", "He retired due to medical illness", "He was disqualified for illegal moves", "FIDE awarded the world championship crown by default to 23-year-old Soviet challenger Anatoly Karpov in April 1975.", mcqIdx++));
  q.push(createNumber("In what year CE did the historic World Chess Championship match between Bobby Fischer and Boris Spassky take place in Reykjavik?", 1972, "CE", "Summer 1972", "The 1972 World Championship match concluded on 1 September 1972 with Fischer winning by a score of 12.5 to 8.5."));

  // Cycle 5: Anatoly Karpov & Garry Kasparov Rivalry
  q.push(createMCQ("Which legendary Soviet champion dominated the late 1970s and 1980s with his suffocating boa constrictor positional squeeze style?", "Anatoly Karpov", "Viktor Korchnoi", "Artur Yusupov", "Karpov won hundreds of elite tournaments, defending his world title twice against Soviet defector Viktor Korchnoi in 1978 and 1981.", mcqIdx++));
  q.push(createMCQ("In 1985, who defeated Anatoly Karpov to become the youngest undisputed World Chess Champion in history at age 22?", "Garry Kasparov", "Vladimir Kramnik", "Viswanathan Anand", "Kasparov held the world number one ranking almost continuously for twenty years from 1985 until his retirement from competitive chess in 2005.", mcqIdx++));
  q.push(createMCQ("What happened to the marathon 1984 World Championship match between Karpov and Kasparov after 48 games spanning five months?", "It was controversially aborted without a winner", "Kasparov won on tiebreaks", "Karpov won 6 to 0", "FIDE President Florencio Campomanes halted the match citing player exhaustion, ordering a fresh match in 1985 that Kasparov won.", mcqIdx++));
  q.push(createMCQ("What opening defense did Garry Kasparov famously employ with black to win critical games against Anatoly Karpov, featuring 1.e4 c5 2.Nf3 d6 3.d4 cxd4 4.Nxd4 Nf6 5.Nc3 a6?", "Sicilian Najdorf", "French Defense", "Caro-Kann Defense", "The sharp Sicilian Najdorf became Kasparov's primary tactical weapon against 1.e4, delivering dynamic counterattacking victories.", mcqIdx++));
  q.push(createMCQ("Which Russian grandmaster defeated Garry Kasparov in London in 2000 using the Berlin Defense of the Ruy Lopez, ending Kasparov's 15-year reign?", "Vladimir Kramnik", "Peter Svidler", "Alexander Grischuk", "Kramnik's Berlin Wall neutralized Kasparov's legendary white openings, winning the 16-game match without conceding a single loss.", mcqIdx++));
  q.push(createNumber("How many total games were played in the grueling, unfinished 1984 to 1985 World Championship match between Karpov and Kasparov before it was halted?", 48, "games", "48 marathon games", "The 1984 match lasted an unprecedented 48 games between September 1984 and February 1985, featuring 40 draws.", mcqIdx));

  // Cycle 6: Deep Blue & The AI Revolution
  q.push(createMCQ("Which IBM supercomputer made history in May 1997 by defeating reigning World Champion Garry Kasparov in a six-game match in New York?", "Deep Blue", "Watson", "AlphaZero", "Deep Blue evaluated up to 200 million chess positions per second, marking the first time a computer defeated a reigning world champion in standard match play.", mcqIdx++));
  q.push(createMCQ("Which DeepMind artificial intelligence system taught itself chess tabula rasa in just four hours of reinforcement self-play to defeat Stockfish in 2017?", "AlphaZero", "AlphaGo", "Deep Thought", "AlphaZero shocked grandmasters with dynamic long-term piece sacrifices, fluid king marches, and active piece play reminiscent of Paul Morphy.", mcqIdx++));
  q.push(createMCQ("What open-source chess engine developed by an international community of volunteers is currently the strongest traditional chess engine in the world?", "Stockfish", "Komodo", "Houdini", "Stockfish utilizes NNUE (Efficiently Updatable Neural Networks) architecture and deep search trees, achieving an estimated Elo rating exceeding 3500.", mcqIdx++));
  q.push(createMCQ("What standard metric unit is used by chess engines to evaluate a positional advantage, where 100 units represents the value of one pawn?", "Centipawn", "Millipawn", "Decipawn", "An evaluation of plus 1.50 (150 centipawns) indicates that the engine calculates White has an advantage roughly equivalent to one and a half pawns.", mcqIdx++));
  q.push(createMCQ("What type of chess competition pairs human players collaborating with computer chess engines in real-time, coined by Garry Kasparov?", "Centaur Chess (Advanced Chess)", "Correspondence Chess", "Bullet Chess", "Centaur chess demonstrated that a human plus a machine could play higher-quality chess than either the strongest human or computer alone.", mcqIdx++));
  q.push(createNumber("In what year CE did IBM's Deep Blue supercomputer officially defeat Garry Kasparov in their historic rematch in New York City?", 1997, "CE", "May 1997", "Deep Blue won the six-game match 3.5 to 2.5 on 11 May 1997, a watershed moment in the history of artificial intelligence."));

  // Cycle 7: Magnus Carlsen & Modern Era Dominance
  q.push(createMCQ("Which Norwegian prodigy achieved the highest classical FIDE Elo rating in history (2882) and held the classical world title from 2013 to 2023?", "Magnus Carlsen", "Hikaru Nakamura", "Fabiano Caruana", "Carlsen dethroned Viswanathan Anand in 2013 in Chennai, defending his title four times against Anand, Karjakin, Caruana, and Nepomniachtchi.", mcqIdx++));
  q.push(createMCQ("How many consecutive classical chess games did Magnus Carlsen play without defeat between July 2018 and October 2020, setting an all-time world record?", "125 games", "80 games", "150 games", "Carlsen surpassed Sergei Tiviakov's mark of 110 games, going 125 games undefeated against the world's elite grandmasters.", mcqIdx++));
  q.push(createMCQ("Which Indian grandmaster became the undisputed World Chess Champion in 2007, defending his title in classical matches against Kramnik, Topalov, and Gelfand?", "Viswanathan Anand", "Pentala Harikrishna", "Vidit Gujrathi", "Vishy Anand is known as The Tiger from Madras and sparked a colossal chess revolution across India that produced dozens of young grandmasters.", mcqIdx++));
  q.push(createMCQ("Which Chinese grandmaster defeated Ian Nepomniachtchi in Astana in 2023 to become the 17th official World Chess Champion?", "Ding Liren", "Wang Hao", "Wei Yi", "Ding Liren clinched the world crown with a daring 46...Rg6 self-pin in the fourth and final rapid tiebreak game.", mcqIdx++));
  q.push(createMCQ("Which American grandmaster, popular on Twitch and YouTube, is one of the world's greatest blitz and bullet chess players alongside Carlsen?", "Hikaru Nakamura", "Wesley So", "Hans Niemann", "Nakamura won the World Fischer Random Championship in 2022 and reached a peak classical rating of 2816.", mcqIdx++));
  q.push(createNumber("What is the highest official peak FIDE classical Elo rating ever achieved in history, recorded by Magnus Carlsen in May 2014?", 2882, "Elo rating", "2882 peak Elo", "Magnus Carlsen reached the pinnacle rating of 2882 in May 2014, the highest rating ever recorded in the history of the FIDE rating system."));

  // Cycle 8: Openings, Defenses & Gambits
  q.push(createMCQ("Which popular opening beginning with 1.e4 e5 2.Nf3 Nc6 3.Bb5 is named after a 16th-century Spanish priest who wrote a book on chess?", "Ruy Lopez (Spanish Game)", "Italian Game", "Vienna Game", "Ruy Lopez de Segura published Libro de la invencion liberal y arte del juego del axedrez in 1561, analyzing the move 3.Bb5 pinning the knight.", mcqIdx++));
  q.push(createMCQ("What is the most popular, dynamic, and statistically highest-scoring counter-attacking response by Black against 1.e4, starting with 1...c5?", "Sicilian Defense", "French Defense", "Caro-Kann Defense", "The Sicilian Defense immediately creates asymmetrical pawn structures and fights for central control without mirroring White's moves.", mcqIdx++));
  q.push(createMCQ("Which classical opening beginning with 1.d4 d5 2.c4 offers a temporary side pawn sacrifice to gain central pawn domination?", "Queen's Gambit", "King's Gambit", "Evans Gambit", "Black can accept the gambit with 2...dxc4 or decline with solid setups like the Orthodox Defense, Slav Defense, or Queen's Gambit Declined.", mcqIdx++));
  q.push(createMCQ("What hypermodern defense for Black against 1.d4 allows White to build a broad pawn center before counter-attacking with ...d6, ...Nf6, ...g6, and ...Bg7?", "King's Indian Defense", "Nimzo-Indian Defense", "Grünfeld Defense", "Championed by Garry Kasparov and Bobby Fischer, the King's Indian leads to thrilling tactical kingside pawn storms against White's queenside expansion.", mcqIdx++));
  q.push(createMCQ("Which solid opening system for White features an early d4, Nf3, Bf4, e3, c3, and Nbd2, popular for its universal structural consistency?", "London System", "Colle System", "Torre Attack", "The London System develops the dark-squared bishop outside the pawn chain before playing e3, providing a solid setup against virtually any Black response.", mcqIdx++));
  q.push(createNumber("How many total playing pieces does each player control on the board at the beginning of a standard chess match?", 16, "pieces", "16 starting pieces", "Each player starts with 16 pieces: 1 King, 1 Queen, 2 Rooks, 2 Bishops, 2 Knights, and 8 Pawns."));

  // Cycle 9: Tactics, Endgames & Rules
  q.push(createMCQ("What tactical tactic occurs when a single piece simultaneously attacks two or more opposing pieces, most famously executed by knights?", "A Fork", "A Pin", "A Skewer", "Knights are particularly lethal at executing royal forks attacking both the king and queen simultaneously due to their unique jumping movement.", mcqIdx++));
  q.push(createMCQ("What German chess term describes a compulsory move situation in which any legal move a player can make will worsen their position?", "Zugzwang", "Zwischenzug", "Luft", "Zugzwang occurs frequently in endgames where having the obligation to move leads directly to defeat or material loss.", mcqIdx++));
  q.push(createMCQ("What essential rook endgame technique involves building a protective pawn bridge with the rook to shield the king from enemy checks and promote a pawn?", "Lucena Position", "Philidor Position", "Vancura Position", "Described by Luis Ramirez de Lucena in 1497, the bridge-building maneuver ensures the promotion of a 7th-rank pawn in rook and pawn endgames.", mcqIdx++));
  q.push(createMCQ("What special French pawn capture rule allows a pawn to capture an enemy pawn that has just advanced two squares past it as if it had advanced only one?", "En Passant", "Castling", "Promotion", "En passant (in passing) must be exercised on the very next turn immediately following the opposing pawn's two-square advance, or the right is permanently lost.", mcqIdx++));
  q.push(createMCQ("What outcome occurs when the player whose turn it is to move has no legal moves available and their king is NOT in check?", "Stalemate (Draw)", "Checkmate (Loss)", "Forfeit", "Under Article 5.2.1 of FIDE laws, stalemate immediately concludes the game as a half-point draw, often used as a desperate escape tactic by defending players.", mcqIdx++));
  q.push(createNumber("Under FIDE rules, after how many consecutive moves without a pawn move or piece capture may a player claim a draw under the Fifty-Move Rule?", 50, "moves", "50 consecutive moves", "The Fifty-Move Rule permits a player to claim a draw if no pawn has moved and no piece has been captured within the last 50 consecutive moves by each side."));

  // Cycle 10: Curiosities & Records
  q.push(createMCQ("What is the fastest possible checkmate in chess, occurring in just two moves from the starting position if White plays 1.f3 and 2.g4?", "Fool's Mate", "Scholar's Mate", "Smothered Mate", "Black plays 1...e5 and delivers checkmate with 2...Qh4# along the fatally weakened e1-h4 diagonal.", mcqIdx++));
  q.push(createMCQ("Which American grandmaster of Indian descent became the youngest chess Grandmaster in history in 2021 at the age of 12 years, 4 months, and 25 days?", "Abhimanyu Mishra", "Sergey Karjakin", "Praggnanandhaa R", "Mishra earned his final GM norm in Budapest in June 2021, breaking Sergey Karjakin's 19-year-old record by 66 days.", mcqIdx++));
  q.push(createMCQ("What is the term for a checkmate delivered by a knight where the mated king is completely trapped and surrounded by its own pieces with nowhere to move?", "Smothered Mate", "Boden's Mate", "Anastasia's Mate", "Smothered mate often features a queen sacrifice on the back rank to force an enemy rook to block the king's final escape square.", mcqIdx++));
  q.push(createMCQ("Which grandmaster holds the Guinness World Record for the largest blindfold simultaneous exhibition, playing 48 games at once while blindfolded on an exercise bike?", "Timur Gareyev", "Marc Lang", "George Koltanowski", "In December 2016 in Las Vegas, Timur Gareyev played 48 opponents simultaneously for 19 hours without looking at a single board, scoring 35 wins, 7 draws, and 6 losses.", mcqIdx++));
  q.push(createMCQ("What mathematical theorem calculates that the number of possible unique chess games is roughly 10 to the 120th power, far exceeding atoms in the observable universe?", "Shannon Number", "Graham's Number", "Avogadro's Constant", "Formulated by mathematician Claude Shannon in his 1950 paper Programming a Computer for Playing Chess, the Shannon Number estimates game-tree complexity.", mcqIdx++));
  q.push(createNumber("What is the minimum classical FIDE Elo rating requirement an athlete must achieve alongside three title norms to earn the Grandmaster title?", 2500, "Elo rating", "2500 FIDE Elo threshold", "FIDE requires candidates to achieve a published classical rating of at least 2500 alongside three qualifying grandmaster norms to earn the Grandmaster title."));

  return {
    id: "chess-grandmasters-strategy-60",
    theme: "Chess History: Grandmasters, Tactics & World Champions",
    title: "Chess History: Grandmasters, Tactics & World Champions",
    description: "A 60-question grand master assessment exploring chess origins from Chaturanga to Romantic sacrifices, world champions from Steinitz to Capablanca, the Soviet dynasty, Fischer vs. Spassky, Kasparov vs. Karpov, Deep Blue AI, Magnus Carlsen, opening theory, and tactical motifs.",
    category: "Sports, Records & General Knowledge",
    difficulty: "moderate",
    createdAt: "2026-08-27T00:00:00Z",
    questions: q
  };
}

// -------------------------------------------------------------
// QUIZ 14: extreme-sports-adventures-60
// -------------------------------------------------------------
function getExtremeSportsQuiz() {
  let mcqIdx = 0;
  const q = [];

  // Cycle 1: Mount Everest & The 8000ers
  q.push(createMCQ("Which duo became the first confirmed mountaineers to reach the summit of Mount Everest on 29 May 1953 via the South Col route?", "Sir Edmund Hillary and Tenzing Norgay", "George Mallory and Andrew Irvine", "Reinhold Messner and Peter Habeler", "New Zealander Edmund Hillary and Sherpa mountaineer Tenzing Norgay reached the 8,848-meter summit as part of the ninth British Everest expedition.", mcqIdx++));
  q.push(createMCQ("Which legendary Italian mountaineer became the first person to climb all 14 eight-thousander peaks and completed the first solo ascent of Everest without oxygen in 1980?", "Reinhold Messner", "Walter Bonatti", "Jerzy Kukuczka", "Reinhold Messner proved human physiology could survive in the Death Zone without bottled oxygen, redefining high-altitude alpine mountaineering.", mcqIdx++));
  q.push(createMCQ("What physiological altitude zone above 8,000 meters contains insufficient atmospheric oxygen pressure to sustain human life for extended periods?", "The Death Zone", "The Troposphere Zone", "The Sub-Zero Zone", "In the Death Zone, human cells consume oxygen faster than the body can replenish it, causing rapid deterioration, altitude sickness, and cerebral edema.", mcqIdx++));
  q.push(createMCQ("Which notoriously lethal Pakistani mountain, the second highest on Earth at 8,611 meters, is nicknamed The Savage Mountain?", "K2", "Nanga Parbat", "Kangchenjunga", "K2 in the Karakoram range is famous for extreme technical climbing, unpredictable avalanches, and severe weather, with a historically high fatality rate.", mcqIdx++));
  q.push(createMCQ("Which Nepali mountaineer shattered world records in 2019 by summiting all 14 eight-thousanders in just 6 months and 6 days in Project Possible?", "Nimsdai Purja", "Kami Rita Sherpa", "Apa Sherpa", "Nirmal Nims Purja smashed the previous record of 7 years and 11 months, documented in the film 14 Peaks: Nothing Is Impossible.", mcqIdx++));
  q.push(createNumber("What is the officially recognized height of Mount Everest above sea level in meters?", 8848, "meters", "29029 feet", "Mount Everest's official summit elevation is officially established at 8,848.86 meters (29,031.7 feet) by Nepal and China."));

  // Cycle 2: Race to the South Pole
  q.push(createMCQ("Which Norwegian explorer led the first expedition to successfully reach the Geographic South Pole on 14 December 1911?", "Roald Amundsen", "Robert Falcon Scott", "Fridtjof Nansen", "Amundsen utilized Greenland sled dogs, lightweight skis, and Inuit survival techniques to reach the pole 34 days ahead of the British team.", mcqIdx++));
  q.push(createMCQ("Which British naval officer led the tragic 1910 to 1913 Terra Nova Expedition, reaching the South Pole in January 1912 only to find Amundsen's tent?", "Captain Robert Falcon Scott", "Sir Ernest Shackleton", "Frank Wild", "Scott and his four companions perished from starvation, frostbite, and blizzard conditions on their return journey across the Ross Ice Shelf.", mcqIdx++));
  q.push(createMCQ("Which Anglo-Irish explorer famously led the Imperial Trans-Antarctic Expedition aboard Endurance, miraculously saving his entire 28-man crew after the ship was crushed in pack ice?", "Sir Ernest Shackleton", "Douglas Mawson", "Apsley Cherry-Garrard", "Shackleton navigated an open 22-foot lifeboat 800 miles across the treacherous Southern Ocean to South Georgia Island to orchestrate the rescue.", mcqIdx++));
  q.push(createMCQ("What is the name of the permanent United States scientific research station located at the southernmost point on Earth since 1956?", "Amundsen-Scott South Pole Station", "McMurdo Station", "Vostok Station", "The station honors the two pioneering explorers who first conquered the South Pole in 1911 and 1912.", mcqIdx++));
  q.push(createMCQ("What fierce, hurricane-force gravity-driven winds sweep down off the high Antarctic ice plateau toward the coast?", "Katabatic winds", "Chinook winds", "Mistral winds", "Katabatic winds in Antarctica can exceed speeds of 300 km/h, creating zero-visibility blinding ground blizzards.", mcqIdx++));
  q.push(createNumber("In what year CE did Roald Amundsen and his Norwegian team plant their national flag at the Geographic South Pole?", 1911, "CE", "December 1911", "Amundsen reached the Geographic South Pole on 14 December 1911, establishing camp Polheim at the bottom of the world."));

  // Cycle 3: North Pole & Arctic Exploration
  q.push(createMCQ("Which Norwegian explorer intentionally froze his specially designed wooden ship Fram into the Arctic pack ice in 1893 to drift across the North Pole?", "Fridtjof Nansen", "Roald Amundsen", "Otto Sverdrup", "Nansen's round-hulled Fram was engineered to be lifted upward by squeezing ice pressure rather than being crushed, proving Arctic transpolar drift.", mcqIdx++));
  q.push(createMCQ("Which American explorer and his African American associate Matthew Henson claimed to have reached the Geographic North Pole on 6 April 1909?", "Robert Peary", "Frederick Cook", "Richard Byrd", "Matthew Henson served as primary navigator, dog driver, and translator, being the first member of the expedition to physically touch the pole.", mcqIdx++));
  q.push(createMCQ("Which Italian engineer piloted the semi-rigid airship Norge with Roald Amundsen in 1926 to make the first undisputed flight over the North Pole?", "Umberto Nobile", "Lincoln Ellsworth", "Alberto Santos-Dumont", "The Norge flew from Spitsbergen, Norway across the North Pole to Teller, Alaska, verified as the first indisputable sighting of the North Pole.", mcqIdx++));
  q.push(createMCQ("Unlike the continent of Antarctica, what forms the physical surface of the Geographic North Pole?", "Shifting sea ice pack over a deep ocean", "A solid continental landmass", "A dormant volcanic crater", "The North Pole sits in the middle of the Arctic Ocean beneath shifting sea ice that is several meters thick over water 4,000 meters deep.", mcqIdx++));
  q.push(createMCQ("What optical Arctic phenomenon creates dangerous flat light conditions where cloud cover and snow-covered ground blend into a disorienting, shadowless horizon?", "Whiteout", "Mirage", "Sun dog", "A whiteout destroys depth perception and spatial orientation, making navigation impossible without compasses or GPS.", mcqIdx++));
  q.push(createNumber("What is the exact geographical latitude of the North Pole in degrees North?", 90, "degrees North", "90° North", "The Geographic North Pole is defined as the northernmost point on the Earth's axis of rotation at exactly 90 degrees North latitude."));

  // Cycle 4: Big Wave Surfing & Ocean Giants
  q.push(createMCQ("Which Portuguese fishing town is world-renowned for generating the largest surfable waves on Earth at Praia do Norte due to a deep underwater canyon?", "Nazare", "Peniche", "Ericeira", "The 5,000-meter-deep Nazare Canyon funnels and amplifies Atlantic storm swells into massive monster waves reaching over 25 meters in height.", mcqIdx++));
  q.push(createMCQ("Which Brazilian big-wave surfer rode an 80-foot (24.4-meter) monster wave at Nazare in 2017 to set the Guinness World Record for biggest wave surfed?", "Rodrigo Koxa", "Lucas Chianca", "Gabriel Medina", "Koxa was towed into the colossal wave by jet ski on 8 November 2017, winning the World Surf League Quiksilver XXL Biggest Wave Award.", mcqIdx++));
  q.push(createMCQ("Which legendary American waterman put Nazare on the global map in 2011 by surfing a pioneering 78-foot wave with local rescue teams?", "Garrett McNamara", "Laird Hamilton", "Kelly Slater", "McNamara pioneered safety protocols, inflatable vests, and jet-ski tow-in systems that revolutionized modern big-wave surfing.", mcqIdx++));
  q.push(createMCQ("Which fearsome big-wave reef break located on the north shore of Maui, Hawaii, is known by surfers as Jaws?", "Peahi", "Waimea Bay", "Banzai Pipeline", "Peahi (Jaws) features ferocious, deep-water Pacific waves traveling at 50 km/h with thick, crushing lip barrels.", mcqIdx++));
  q.push(createMCQ("What northern California big-wave surfing spot near Half Moon Bay produces heavy, freezing cold waves over dangerous rock reefs?", "Mavericks", "Steamer Lane", "Rincon", "Mavericks draws elite big-wave surfers to cold, shark-inhabited waters where wave faces regularly exceed 15 to 18 meters.", mcqIdx++));
  q.push(createNumber("What is the height in meters of Rodrigo Koxa's official world record biggest wave ever surfed at Nazare?", 24, "meters", "80 feet (24.38m)", "Rodrigo Koxa's world-record wave on 8 November 2017 was officially verified at 24.38 meters (80.0 feet)."));

  // Cycle 5: Free Soloing & Big Wall Climbing
  q.push(createMCQ("Which American rock climber made history on 3 June 2017 by completing the first-ever free solo climb of El Capitan in Yosemite without ropes?", "Alex Honnold", "Tommy Caldwell", "Dean Potter", "Alex Honnold scaled the 900-meter Freerider route on El Capitan in 3 hours and 56 minutes, documented in the Oscar-winning film Free Solo.", mcqIdx++));
  q.push(createMCQ("What is the monumental 900-meter vertical granite monolith rising above Yosemite Valley that is the mecca of world big-wall rock climbing?", "El Capitan", "Half Dome", "Cathedral Rocks", "El Capitan presents sheer granite faces with legendary routes such as The Nose, Salathe Wall, and the Dawn Wall.", mcqIdx++));
  q.push(createMCQ("Which American climbing duo completed the world-first free climb of the notoriously smooth, nearly featureless Dawn Wall on El Capitan in 2015?", "Tommy Caldwell and Kevin Jorgeson", "Alex Honnold and Cedar Wright", "Chris Sharma and Adam Ondra", "Caldwell and Jorgeson spent 19 consecutive days living on portaledges suspended high on the wall to complete the 32-pitch 5.14d route.", mcqIdx++));
  q.push(createMCQ("Which trailblazing American female climber made history in 1993 by becoming the first person (male or female) to free climb The Nose on El Capitan?", "Lynn Hill", "Steph Davis", "Ashima Shiraishi", "Lynn Hill famously proclaimed It goes, boys! after freeing the notoriously difficult Great Roof and Changing Corners pitches.", mcqIdx++));
  q.push(createMCQ("What specialized climbing grading system used in North America rates technical rock climbing difficulty starting from class 5.0 up to 5.15d?", "Yosemite Decimal System (YDS)", "Fontainebleau Scale", "French Numerical Scale", "Created in the 1950s at Tahquitz Rock, the system rates 5th-class climbing where ropes and belays are essential for safety.", mcqIdx++));
  q.push(createNumber("How many minutes did Alex Honnold take to complete his historic free solo climb of El Capitan's Freerider route in 2017?", 236, "minutes", "3 hours 56 minutes", "Honnold completed the 3,000-foot vertical granite ascent in exactly 3 hours and 56 minutes (236 minutes) on 3 June 2017."));

  // Cycle 6: Stratospheric Skydiving & BASE Jumping
  q.push(createMCQ("Which Austrian daredevil made history on 14 October 2012 by jumping from a helium balloon in the stratosphere at 39 kilometers in the Red Bull Stratos mission?", "Felix Baumgartner", "Alan Eustace", "Joe Kittinger", "Baumgartner accelerated to Mach 1.25 (1,357.6 km/h) in freefall, becoming the first human to break the speed of sound without a vehicle.", mcqIdx++));
  q.push(createMCQ("What does the acronym BASE stand for in the extreme parachute jumping sport of BASE jumping?", "Building, Antenna, Span, Earth", "Bridge, Altitude, Sky, Elevation", "Bungee, Air, Speed, Extreme", "BASE jumpers leap from fixed land-based objects across the four categories, deploying parachutes at low altitudes.", mcqIdx++));
  q.push(createMCQ("What specialized aerodynamic jumpsuit with fabric between the legs and under the arms allows jumpers to glide horizontally through the air like birds?", "Wingsuit", "G-suit", "Speedsuit", "Wingsuits convert vertical falling speed into forward glide with glide ratios up to 3:1, enabling high-speed proximity flights alongside mountain cliffs.", mcqIdx++));
  q.push(createMCQ("Which US Air Force officer held the highest parachute jump record from 31,300 meters for 52 years after Project Excelsior in 1960?", "Joseph Kittinger", "Chuck Yeager", "John Glenn", "Colonel Joe Kittinger served as Baumgartner's capsule communicator and mentor during the 2012 Red Bull Stratos mission.", mcqIdx++));
  q.push(createMCQ("What constant maximum speed does a freely falling human body in belly-to-earth orientation achieve when air resistance equals gravitational pull?", "Terminal velocity", "Escape velocity", "Orbital velocity", "For a human belly-to-earth skydiver in standard lower atmosphere, terminal velocity is approximately 190 to 200 km/h (120 mph).", mcqIdx++));
  q.push(createNumber("From what altitude in kilometers did Felix Baumgartner jump during his 2012 Red Bull Stratos mission?", 39, "kilometers", "128100 feet (39km)", "Baumgartner stepped out of his capsule at an altitude of 38,969.4 meters (approximately 39 kilometers or 24.2 miles) above New Mexico."));

  // Cycle 7: Ultra-Running & Desert Endurance
  q.push(createMCQ("What legendary 250-kilometer, six-day footrace across the Sahara Desert requires competitors to carry all food and gear on their backs?", "Marathon des Sables", "Badwater 135", "Leadville 100", "Runners in the Marathon des Sables endure 50 degrees Celsius heat, blinding sandstorms, and towering sand dunes in southern Morocco.", mcqIdx++));
  q.push(createMCQ("Which grueling 135-mile ultramarathon starts at Badwater Basin in Death Valley (86m below sea level) and finishes at Whitney Portal in searing summer heat?", "Badwater 135", "Western States 100", "Hardrock 100", "Badwater runners face pavement temperatures that can melt running shoes, completing the 217-kilometer course in furnace-like July temperatures.", mcqIdx++));
  q.push(createMCQ("Which mysterious, notoriously brutal 100-mile ultramarathon created by Lazarus Lake in Tennessee has seen only around 20 finishers since 1986?", "The Barkley Marathons", "Spartathlon", "Tor des Geants", "Inspired by James Earl Ray's prison escape, the race requires runners to find hidden paperback books in briar-choked woods within a 60-hour cutoff.", mcqIdx++));
  q.push(createMCQ("Which historic 246-kilometer continuous ultramarathon in Greece traces the legendary courier messenger Pheidippides from Athens to Sparta?", "Spartathlon", "Olympus Marathon", "Crete Ultra", "Established in 1983 based on Herodotus's account of the Persian Wars, runners must touch the statue of King Leonidas in Sparta within 36 hours.", mcqIdx++));
  q.push(createMCQ("What 170-kilometer mountain ultramarathon circumnavigates the Mont Blanc massif through France, Italy, and Switzerland with 10,000m of elevation gain?", "Ultra-Trail du Mont-Blanc (UTMB)", "Western States 100", "Grand Raid Reunion", "The UTMB in Chamonix is the most competitive trail running race in the world, taking runners through high alpine passes day and night.", mcqIdx++));
  q.push(createNumber("Approximately how many total individual runners have managed to officially finish the brutal Barkley Marathons since its creation in 1986?", 20, "finishers", "approx. 20 finishers", "Only 20 distinct individuals have successfully finished all five 20-mile loops of the Barkley Marathons within the strict 60-hour time limit."));

  // Cycle 8: Freediving & Subaquatic Limits
  q.push(createMCQ("Which Austrian freediving legend nicknamed The Deepest Man on Earth set the No-Limits freedive world record at 214 meters on a single breath?", "Herbert Nitsch", "William Trubridge", "Umberto Pelizzari", "Herbert Nitsch has held 33 world records across all eight freediving disciplines, surviving a 253-meter experimental dive in Greece.", mcqIdx++));
  q.push(createMCQ("Which New Zealand freediver broke world records by diving unassisted (without fins) to a depth of 102 meters at Dean's Blue Hole in the Bahamas?", "William Trubridge", "Alexey Molchanov", "Guillaume Nery", "Trubridge specialized in Constant Weight No Fins (CNF), using only a modified breaststroke to descend and ascend into the abyss.", mcqIdx++));
  q.push(createMCQ("What physiological reflex in humans triggers bradycardia (slowing heart rate) and peripheral vasoconstriction when the face is submerged in water?", "Mammalian dive reflex", "Barotrauma reflex", "Valsalva reflex", "The mammalian dive reflex conserves core oxygen and redirects blood flow to the brain and heart during deep breath-hold diving.", mcqIdx++));
  q.push(createMCQ("Which 1988 Luc Besson cult film dramatized the fierce freediving rivalry between Jacques Mayol and Enzo Maiorca?", "The Big Blue (Le Grand Bleu)", "Sanctum", "The Abyss", "The Big Blue popularized the beauty and danger of freediving to millions of viewers worldwide with a mesmerizing score by Eric Serra.", mcqIdx++));
  q.push(createMCQ("What deep underwater sinkhole in Long Island, Bahamas, plunging to 202 meters, hosts the prestigious Vertical Blue freediving championship?", "Dean's Blue Hole", "Great Blue Hole of Belize", "Dragon Hole", "Dean's Blue Hole provides calm, current-free waters directly accessible from the beach, making it the premier freediving stadium.", mcqIdx++));
  q.push(createNumber("What is Herbert Nitsch's official AIDA world record deepest No-Limits freediving depth in meters?", 214, "meters", "702 feet", "Herbert Nitsch achieved his official AIDA No-Limits world record depth of 214 meters (702 feet) on 14 June 2007 in Spetses, Greece."));

  // Cycle 9: Solo Round-the-World Sailing
  q.push(createMCQ("What prestigious non-stop, solo, unassisted yacht race around the world without assistance starts and finishes in Les Sables-d'Olonne, France?", "Vendee Globe", "The Ocean Race", "Route du Rhum", "Known as The Everest of the Seas, competitors sail IMOCA 60 foiling monohulls around the Cape of Good Hope, Cape Leeuwin, and Cape Horn.", mcqIdx++));
  q.push(createMCQ("Which English sailor became the first person to complete a single-handed non-stop circumnavigation of the globe in the 1968 to 1969 Golden Globe Race?", "Sir Robin Knox-Johnston", "Bernard Moitessier", "Sir Francis Chichester", "Knox-Johnston sailed his 32-foot wooden ketch Suhaili for 312 days, being the only one of nine starters to successfully finish the race.", mcqIdx++));
  q.push(createMCQ("What treacherous southern headland of the Tierra del Fuego archipelago is notorious for huge waves, strong currents, and iceberg hazards?", "Cape Horn", "Cape of Good Hope", "Cape Leeuwin", "Rounding Cape Horn marks the boundary between the Pacific and Atlantic Oceans, revered by sailors as the ultimate maritime challenge.", mcqIdx++));
  q.push(createMCQ("What oceanic location in the South Pacific is the most remote point on Earth, furthest from any landmass, used as a spacecraft cemetery?", "Point Nemo", "Bikini Atoll", "Easter Island", "Point Nemo is 2,688 kilometers from the nearest land; the closest humans are often astronauts aboard the International Space Station passing overhead.", mcqIdx++));
  q.push(createMCQ("What strong westerly winds blowing between latitudes 40 and 50 degrees South in the Southern Ocean power round-the-world sailing races?", "The Roaring Forties", "The Trade Winds", "The Doldrums", "The lack of landmasses in the Southern Hemisphere allows storms to build uninterrupted, driving giant waves and high-speed sailing.", mcqIdx++));
  q.push(createNumber("What is the record in days set by French sailor Armel Le Cleac'h to complete the non-stop solo Vendee Globe circumnavigation?", 74, "days", "74 days 3 hours", "Armel Le Cleac'h won the 2016-2017 Vendee Globe in a record time of 74 days, 3 hours, and 35 minutes aboard Banque Populaire VIII."));

  // Cycle 10: Polar Crossings & Earth Extremes
  q.push(createMCQ("Which Norwegian explorer completed the first solo, unassisted, and unsupported crossing of the Antarctic continent in 1996 to 1997?", "Borge Ousland", "Erling Kagge", "Mike Horn", "Ousland hauled a 180kg sledge 2,845 kilometers in 64 days using skis and a traction kite, enduring temperatures below minus 50 Celsius.", mcqIdx++));
  q.push(createMCQ("At which Russian Antarctic research station was the lowest officially verified natural temperature on the surface of Earth recorded at minus 89.2 degrees Celsius?", "Vostok Station", "Amundsen-Scott Station", "Concordia Station", "Located near the Southern Pole of Cold on the Antarctic ice sheet at 3,488m elevation, Vostok recorded minus 89.2C on 21 July 1983.", mcqIdx++));
  q.push(createMCQ("What is the highest mountain peak on the continent of Antarctica, rising to 4,892 meters in the Sentinel Range?", "Mount Vinson", "Mount Erebus", "Mount Tyree", "First climbed by an American Alpine Club expedition in 1966, Mount Vinson is one of the prized Seven Summits of mountaineering.", mcqIdx++));
  q.push(createMCQ("Which British explorer and adventurer was the first to visit both the North and South Poles by surface transport in the Transglobe Expedition?", "Sir Ranulph Fiennes", "Sir Vivian Fuchs", "Bear Grylls", "Guinness World Records described Ranulph Fiennes as The World's Greatest Living Explorer for his polar and desert expeditions.", mcqIdx++));
  q.push(createMCQ("What active volcano in Antarctica is famous for hosting a persistent boiling phonolitic lava lake in its summit crater?", "Mount Erebus", "Mount Terror", "Mount Sidley", "Discovered in 1841 by Sir James Clark Ross, Mount Erebus is the southernmost active volcano on Earth.", mcqIdx++));
  q.push(createNumber("What is the lowest naturally recorded surface temperature on Earth in degrees Celsius, measured at Vostok Station in 1983?", -89, "degrees Celsius", "-89.2 °C (-128.6 °F)", "The thermometer at Vostok Station dropped to minus 89.2 degrees Celsius (minus 128.6 °F) on 21 July 1983, the coldest natural temperature ever measured on Earth."));

  return {
    id: "extreme-sports-adventures-60",
    theme: "Extreme Sports: Polar Expeditions & Mountain Endurance",
    title: "Extreme Sports: Polar Expeditions & Mountain Endurance",
    description: "A 60-question grand master assessment exploring Everest summits, the heroic race to the South Pole, Arctic pack ice, Nazare monster waves, Alex Honnold's free soloing, Red Bull Stratos, desert ultramarathons, freediving abyss limits, and solo global yachting.",
    category: "Sports, Records & General Knowledge",
    difficulty: "moderate",
    createdAt: "2026-08-27T00:00:00Z",
    questions: q
  };
}

// -------------------------------------------------------------
// QUIZ 15: video-games-gaming-history-60
// -------------------------------------------------------------
function getVideoGamesQuiz() {
  let mcqIdx = 0;
  const q = [];

  // Cycle 1: Arcade Dawn & Birth of Commercial Gaming
  q.push(createMCQ("Which pioneering coin-operated arcade table tennis simulation game released by Atari in 1972 helped launch the commercial video game industry?", "Pong", "Computer Space", "Spacewar!", "Created by Allan Alcorn under Atari founder Nolan Bushnell, Pong became a massive commercial sensation in taverns and arcades worldwide.", mcqIdx++));
  q.push(createMCQ("Which iconic 1978 Taito arcade shoot 'em up game designed by Tomohiro Nishikado caused a temporary shortage of 100-yen coins in Japan?", "Space Invaders", "Galaxian", "Asteroids", "Space Invaders introduced descending alien waves, continuous background heartbeat music, and popularized the high-score concept in arcades.", mcqIdx++));
  q.push(createMCQ("Which yellow, pizza-shaped character was created by Toru Iwatani for Namco in 1980, becoming an international pop culture icon?", "Pac-Man", "Q*bert", "Dig Dug", "Iwatani designed Pac-Man to appeal to women and families, navigating mazes while dodging ghosts Blinky, Pinky, Inky, and Clyde.", mcqIdx++));
  q.push(createMCQ("Which 1979 Atari arcade game by Ed Logg utilized monochrome vector graphics to let players shoot space rocks and flying saucers?", "Asteroids", "Lunar Lander", "Tempest", "Asteroids introduced wraparound screen mechanics and became Atari's best-selling arcade cabinet of all time.", mcqIdx++));
  q.push(createMCQ("Which 1981 Nintendo arcade game designed by Shigeru Miyamoto introduced Jumpman (later Mario) climbing girders to rescue Pauline from an ape?", "Donkey Kong", "Mario Bros.", "Popeye", "Donkey Kong established Nintendo as a major force in the arcade market and invented key conventions of the platforming video game genre.", mcqIdx++));
  q.push(createNumber("In what year CE did Atari release the groundbreaking coin-operated arcade game Pong?", 1972, "CE", "November 1972", "Atari released the commercial Pong arcade cabinet on 29 November 1972, installing the first test unit at Andy Capp's Tavern in California."));

  // Cycle 2: The 1983 Crash & NES Resurrection
  q.push(createMCQ("What catastrophic event struck the North American video game market in 1983 due to market saturation, low-quality software, and competition from PCs?", "The Video Game Crash of 1983", "The Great Console Depletion", "The Silicon Winter", "Revenues dropped by roughly 97 percent, leading Atari to famously bury millions of unsold cartridges, including E.T., in an Alamogordo, New Mexico landfill.", mcqIdx++));
  q.push(createMCQ("Which 8-bit home console released by Nintendo in North America in 1985 single-handedly revived the Western console gaming market?", "Nintendo Entertainment System (NES)", "Sega Master System", "Atari 7800", "Marketed as the Famicom in Japan, Nintendo disguised the NES as an entertainment system bundled with R.O.B. the robot to overcome retailer skepticism.", mcqIdx++));
  q.push(createMCQ("What emblem did Nintendo place on licensed cartridges starting with the NES to assure consumers of software quality and compatibility?", "Nintendo Seal of Quality", "Nintendo 100% Certified", "Famicom Gold Standard", "Nintendo strictly limited third-party publishers to five games per year to prevent market flooding and maintain consumer trust.", mcqIdx++));
  q.push(createMCQ("Which Shigeru Miyamoto masterpiece bundled with the NES in 1985 established the gold standard for fluid side-scrolling platformer games?", "Super Mario Bros.", "The Legend of Zelda", "Metroid", "Super Mario Bros. sold over 40 million copies on the NES, featuring secret warp zones, power-up mushrooms, and Koji Kondo's memorable musical score.", mcqIdx++));
  q.push(createMCQ("Which 1986 action-adventure game designed by Shigeru Miyamoto introduced gold cartridges, battery-backed save files, and open-ended exploration in Hyrule?", "The Legend of Zelda", "Dragon Quest", "Final Fantasy", "The Legend of Zelda let players explore dungeons and overworlds non-linearly, collecting the Triforce to rescue Princess Zelda from Ganon.", mcqIdx++));
  q.push(createNumber("In what year CE was the Nintendo Entertainment System (NES) officially released in North America with its New York test launch?", 1985, "CE", "October 1985", "Nintendo launched the NES in the New York City test market on 18 October 1985 before rolling out nationwide across 1986."));

  // Cycle 3: The 16-Bit Console Wars
  q.push(createMCQ("Which blue mascot was created by Sega in 1991 to showcase the Genesis console's processing speed and rival Nintendo's Mario?", "Sonic the Hedgehog", "Alex Kidd", "Knuckles the Echidna", "Programmed by Yuji Naka with character design by Naoto Ohshima, Sonic's supersonic speed became the central weapon in Sega's Genesis does what Nintendon't campaign.", mcqIdx++));
  q.push(createMCQ("What revolutionary visual rendering mode on the Super Nintendo (SNES) allowed background layers to rotate and scale, creating pseudo-3D effects in F-Zero?", "Mode 7", "Super FX", "Vector Matrix", "Mode 7 graphics powered flagship titles like F-Zero, Super Mario Kart, and Pilotwings, giving the 16-bit SNES a unique visual depth advantage.", mcqIdx++));
  q.push(createMCQ("Which 1991 Capcom fighting game became a worldwide arcade phenomenon, introducing combo mechanics and eight playable World Warriors?", "Street Fighter II", "Fatal Fury", "The King of Fighters", "Street Fighter II revolutionized competitive gaming, spawning local arcade scenes where players queued quarters on cabinets to challenge winners.", mcqIdx++));
  q.push(createMCQ("Which 1992 Midway fighting game featuring digitized photographic graphics, decapitations, and Fatalities led directly to the creation of the ESRB rating system?", "Mortal Kombat", "Killer Instinct", "Primal Rage", "Mortal Kombat's graphic gore provoked 1993 US Congressional hearings on video game violence, prompting the industry to form the Entertainment Software Rating Board.", mcqIdx++));
  q.push(createMCQ("Which British developer partnered with Nintendo in 1994 to produce Donkey Kong Country, using groundbreaking pre-rendered 3D silicon graphics on SNES?", "Rare", "Argonaut Games", "Psygnosis", "Donkey Kong Country sold over nine million copies, proving the 16-bit SNES could visually rival early 32-bit CD-ROM consoles.", mcqIdx++));
  q.push(createNumber("How many playable World Warrior characters were selectable in the original 1991 arcade release of Capcom's Street Fighter II?", 8, "characters", "8 World Warriors", "The original Street Fighter II roster featured eight selectable fighters: Ryu, Ken, Chun-Li, Guile, Blanka, Dhalsim, E. Honda, and Zangief."));

  // Cycle 4: The 3D Revolution & PlayStation
  q.push(createMCQ("Which company entered the console market in 1994 with the PlayStation after a failed CD-ROM add-on partnership with Nintendo?", "Sony", "Panasonic", "Philips", "Spearheaded by engineer Ken Kutaragi, the Sony PlayStation utilized CD-ROM storage and dedicated 3D geometry hardware to dominate the 32-bit era.", mcqIdx++));
  q.push(createMCQ("Which landmark 1996 Nintendo 64 launch title defined fluid analog 3D camera control, dynamic physics, and triple jumps in full three dimensions?", "Super Mario 64", "Banjo-Kazooie", "Rayman 2", "Super Mario 64 set the benchmark for third-person 3D movement and platforming that all subsequent 3D video games adopted.", mcqIdx++));
  q.push(createMCQ("Which 1998 Nintendo 64 epic introduced Z-targeting lock-on combat and is widely ranked among the highest-rated games in review history on Metacritic?", "The Legend of Zelda: Ocarina of Time", "The Legend of Zelda: Majora's Mask", "GoldenEye 007", "Ocarina of Time solved 3D melee targeting with its Z-targeting mechanic and immersed players in an epic time-traveling adventure across Hyrule.", mcqIdx++));
  q.push(createMCQ("Which Square RPG released on three PlayStation CD-ROMs in 1997 popularized Japanese role-playing games globally with Cloud Strife and Sephiroth?", "Final Fantasy VII", "Chrono Cross", "Xenogears", "Final Fantasy VII featured cinematic 3D CGI cutscenes, a sweeping orchestral score by Nobuo Uematsu, and sold over 14 million copies worldwide.", mcqIdx++));
  q.push(createMCQ("Which 1996 survival horror game by Capcom, directed by Shinji Mikami, trapped players in the Spencer Mansion fighting zombies and the T-virus?", "Resident Evil (Biohazard)", "Silent Hill", "Alone in the Dark", "Resident Evil popularized fixed cinematic camera angles, inventory management, and coined the term survival horror for video games.", mcqIdx++));
  q.push(createNumber("How many million total units did the original Sony PlayStation console sell worldwide across its lifespan?", 102, "million units", "approx. 102.4M consoles", "The original Sony PlayStation became the first video game console in history to ship more than 100 million units, finishing at 102.49 million."));

  // Cycle 5: PC Gaming Milestones & FPS Legends
  q.push(createMCQ("Which 1993 first-person shooter by id Software (John Carmack and John Romero) revolutionized PC graphics, networked deathmatches, and user modding?", "Doom", "Wolfenstein 3D", "Duke Nukem 3D", "Distributed via shareware, Doom was installed on more office and university PCs in 1993 than Microsoft's Windows operating system.", mcqIdx++));
  q.push(createMCQ("Which 1998 debut first-person shooter by Valve followed silent physicist Gordon Freeman through the Black Mesa Research Facility without cutscenes?", "Half-Life", "Deus Ex", "System Shock 2", "Half-Life revolutionized video game storytelling by delivering all narrative events in real-time through the player's direct unbroken first-person perspective.", mcqIdx++));
  q.push(createMCQ("Which 1998 real-time strategy game by Blizzard Entertainment became a massive national esports phenomenon in South Korea with televised leagues?", "StarCraft", "Warcraft II", "Command & Conquer", "StarCraft's three perfectly balanced asymmetrical factions (Terran, Zerg, and Protoss) set the standard for competitive RTS gaming.", mcqIdx++));
  q.push(createMCQ("Which groundbreaking 1996 id Software title was the first FPS to feature fully 3D polygonal models, free mouselook, and TCP/IP Internet multiplayer?", "Quake", "Unreal", "Hexen", "Quake popularized rocket jumping, clan matches, and spawned legendary mods like Team Fortress and the Machinima digital filmmaking movement.", mcqIdx++));
  q.push(createMCQ("What legendary 1999 tactical team shooter originated as a free community modification (mod) for Valve's Half-Life by Minh Le and Jess Cliffe?", "Counter-Strike", "Team Fortress Classic", "Day of Defeat", "Counter-Strike pit Terrorists against Counter-Terrorists in bomb defusal and hostage rescue, becoming one of the most enduring esports in history.", mcqIdx++));
  q.push(createNumber("In what year CE did id Software release the legendary, industry-defining PC first-person shooter Doom?", 1993, "CE", "December 1993", "Doom was uploaded to an FTP server at the University of Wisconsin-Parkside on 10 December 1993, crashing the university network under download volume."));

  // Cycle 6: Open Worlds & Blockbuster RPGs
  q.push(createMCQ("Which 2001 Rockstar Games blockbuster revolutionized the industry by translating open-world crime gameplay into a fully 3D living Liberty City?", "Grand Theft Auto III", "Mafia", "Driver", "GTA III gave players unprecedented sandbox freedom, radio stations, and mission structures, establishing the template for modern open-world games.", mcqIdx++));
  q.push(createMCQ("Which massive 2011 Bethesda action RPG set in the snowy province of Tamriel allowed players to shout Dragon Shouts (Thu'um) as the Dragonborn?", "The Elder Scrolls V: Skyrim", "The Elder Scrolls IV: Oblivion", "Fallout 3", "Skyrim sold over 60 million copies across platforms, becoming an enduring cultural touchstone with its iconic opening: Hey, you. You're finally awake.", mcqIdx++));
  q.push(createMCQ("Which Polish developer created The Witcher 3: Wild Hunt in 2015, based on the dark fantasy novels of Andrzej Sapkowski featuring Geralt of Rivia?", "CD Projekt Red", "Techland", "People Can Fly", "The Witcher 3 won hundreds of Game of the Year awards for its morally gray quests, immersive open world, and acclaimed expansions Hearts of Stone and Blood and Wine.", mcqIdx++));
  q.push(createMCQ("Which 2004 Blizzard subscription MMORPG set in the world of Azeroth became a worldwide cultural phenomenon with over 12 million peak active subscribers?", "World of Warcraft", "EverQuest", "Guild Wars", "World of Warcraft streamlined MMO mechanics, raid dungeons, and Horde vs. Alliance faction warfare, defining online gaming culture for decades.", mcqIdx++));
  q.push(createMCQ("Which post-apocalyptic role-playing franchise featuring Vault Boy, Pip-Boys, and atomic 1950s retro-futurism was created by Interplay and expanded by Bethesda?", "Fallout", "Wasteland", "Metro 2033", "War. War never changes is the famous opening catchphrase across the Fallout series, set in devastated irradiated wasteland America.", mcqIdx++));
  q.push(createNumber("What was the peak worldwide active subscriber count in millions achieved by Blizzard's MMORPG World of Warcraft in 2010?", 12, "million subscribers", "12 million subscribers", "World of Warcraft reached its peak of 12 million active monthly paying subscribers following the release of the Wrath of the Lich King expansion."));

  // Cycle 7: Handheld Dominance & Pokemon
  q.push(createMCQ("Which veteran Nintendo engineer designed the Game Boy, Game & Watch, and D-pad directional controller before his tragic passing in 1997?", "Gunpei Yokoi", "Satoru Iwata", "Hiroshi Yamauchi", "Yokoi's philosophy of Lateral Thinking with Withered Technology used mature, affordable technology (monochrome screen, 4 AA batteries) to build the ultra-durable Game Boy.", mcqIdx++));
  q.push(createMCQ("Which Russian programmer created the legendary falling-block puzzle game Tetris in 1984 while working at the Soviet Academy of Sciences in Moscow?", "Alexey Pajitnov", "Eugene Nalimov", "Dmitry Pavlovsky", "Tetris became a global addiction when bundled with every original Nintendo Game Boy in 1989, selling tens of millions of units worldwide.", mcqIdx++));
  q.push(createMCQ("Which Japanese game designer inspired by childhood insect collecting created Pokemon (Pocket Monsters) for Game Freak and Nintendo in 1996?", "Satoshi Tajiri", "Ken Sugimori", "Junichi Masuda", "Satoshi Tajiri utilized the Game Boy Link Cable to allow players to trade and battle Pokemon, creating the highest-grossing media franchise in human history.", mcqIdx++));
  q.push(createMCQ("Which innovative dual-screen handheld console released by Nintendo in 2004 featured a built-in touchscreen, microphone, and Wi-Fi capability?", "Nintendo DS", "PlayStation Portable (PSP)", "Game Boy Advance SP", "The Nintendo DS sold over 154 million units worldwide, appealing to broad audiences through titles like Brain Age, Nintendogs, and Mario Kart DS.", mcqIdx++));
  q.push(createMCQ("What is the iconic electric mouse Pokemon that serves as the universal mascot of the global Pokemon franchise?", "Pikachu", "Eevee", "Charmander", "Voiced by Ikue Otani, Pikachu (Pokedex #025) became one of the most recognizable cultural symbols in the world alongside Mickey Mouse.", mcqIdx++));
  q.push(createNumber("How many original Generation 1 Pokemon species were cataloged in the Pokedex of Pokemon Red and Blue?", 151, "Pokemon species", "151 original Pokemon", "The original Kanto Pokedex spanned from Bulbasaur (#001) to Mew (#151), setting off the Gotta Catch 'Em All global phenomenon."));

  // Cycle 8: Sixth & Seventh Generation Blockbusters
  q.push(createMCQ("Which 128-bit home console released by Sony in 2000 is the best-selling video game console of all time, selling over 155 million units?", "PlayStation 2", "Xbox", "Nintendo GameCube", "The PS2's built-in DVD video player, backward compatibility with PS1 games, and massive software library made it a dominant entertainment center.", mcqIdx++));
  q.push(createMCQ("Which flagship sci-fi first-person shooter franchise developed by Bungie launched Microsoft's original Xbox console in November 2001?", "Halo: Combat Evolved", "Gears of War", "Mass Effect", "Halo introduced Master Chief, the artificial intelligence Cortana, two-weapon limits, regenerating shields, and popularized dual-analog console shooting.", mcqIdx++));
  q.push(createMCQ("Which Nintendo home console released in 2006 captured the mainstream world with its motion-sensing Wii Remote controller and Wii Sports?", "Wii", "Wii U", "GameCube", "The Wii sold over 101 million consoles, bringing grandparents, children, and non-gamers together to play virtual tennis, bowling, and golf.", mcqIdx++));
  q.push(createMCQ("Which 2007 post-apocalyptic underwater first-person shooter by Irrational Games challenged players with objectivist philosophy in the submerged city of Rapture?", "BioShock", "System Shock", "Dead Space", "Directed by Ken Levine, BioShock features the Big Daddies, Little Sisters, and the iconic plot twist phrase: Would you kindly?", mcqIdx++));
  q.push(createMCQ("Which 2013 Naughty Dog cinematic survival masterpiece on PlayStation 3 chronicled Joel and Ellie's journey across a fungal zombie wasteland?", "The Last of Us", "Uncharted 2", "Days Gone", "The Last of Us received widespread acclaim for profound emotional storytelling, stellar voice acting by Troy Baker and Ashley Johnson, and tense stealth gameplay.", mcqIdx++));
  q.push(createNumber("How many million units has the Sony PlayStation 2 sold worldwide, holding the record as the best-selling video game console in history?", 155, "million consoles", "approx. 155M consoles", "Sony officially announced that the PlayStation 2 achieved over 155 million lifetime console sales before production ended in 2013."));

  // Cycle 9: The Indie Revolution & Sandboxes
  q.push(createMCQ("Which Swedish programmer known as Notch created the infinite voxel sandbox phenomenon Minecraft, which became the best-selling game of all time?", "Markus Persson", "Jens Bergensten", "Daniel Kaplan", "First released publicly as an alpha in May 2009, Minecraft allows players to mine, craft, build, and survive in infinite procedurally generated block worlds.", mcqIdx++));
  q.push(createMCQ("Which solo developer, known as Toby Fox, created the beloved 2015 indie RPG Undertale where players can complete the game without killing any enemies?", "Toby Fox", "Jonathan Blow", "Phil Fish", "Undertale featured witty dialogue, bullet-hell dodging mechanics, a legendary soundtrack, and unforgettable characters Sans and Papyrus.", mcqIdx++));
  q.push(createMCQ("Which Australian two-person studio, Team Cherry, created the critically acclaimed 2017 atmospheric hand-drawn Metroidvania game Hollow Knight?", "Team Cherry", "Supergiant Games", "Motion Twin", "Hollow Knight captivated players with fluid nail combat, expansive lore in the ruined insect kingdom of Hallownest, and Christopher Larkin's melancholic score.", mcqIdx++));
  q.push(createMCQ("Which solo developer spent over four years creating the charming, multi-million-selling farming simulation RPG Stardew Valley as ConcernedApe?", "Eric Barone", "Lucas Pope", "Edmund McMillen", "Eric Barone designed all programming, pixel art, music, and dialogue alone, paying homage to the classic Harvest Moon series.", mcqIdx++));
  q.push(createMCQ("Which 2008 indie platformer by Jonathan Blow manipulated time rewind mechanics to rescue a princess, heralding the modern indie game movement on Xbox Live Arcade?", "Braid", "Limbo", "Super Meat Boy", "Braid demonstrated that small independent developers could achieve commercial and critical success on digital console storefronts with artistic puzzle design.", mcqIdx++));
  q.push(createNumber("Approximately how many million copies has Minecraft sold worldwide across all platforms, making it the best-selling video game in history?", 300, "million copies", "over 300M copies", "Mojang and Microsoft officially confirmed in late 2023 that Minecraft surpassed 300 million copies sold worldwide."));

  // Cycle 10: Modern Esports & Battle Royales
  q.push(createMCQ("Which Riot Games multiplayer online battle arena (MOBA) is the most watched competitive esport in the world, culminating in the annual World Championship?", "League of Legends", "Dota 2", "Heroes of the Storm", "League of Legends features millions of daily active players and sells out massive Olympic stadiums worldwide for its Worlds finals.", mcqIdx++));
  q.push(createMCQ("Which 100-player free-to-play battle royale game by Epic Games became a global cultural juggernaut in 2017 with building mechanics and crossover events?", "Fortnite", "PUBG: Battlegrounds", "Apex Legends", "Fortnite hosted virtual live concerts by Travis Scott and Ariana Grande, introducing in-game pop culture crossover skins spanning Marvel, Star Wars, and anime.", mcqIdx++));
  q.push(createMCQ("Which annual Valve tournament for Dota 2 has repeatedly awarded the largest single prize pool in esports history, exceeding 40 million dollars in 2021?", "The International", "EVO", "Intel Extreme Masters", "The International crowdfunded its massive prize pool through in-game Battle Pass (Compendium) purchases by the global Dota community.", mcqIdx++));
  q.push(createMCQ("What is the term for the video game subculture of attempting to complete a game as quickly as humanly possible, celebrated at Games Done Quick marathons?", "Speedrunning", "Score-attacking", "Tool-assisting", "Speedrunners utilize routing, frame-perfect inputs, sequence breaking, and game physics glitches across categories like Any% and 100%.", mcqIdx++));
  q.push(createMCQ("Which hybrid home and portable console released by Nintendo in March 2017 features detachable Joy-Con controllers and dockable TV play?", "Nintendo Switch", "Wii U", "Nintendo 3DS", "The Nintendo Switch became Nintendo's best-selling home console, powered by masterpieces like The Legend of Zelda: Breath of the Wild and Mario Kart 8 Deluxe.", mcqIdx++));
  q.push(createNumber("What is the maximum number of players who drop out of the Battle Bus onto the island in a standard Fortnite Battle Royale match?", 100, "players", "100 players per match", "Every standard solo, duo, or squad Fortnite Battle Royale match begins with up to 100 players skydiving onto the island until one survivor remains."));

  return {
    id: "video-games-gaming-history-60",
    theme: "Video Game History: Arcade Pioneers, Consoles & Icons",
    title: "Video Game History: Arcade Pioneers, Consoles & Icons",
    description: "A 60-question grand master assessment exploring Pong and the arcade dawn, the 1983 crash, NES resurrection, the 16-bit console wars, 3D revolutions on PlayStation and N64, Doom and PC legends, Grand Theft Auto, Game Boy and Pokemon, the PS2 era, indie masterpieces, and modern battle royales.",
    category: "Sports, Records & General Knowledge",
    difficulty: "moderate",
    createdAt: "2026-08-27T00:00:00Z",
    questions: q
  };
}

// -------------------------------------------------------------
// QUIZ 16: world-records-human-extremes-60
// -------------------------------------------------------------
function getWorldRecordsQuiz() {
  let mcqIdx = 0;
  const q = [];

  // Cycle 1: Human Stature & Physical Extremes
  q.push(createMCQ("Who was the tallest verified human in recorded medical history, measured at an astonishing 272 cm (8 ft 11.1 in) before his death in 1940?", "Robert Wadlow", "John Rogan", "Sultan Kosen", "Born in Alton, Illinois, Robert Wadlow's extraordinary height was caused by hypertrophy of his pituitary gland, which produced excessive human growth hormone.", mcqIdx++));
  q.push(createMCQ("Who is the shortest verified adult person in medical history, measuring just 54.6 cm (21.5 inches) tall from Nepal?", "Chandra Bahadur Dangi", "Gul Mohammed", "Junrey Balawing", "Chandra Bahadur Dangi lived in a remote village in Dang district, Nepal, officially measured by Guinness World Records in 2012.", mcqIdx++));
  q.push(createMCQ("Which Turkish farmer holds the Guinness World Record as the tallest living man on Earth, standing at 251 cm (8 ft 2.8 in)?", "Sultan Kosen", "Brahim Takioullah", "Morteza Mehrzad", "Sultan Kosen also holds the world record for the largest hands on a living person, measuring 28.5 cm (11.2 inches) from wrist to middle fingertip.", mcqIdx++));
  q.push(createMCQ("Which Indian woman holds the Guinness World Record as the world's shortest living woman, measuring 62.8 cm (24.7 inches)?", "Jyoti Amge", "Bridgette Jordan", "Madge Bester", "Jyoti Amge, who has a form of dwarfism called achondroplasia, is an actress who starred in American Horror Story: Freak Show.", mcqIdx++));
  q.push(createMCQ("What endocrine gland located at the base of the human brain regulates growth hormone, whose overactivity causes gigantism and acromegaly?", "Pituitary gland", "Thyroid gland", "Adrenal gland", "The anterior pituitary gland secretes somatotropin (growth hormone); non-cancerous adenoma tumors on the gland can trigger continuous linear bone growth.", mcqIdx++));
  q.push(createNumber("What was the exact standing height of Robert Wadlow, the tallest person in verified medical history, in centimeters?", 272, "centimeters", "8 ft 11.1 in", "Robert Wadlow was measured at exactly 272.0 centimeters (8 feet 11.1 inches) on 27 June 1940, shortly before his death at age 22."));

  // Cycle 2: Lifespan & Longevity Milestones
  q.push(createMCQ("Which French supercentenarian holds the undisputed Guinness World Record for the longest verified human lifespan in history, living 122 years and 164 days?", "Jeanne Calment", "Sarah Knauss", "Kane Tanaka", "Born in Arles in 1875, Jeanne Calment met Vincent van Gogh as a teenager, rode a bicycle until age 100, and lived independently until 110.", mcqIdx++));
  q.push(createMCQ("Who was the oldest verified man in human history, living to 116 years and 54 days in Kyoto Prefecture, Japan?", "Jiroemon Kimura", "Christian Mortensen", "Emiliano Mercado del Toro", "Born in 1897, Jiroemon Kimura attributed his longevity to eating small food portions (hara hachi bun me) and reading newspapers daily.", mcqIdx++));
  q.push(createMCQ("What demographic term designates a person who has achieved the verified age of 110 years or older?", "Supercentenarian", "Centenarian", "Nonagenarian", "While approximately one in 1,000 centenarians reaches 110, supercentenarians exhibit extraordinary biological resilience against cardiovascular disease and cancer.", mcqIdx++));
  q.push(createMCQ("What demographic term coined by Dan Buettner identifies geographic regions such as Okinawa (Japan) and Sardinia (Italy) with exceptional concentrations of centenarians?", "Blue Zones", "Longevity Hotspots", "Golden Havens", "Blue Zones share common lifestyle characteristics: plant-heavy diets, natural daily physical movement, strong community social ties, and purposeful living.", mcqIdx++));
  q.push(createMCQ("Which American woman from Pennsylvania was the second oldest verified person in history, living 119 years and 97 days before passing in 1999?", "Sarah Knauss", "Susannah Mushatt Jones", "Delphia Welford", "Sarah Knauss lived through seven American wars, the sinking of the Titanic, and the invention of automobiles, airplanes, and the Internet.", mcqIdx++));
  q.push(createNumber("How many full completed years did French supercentenarian Jeanne Calment live, setting the all-time verified human lifespan record?", 122, "years", "122 years 164 days", "Jeanne Calment lived 122 completed years and 164 days from 21 February 1875 until her death on 4 August 1997."));

  // Cycle 3: Speed, Sprinting & Reaction Extremes
  q.push(createMCQ("During his world-record 9.58-second 100-meter sprint in Berlin in 2009, what peak top speed in km/h did Jamaican sprinter Usain Bolt achieve?", "44.72 km/h", "38.50 km/h", "50.10 km/h", "Usain Bolt hit his peak instantaneous velocity between the 60m and 80m marks, covering that 20-meter split in a blistering 1.61 seconds.", mcqIdx++));
  q.push(createMCQ("Which American sprinter set the women's 100-meter world record of 10.49 seconds in Indianapolis in 1988, a mark that has stood for over three decades?", "Florence Griffith-Joyner", "Carmelita Jeter", "Elaine Thompson-Herah", "Flo-Jo also set the women's 200-meter world record of 21.34 seconds at the 1988 Seoul Olympics, celebrated for her flamboyant one-legged running suits.", mcqIdx++));
  q.push(createMCQ("In October 2019 in Vienna, who became the first human to run a marathon distance in under two hours (1 hour, 59 minutes, 40 seconds) in the INEOS 1:59 Challenge?", "Eliud Kipchoge", "Kenenisa Bekele", "Kelvin Kiptum", "Aided by rotating pace car lasers and alternating teams of world-class pacemakers, Kipchoge proved that no human is limited.", mcqIdx++));
  q.push(createMCQ("Who holds the Guinness World Record for the fastest typing speed on a Dvorak keyboard, achieving peak speeds of 212 words per minute?", "Barbara Blackburn", "Stella Pajunas", "Sean Wrona", "Blackburn maintained a sustained typing speed of 150 wpm for 50 minutes and clocked peak bursts over 212 wpm in official tests.", mcqIdx++));
  q.push(createMCQ("What is the average human visual reaction time to an unexpected visual stimulus under normal laboratory conditions?", "200 to 250 milliseconds", "50 to 80 milliseconds", "500 to 600 milliseconds", "Auditory reaction times are even faster at roughly 140 to 160 milliseconds because sound signals reach the brain stem more directly than visual stimuli.", mcqIdx++));
  q.push(createNumber("What peak sprinting speed in kilometers per hour (rounded to the nearest whole integer) did Usain Bolt reach during his 100m world record?", 44, "km/h", "approx. 27.78 mph", "Usain Bolt reached an extraordinary peak speed of 44.72 km/h (27.78 mph) between the 60-meter and 80-meter marks in Berlin in 2009."));

  // Cycle 4: Strength & Powerlifting Feats
  q.push(createMCQ("Which Icelandic strongman and actor set the world record for the heaviest deadlift in history by lifting 501 kg (1,105 lbs) in May 2020?", "Hafthor Bjornsson", "Eddie Hall", "Zydrunas Savickas", "Hafthor The Mountain Bjornsson lifted the 501kg barbell at Thor's Power Gym in Reykjavik under official refereeing.", mcqIdx++));
  q.push(createMCQ("Which British strongman became the first human in history to officially deadlift 500 kg (1,102 lbs) at the World Deadlift Championships in 2016?", "Eddie Hall", "Brian Shaw", "Tom Stoltman", "Eddie The Beast Hall's superhuman lift pushed blood pressure so high that he briefly lost consciousness immediately after dropping the bar.", mcqIdx++));
  q.push(createMCQ("Which 19th-century French-Canadian strongman was renowned for incredible feats such as lifting 500 pounds with one finger and resisting two draft horses?", "Louis Cyr", "Eugen Sandow", "Arthur Saxon", "Louis Cyr never suffered defeat in any strength contest and is considered by historians to be the strongest man of the 19th century.", mcqIdx++));
  q.push(createMCQ("Which American weightlifting pioneer won Olympic gold in 1956 and was credited with a legendary back lift of 6,270 lbs (2,840 kg) from trestles?", "Paul Anderson", "Tommy Kono", "Norb Schemansky", "Paul Anderson's immense squatting strength helped establish powerlifting as an international competitive sport.", mcqIdx++));
  q.push(createMCQ("Which Lithuanian strongman won the World's Strongest Man title four times and the Arnold Strongman Classic a record eight times?", "Zydrunas Savickas", "Mariusz Pudzianowski", "Magnus Ver Magnusson", "Big Z is widely regarded as one of the greatest overhead pressers and static strength athletes in strongman history.", mcqIdx++));
  q.push(createNumber("What is the official world record weight in kilograms lifted by Hafthor Bjornsson for the heaviest deadlift in history?", 501, "kilograms", "1105 lbs", "Hafthor Bjornsson lifted exactly 501 kilograms (1,104.5 pounds) on 2 May 2020, surpassing Eddie Hall's 500kg record."));

  // Cycle 5: Memory & Mental Calculation Feats
  q.push(createMCQ("Which Japanese mental memory master recited 100,000 decimal places of the mathematical constant Pi (π) from memory in 16 hours in 2006?", "Akira Haraguchi", "Rajveer Meena", "Lu Chao", "Haraguchi used a custom mnemonic system associating Japanese syllables with numbers, reciting digits continuously with short hourly breaks.", mcqIdx++));
  q.push(createMCQ("Which Indian mental calculation prodigy, known as The Human Computer, multiplied two randomly selected 13-digit numbers in 28 seconds at Imperial College London in 1980?", "Shakuntala Devi", "Srinivasa Ramanujan", "Priyamvada Natarajan", "Shakuntala Devi correctly multiplied 7,686,369,774,870 by 2,465,099,745,779 to produce the 26-digit product in under half a minute.", mcqIdx++));
  q.push(createMCQ("What ancient mnemonic technique, also known as the Method of Loci, involves visualizing items to be remembered in specific architectural rooms?", "Memory Palace technique", "Major System", "Peg System", "Attributed to the ancient Greek poet Simonides of Ceos, memory palaces allow mental athletes to memorize thousands of random digits and cards.", mcqIdx++));
  q.push(createMCQ("How many playing cards are in a standard deck that world memory champions can memorize in under 15 seconds?", "52 cards", "32 cards", "104 cards", "Memory champions convert pairs of cards into vivid animated images, placing them in predetermined locations along a mental journey.", mcqIdx++));
  q.push(createMCQ("Which German mental calculation champion holds multiple world records for calculating the calendar day of the week for arbitrary historical dates within milliseconds?", "Dr. Gert Mittring", "Rudiger Gamm", "Arthur Benjamin", "Mental calendar calculators utilize modular arithmetic algorithms to instantly determine the weekday of any date spanning millions of years.", mcqIdx++));
  q.push(createNumber("What is the world record time in seconds for memorizing the exact sequence of a shuffled 52-card deck of cards?", 12, "seconds", "approx. 12.74 seconds", "Elite memory grandmasters have achieved official competition records memorizing a complete 52-card deck in under 13 seconds (approx. 12.74s)."));

  // Cycle 6: Endurance & Breath-Holding Feats
  q.push(createMCQ("Which Croatian freediver set the Guinness World Record for the longest voluntary breath hold (static apnea) underwater at 24 minutes and 37 seconds in 2021?", "Budimir Sobat", "Aleix Segura", "Tom Sietas", "Budimir Buda Sobat performed pre-oxygenation with pure oxygen for 30 minutes prior to immersion, raising awareness for autism.", mcqIdx++));
  q.push(createMCQ("Which Dutch extreme athlete, known as The Iceman, has set dozens of world records for ice endurance and developed a specialized cold-exposure breathing method?", "Wim Hof", "Lewis Pugh", "Stig Severinsen", "Wim Hof demonstrated voluntary control over his autonomic nervous system and immune response during cold exposure trials at Radboud University.", mcqIdx++));
  q.push(createMCQ("Which Canadian hero with an amputated right leg ran 5,373 kilometers over 143 days in 1980 in the Marathon of Hope to raise cancer research funds?", "Terry Fox", "Rick Hansen", "Steve Fonyo", "Terry Fox ran a full marathon every single day across Canada until cancer spread to his lungs, inspiring annual Terry Fox Runs globally.", mcqIdx++));
  q.push(createMCQ("Which American ultramarathoner famously ran 50 official marathons in 50 US states in 50 consecutive days in 2006?", "Dean Karnazes", "Scott Jurek", "David Goggins", "Dean Karnazes completed his 50-50-50 challenge by finishing the New York City Marathon on day 50, running a total of 1,310 miles.", mcqIdx++));
  q.push(createMCQ("What British endurance swimmer completed long-distance swims in freezing waters across the North Pole and Antarctic without a wetsuit to advocate for ocean protection?", "Lewis Pugh", "Ross Edgley", "Martin Strel", "Lewis Pugh was designated the UN Patron of the Oceans, training his body to raise his core temperature through anticipatory thermogenesis.", mcqIdx++));
  q.push(createNumber("What is the record time in full minutes for the longest voluntary breath hold underwater with oxygen pre-breathing set by Budimir Sobat?", 24, "minutes", "24 minutes 37 seconds", "Budimir Sobat held his breath underwater for 24 minutes and 37 seconds in Sisak, Croatia, on 27 March 2021."));

  // Cycle 7: High Altitude, Deep Diving & Fall Survival
  q.push(createMCQ("Which Yugoslav flight attendant miraculously survived the highest fall without a parachute in history after her plane exploded at 10,160 meters in 1972?", "Vesna Vulovic", "Juliane Koepcke", "Larisa Savitskaya", "Vesna Vulovic was pinned by a food cart in the tail section of JAT Flight 367, which landed at a glancing angle on a snow-covered pine slope in Czechoslovakia.", mcqIdx++));
  q.push(createMCQ("Which American computer scientist broke Baumgartner's skydiving altitude record in 2014 by jumping from a helium balloon at 41,419 meters (135,890 feet)?", "Alan Eustace", "Joe Kittinger", "Larry Walters", "Eustace was suspended directly from the balloon without a capsule, wearing a custom spacesuit designed by Paragon Space Development Corporation.", mcqIdx++));
  q.push(createMCQ("What cave in Abkhazia is recognized as the deepest known natural cave on Earth, explored to a depth of 2,212 meters (7,257 feet)?", "Veryovkina Cave", "Krubera Cave", "Mammoth Cave", "Speleologists take over a week of underground vertical rope ascents and descents to reach the subterranean terminal sump of Veryovkina Cave.", mcqIdx++));
  q.push(createMCQ("Which American ocean explorer completed the Five Deeps Expedition in 2019, diving solo to the deepest point of all five oceans in the submersible Limiting Factor?", "Victor Vescovo", "James Cameron", "Don Walsh", "Victor Vescovo reached a record depth of 10,928 meters in the Challenger Deep of the Mariana Trench, discovering new benthic species.", mcqIdx++));
  q.push(createMCQ("What Swiss engineer and American naval lieutenant made the first crewed descent to the bottom of the Mariana Trench in the bathyscaphe Trieste in 1960?", "Jacques Piccard and Don Walsh", "William Beebe and Otis Barton", "Auguste Piccard and Jacques Cousteau", "The bathyscaphe Trieste endured 1,000 atmospheres of crushing hydrostatic pressure during its historic dive to 10,911 meters on 23 January 1960.", mcqIdx++));
  q.push(createNumber("From what altitude in meters did flight attendant Vesna Vulovic fall and survive without a parachute in 1972?", 10160, "meters", "33330 feet", "Vesna Vulovic survived a free fall of 10,160 meters (33,330 feet), holding the Guinness World Record for the highest fall survived without a parachute."));

  // Cycle 8: Speedcubing & Dexterity Records
  q.push(createMCQ("Which American speedcuber set the official three-by-three Rubik's Cube single solve world record of 3.13 seconds in Long Beach, California in 2023?", "Max Park", "Yusheng Du", "Feliks Zemdegs", "Max Park, who is on the autism spectrum, solved the three-by-three cube in 3.13 seconds at the Pride in Long Beach 2023 competition, holding dozens of world records.", mcqIdx++));
  q.push(createMCQ("Which Australian speedcubing legend dominated competitive cubing for a decade, breaking over 120 official world records across various twisty puzzles?", "Feliks Zemdegs", "Mats Valk", "Tymon Kolasinski", "Zemdegs revolutionized lookahead technique and popularized the CFOP (Fridrich) method among millions of aspiring cubers worldwide.", mcqIdx++));
  q.push(createMCQ("What is the name of the most popular three-by-three Rubik's Cube speedcubing method, consisting of Cross, First Two Layers (F2L), Orientation (OLL), and Permutation (PLL)?", "CFOP Method", "Roux Method", "ZZ Method", "Developed by Jessica Fridrich and other cubers in the 1980s, the CFOP method solves the puzzle in four systematic, highly algorithmic steps.", mcqIdx++));
  q.push(createMCQ("Which Hungarian architect and professor of architecture invented the world-famous mechanical twisty puzzle the Magic Cube (Rubik's Cube) in 1974?", "Erno Rubik", "Laszlo Biro", "Janos Neumann", "Erno Rubik created the three-by-three cube in Budapest as a 3D geometric teaching model for his students, selling over 500 million units worldwide.", mcqIdx++));
  q.push(createMCQ("What competitive dexterity sport involves stacking twelve specially designed plastic cups in specific pyramid sequences against a digital timer?", "Sport Stacking (Cup Stacking)", "Cup Pong", "Speed Pitching", "Sport stacking develops hand-eye coordination, bilateral dexterity, and ambidexterity, with world record cycle times under 5 seconds.", mcqIdx++));
  q.push(createNumber("What is the single solve world record in seconds for the three-by-three Rubik's Cube achieved by Max Park in 2023 (rounded to the nearest integer)?", 3, "seconds", "3.13 seconds record", "Max Park set the stunning world record of 3.13 seconds on 11 June 2023 in California, executing roughly 10 moves per second."));

  // Cycle 9: Aviation & Space Endurance
  q.push(createMCQ("Which Russian cosmonaut holds the all-time record for the longest continuous single spaceflight in human history, spending 437 consecutive days aboard the Mir space station?", "Valeri Polyakov", "Sergei Krikalev", "Yuri Malenchenko", "Polyakov, a physician, orbited Earth 7,075 times between January 1994 and March 1995 to study how the human body endures long-duration microgravity for Mars missions.", mcqIdx++));
  q.push(createMCQ("Which American astronaut holds the record for the most cumulative days spent in space by any American or woman, totaling 675 days across multiple missions?", "Peggy Whitson", "Christina Koch", "Sunita Williams", "Dr. Peggy Whitson was the first female commander of the International Space Station and performed 10 spacewalks.", mcqIdx++));
  q.push(createMCQ("Which 1969 Apollo mission achieved the highest speed ever attained by a crewed vehicle, reaching 39,897 km/h (24,791 mph) during re-entry from the Moon?", "Apollo 10", "Apollo 11", "Apollo 13", "Crewed by Thomas Stafford, John Young, and Eugene Cernan, Apollo 10 served as the full dress rehearsal for the Apollo 11 lunar landing.", mcqIdx++));
  q.push(createMCQ("What NASA robotic space probe launched in 1977 is the farthest human-made object from Earth, traveling in interstellar space over 24 billion kilometers away?", "Voyager 1", "Voyager 2", "New Horizons", "Voyager 1 carries the Golden Record containing sounds and images of Earth, continuing to transmit scientific data back to NASA's Deep Space Network.", mcqIdx++));
  q.push(createMCQ("Which Russian cosmonaut holds the world record for the most cumulative time spent in space by any human, surpassing 1,000 total days across five missions in 2024?", "Oleg Kononenko", "Gennady Padalka", "Yuri Romanenko", "Oleg Kononenko reached the unprecedented 1,000-day cumulative space milestone on 4 June 2024 aboard the International Space Station.", mcqIdx++));
  q.push(createNumber("How many continuous days did Russian cosmonaut Valeri Polyakov spend aboard the Mir space station on his record-setting 1994 to 1995 mission?", 437, "days", "437 days 18 hours", "Valeri Polyakov lived aboard Mir for 437 days, 17 hours, and 58 minutes, the longest continuous spaceflight in human history."));

  // Cycle 10: Extreme Expeditions & Superlative Feats
  q.push(createMCQ("Which legendary British explorer led the Transglobe Expedition (1979 to 1982), completing the first surface circumnavigation of the world along its polar axis?", "Sir Ranulph Fiennes", "Sir Peter Blake", "Robert Swan", "Sir Ranulph Fiennes and Charles Burton traveled 52,000 miles across land, sea, and ice, crossing both the South and North Poles.", mcqIdx++));
  q.push(createMCQ("What is the highest commercial bungee jump in the world, allowing thrill-seekers to plunge 233 meters (764 feet) from a tower observation deck?", "Macau Tower Bungee Jump", "Verzasca Dam", "Bloukrans Bridge", "Operated by AJ Hackett, the Macau Tower jump uses a specialized deceleration system and guide cables to control the 200 km/h freefall.", mcqIdx++));
  q.push(createMCQ("Who was the managing director of the Guinness Brewery who conceived the idea for a definitive book of world records to settle pub arguments in 1951?", "Sir Hugh Beaver", "Arthur Guinness", "Norris McWhirter", "Sir Hugh Beaver got into a debate while hunting about the fastest game bird in Europe (the golden plover), leading him to commission the McWhirter twins to compile the book.", mcqIdx++));
  q.push(createMCQ("Which twin brothers compiled and edited the original Guinness Book of Records, published in Great Britain in 1955?", "Norris and Ross McWhirter", "Wilbur and Orville Wright", "Auguste and Louis Lumiere", "The McWhirter twins possessed encyclopedic memories, fact-checking records for the popular BBC television show Record Breakers for decades.", mcqIdx++));
  q.push(createMCQ("What is the deepest natural trench in the world, plunging to nearly 11,000 meters in the western Pacific Ocean?", "Mariana Trench", "Puerto Rico Trench", "Java Trench", "The Mariana Trench's deepest point, the Challenger Deep, exerts over 1,086 bars of pressure, comparable to having an elephant stand on your thumb.", mcqIdx++));
  q.push(createNumber("In what year CE was the first official edition of The Guinness Book of Records published in the United Kingdom?", 1955, "CE", "August 1955", "The first 198-page edition was bound on 27 August 1955, quickly topping British bestseller lists by Christmas."));

  return {
    id: "world-records-human-extremes-60",
    theme: "World Records: Human Limits & Superlative Feats",
    title: "World Records: Human Limits & Superlative Feats",
    description: "A 60-question grand master assessment exploring Robert Wadlow, supercentenarians, Usain Bolt's top sprinting speed, Hafthor's 501kg deadlift, memory prodigies, 24-minute breath holds, Vesna Vulovic's fall survival, 3.13-second Rubik's cube solves, and cosmonaut space endurance.",
    category: "Sports, Records & General Knowledge",
    difficulty: "moderate",
    createdAt: "2026-08-27T00:00:00Z",
    questions: q
  };
}

module.exports = {
  getChessQuiz,
  getExtremeSportsQuiz,
  getVideoGamesQuiz,
  getWorldRecordsQuiz
};

if (require.main === module) {
  const quizzes = [
    getChessQuiz(),
    getExtremeSportsQuiz(),
    getVideoGamesQuiz(),
    getWorldRecordsQuiz()
  ];
  
  for (const quiz of quizzes) {
    const dir = path.join('quizzes', quiz.id);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, 'dataset.json'), JSON.stringify(quiz, null, 2), 'utf8');
    console.log(`Wrote: ${dir}/dataset.json`);
  }
}
