const fs = require('fs');
const path = require('path');

function createMCQ(question, correctOption, wrongOption1, wrongOption2, explanation, mcqIndex) {
  const targetSlot = mcqIndex % 3;
  const options = [];
  if (targetSlot === 0) {
    options.push(correctOption, wrongOption1, wrongOption2);
  } else if (targetSlot === 1) {
    options.push(wrongOption1, correctOption, wrongOption2);
  } else {
    options.push(wrongOption1, wrongOption2, correctOption);
  }
  const cleanOptions = options.map(o => o.replace(/[()[\]{}]/g, '').trim());
  return {
    type: 'mcq',
    question: question.trim(),
    options: cleanOptions,
    correctIndex: targetSlot,
    explanation: explanation.trim()
  };
}

function createNumber(question, target, metricUnit, imperialDisplay, explanation) {
  return {
    type: 'number',
    question: question.trim(),
    target: typeof target === 'number' ? target : parseFloat(target),
    metricUnit: metricUnit.trim(),
    imperialDisplay: imperialDisplay ? imperialDisplay.trim() : undefined,
    explanation: explanation.trim()
  };
}

// -------------------------------------------------------------
// QUIZ 9: theater-opera-performing-arts-60
// -------------------------------------------------------------
function getTheaterOperaQuiz() {
  let mcqIdx = 0;
  const q = [];

  // Cycle 1: Ancient Greek Theater & Tragedies
  q.push(createMCQ("Who is traditionally celebrated as history's first actor, stepping out of the Greek chorus in 534 BCE to speak dialogue as a distinct character?", "Thespis", "Aeschylus", "Sophocles", "Thespis introduced spoken impersonation at the City Dionysia festival in Athens, from whose name the word thespian derives.", mcqIdx++));
  q.push(createMCQ("Which Athenian festival held in honor of the god of wine and theater staged the great competitive tragedy trilogies of classical antiquity?", "City Dionysia", "Panathenaea", "Eleusinian Mysteries", "The City Dionysia featured dramatic competitions where playwrights presented three connected tragedies followed by a comedic satyr play.", mcqIdx++));
  q.push(createMCQ("Which tragic Greek playwright wrote the only complete surviving tragic trilogy from antiquity, the Oresteia (Agamemnon, The Libation Bearers, and The Eumenides)?", "Aeschylus", "Euripides", "Aristophanes", "Aeschylus introduced the second actor, expanded dialogue, and explored cosmic justice, generational curses, and the creation of trial by jury.", mcqIdx++));
  q.push(createMCQ("Which Sophoclean tragedy portrays a King of Thebes who unwittingly fulfills a prophecy that he will kill his father and marry his mother?", "Oedipus Rex", "Antigone", "Ajax", "Oedipus Rex (Oedipus Tyrannus) was praised by Aristotle in the Poetics as the supreme exemplar of tragic dramatic structure and recognition (anagnorisis).", mcqIdx++));
  q.push(createMCQ("What was the circular dancing floor and primary performance space in an ancient Greek open-air theater called?", "Orchestra", "Skene", "Theatron", "The orchestra was the central level ground where the dramatic chorus sang, danced, and commented upon the unfolding tragic events.", mcqIdx++));
  q.push(createNumber("How many complete tragic trilogies have survived intact from ancient classical Greek dramatic literature?", 1, "trilogy", "1 complete trilogy (The Oresteia)", "The Oresteia by Aeschylus (comprising Agamemnon, The Libation Bearers, and The Eumenides) is the sole complete tragic trilogy surviving from ancient Greece."));

  // Cycle 2: Commedia dell'arte & Early Opera
  q.push(createMCQ("What professional Italian theatrical form popular from the 16th to 18th centuries relied on masked stock characters and improvised slapstick comedy (lazzi)?", "Commedia dell'arte", "Opera buffa", "Intermezzo", "Commedia dell'arte featured stock archetypes like the greedy merchant Pantalone, the pompous Il Dottore, and the acrobatic trickster servant Arlecchino.", mcqIdx++));
  q.push(createMCQ("Which group of Florentine Renaissance humanists, musicians, and poets sought to revive ancient Greek musical drama, inadvertently inventing opera?", "Florentine Camerata", "Accademia dei Lincei", "Arcadian Academy", "Gathering at the palace of Count Giovanni de' Bardi in the late 16th century, the Camerata developed monody (expressive solo singing over basso continuo).", mcqIdx++));
  q.push(createMCQ("Which Italian master's 1607 opera L'Orfeo, recounting Orpheus's descent into the underworld to rescue Eurydice, is hailed as the first operatic masterwork?", "Claudio Monteverdi", "Jacopo Peri", "Giulio Caccini", "Monteverdi used a large 40-piece orchestra and expressive vocal declamation to establish opera as a profound theatrical art form in Mantua.", mcqIdx++));
  q.push(createMCQ("In which maritime Italian city was the world's first public commercial opera house, the Teatro San Cassiano, opened in 1637?", "Venice", "Florence", "Naples", "The opening of Teatro San Cassiano in Venice democratized opera, shifting it from aristocratic private court entertainment to ticketed public performance.", mcqIdx++));
  q.push(createMCQ("What acrobatic, diamond-pattern-costumed Commedia dell'arte character carries a wooden slapstick and serves as a witty servant?", "Arlecchino (Harlequin)", "Pantalone", "Brighella", "Arlecchino used physical comedy, acrobatic agility, and his slapstick bat to outwit masters and drive comic plots.", mcqIdx++));
  q.push(createNumber("In what year CE did Claudio Monteverdi premiere his milestone opera L'Orfeo at the Ducal Palace of Mantua?", 1607, "CE", "February 1607", "L'Orfeo was first performed on 24 February 1607 during carnival festivities in Mantua, establishing the foundation of classical opera."));

  // Cycle 3: Classical & Bel Canto Opera
  q.push(createMCQ("Which Mozart comic opera features the servant Figaro outwitting his aristocratic master Count Almaviva on his wedding day?", "The Marriage of Figaro", "Don Giovanni", "Cosi fan tutte", "Le Nozze di Figaro premiered in Vienna in 1786, setting Beaumarchais's politically subversive play with dazzling ensemble finales.", mcqIdx++));
  q.push(createMCQ("Which Italian vocal style meaning beautiful singing flourished in the early 19th century, characterized by smooth legato, agile coloratura, and vocal beauty?", "Bel Canto", "Verismo", "Sprechstimme", "Bel canto was perfected by Italian masters Rossini, Bellini, and Donizetti, prioritizing dazzling vocal technique and expressiveness.", mcqIdx++));
  q.push(createMCQ("Which Gaetano Donizetti tragic opera features one of the most famous and difficult coloratura mad scenes in operatic history, Il dolce suono?", "Lucia di Lammermoor", "L'elisir d'amore", "Don Pasquale", "Based on Walter Scott's Scottish novel, Lucia murders her forced husband on their wedding night and hallucinates marrying her true love Edgardo.", mcqIdx++));
  q.push(createMCQ("Which Vincenzo Bellini masterpiece features the famous soprano prayer aria Casta Diva addressed to the chaste goddess of the moon?", "Norma", "I Puritani", "La Sonnambula", "Norma is considered a supreme summit of the bel canto soprano repertoire, demanding extraordinary dramatic intensity and vocal stamina.", mcqIdx++));
  q.push(createMCQ("What was the historical term for male singers castrated before puberty to preserve their high soprano or alto vocal range with adult lung capacity?", "Castrati", "Countertenors", "Falsettos", "Castrati like Farinelli were the international rock stars of 18th-century Baroque opera, possessing astonishing breath control and vocal power.", mcqIdx++));
  q.push(createNumber("How many legendary Italian operas did Wolfgang Amadeus Mozart compose to libretti written by Lorenzo Da Ponte?", 3, "operas", "The 3 Da Ponte Operas", "Mozart and Da Ponte created three enduring operatic masterpieces: Le Nozze di Figaro (1786), Don Giovanni (1787), and Cosi fan tutte (1790)."));

  // Cycle 4: Giuseppe Verdi & Romantic Opera
  q.push(createMCQ("Which Italian opera titan composed the beloved masterworks Rigoletto, Il Trovatore, and La Traviata during his prolific middle period?", "Giuseppe Verdi", "Giacomo Puccini", "Amilcare Ponchielli", "Verdi transformed Italian opera into raw human drama, matching intense emotional depth with soaring melodies that defined the 19th century.", mcqIdx++));
  q.push(createMCQ("Which Verdi chorus from the 1842 opera Nabucco, sung by exiled Hebrew slaves, became an unofficial anthem for Italian unification (Risorgimento)?", "Va, pensiero", "Anvil Chorus", "Triumphal March", "Va, pensiero (Fly, thought, on wings of gold) resonated deeply with Italians longing for independence from Austrian Habsburg rule.", mcqIdx++));
  q.push(createMCQ("In Verdi's tragic masterpiece Rigoletto, which famous aria does the frivolous Duke of Mantua sing proclaiming that woman is fickle?", "La donna e mobile", "Nessun dorma", "Questa o quella", "La donna e mobile is one of the most recognized tenor melodies in the world, capturing the Duke's carefree and deceitful hedonism.", mcqIdx++));
  q.push(createMCQ("Which grandiose Verdi opera set in ancient Egypt features the famous Triumphal March with custom long Egyptian trumpets?", "Aida", "Don Carlo", "Otello", "Commissioned to celebrate the opening of the Khedivial Opera House in Cairo, Aida tells the tragic love story of an enslaved Ethiopian princess and Egyptian general Radames.", mcqIdx++));
  q.push(createMCQ("Which French courtesan character based on Alphonsine Plessis dies of tuberculosis in the arms of Alfredo in Verdi's La Traviata?", "Violetta Valery", "Gilda", "Desdemona", "La Traviata (The Fallen Woman), based on Alexandre Dumas fils's The Lady of the Camellias, was revolutionary for staging contemporary Parisian realism.", mcqIdx++));
  q.push(createNumber("How many days did Gioachino Rossini take to compose his comic operatic masterpiece The Barber of Seville in 1816?", 13, "days", "approx. 13 days", "Rossini wrote the complete score of The Barber of Seville in an astonishingly rapid 13 days, leading to its Rome premiere on 20 February 1816."));

  // Cycle 5: Dramatic Realism & Modern Theater
  q.push(createMCQ("Which Norwegian playwright is known as the Father of Modern Realism for groundbreaking social dramas like A Doll's House and Hedda Gabler?", "Henrik Ibsen", "August Strindberg", "Anton Chekhov", "Ibsen challenged Victorian bourgeois hypocrisy; Nora Helmer slamming the door as she leaves her patronizing husband shocked European society in 1879.", mcqIdx++));
  q.push(createMCQ("Which Russian dramatist and physician wrote masterpieces of subtle emotional subtext including The Seagull, Uncle Vanya, and The Cherry Orchard?", "Anton Chekhov", "Maxim Gorky", "Ivan Turgenev", "Chekhov pioneered mood-driven dramaturgy where profound internal psychological shifts occur beneath everyday domestic conversations.", mcqIdx++));
  q.push(createMCQ("Which Russian theater director co-founded the Moscow Art Theatre and developed the influential psychological acting system known as the Stanislavski Method?", "Konstantin Stanislavski", "Vsevolod Meyerhold", "Yevgeny Vakhtangov", "Stanislavski trained actors to achieve psychological realism and emotional truth through the magic if, objectives, and affective memory.", mcqIdx++));
  q.push(createMCQ("Which Swedish dramatist pioneered psychological naturalism with Miss Julie before venturing into expressionism with A Dream Play?", "August Strindberg", "Henrik Ibsen", "Bjornstjerne Bjornson", "Strindberg explored intense Darwinian battles between the sexes, classes, and subconscious minds in compact, high-tension chamber plays.", mcqIdx++));
  q.push(createMCQ("What dramatic theater term refers to the imaginary invisible barrier separating the performers onstage from the audience in the auditorium?", "The Fourth Wall", "The Proscenium Arch", "The Apron", "Realist theater emphasized maintaining the fourth wall, whereas modernist playwrights like Brecht intentionally broke it to engage the audience critically.", mcqIdx++));
  q.push(createNumber("How many major canonical full-length plays did Russian master Anton Chekhov write before his untimely death in 1904?", 4, "plays", "The 4 Great Plays", "Chekhov's quartet of undisputed theatrical masterpieces comprises The Seagull (1896), Uncle Vanya (1898), Three Sisters (1901), and The Cherry Orchard (1904)."));

  // Cycle 6: Broadway Musical Theater Pioneers
  q.push(createMCQ("Which landmark 1927 musical by Jerome Kern and Oscar Hammerstein II revolutionized Broadway by integrating songs seamlessly into serious social drama?", "Show Boat", "Oklahoma!", "Porgy and Bess", "Show Boat tackled racial miscegenation, addiction, and marital abandonment along the Mississippi River, featuring Paul Robeson's immortal Ol' Man River.", mcqIdx++));
  q.push(createMCQ("Which 1943 musical by Richard Rodgers and Oscar Hammerstein II opened with Oh, What a Beautiful Mornin', launching the Golden Age of Broadway?", "Oklahoma!", "Carousel", "The Sound of Music", "Oklahoma! pioneered the fully integrated book musical where songs, dialogue, and Agnes de Mille's dream ballet advanced character and plot.", mcqIdx++));
  q.push(createMCQ("Which 1957 Broadway musical with music by Leonard Bernstein and lyrics by Stephen Sondheim transposed Romeo and Juliet to rival New York street gangs?", "West Side Story", "Guys and Dolls", "Cabaret", "West Side Story featured explosive choreography by Jerome Robbins, capturing racial tensions between the white Jets and Puerto Rican Sharks in Manhattan.", mcqIdx++));
  q.push(createMCQ("Which celebrated American lyricist and composer created intellectually complex theatrical masterworks like Company, Sweeney Todd, and Into the Woods?", "Stephen Sondheim", "Cole Porter", "Irving Berlin", "Sondheim revolutionized modern musical theater through intricate polysyllabic rhymes, dark psychological themes, and sophisticated non-traditional song structures.", mcqIdx++));
  q.push(createMCQ("Which Lerner and Loewe musical adapted George Bernard Shaw's play Pygmalion, featuring Eliza Doolittle and Professor Henry Higgins?", "My Fair Lady", "Brigadoon", "Camelot", "My Fair Lady premiered on Broadway in 1956 starring Julie Andrews and Rex Harrison, featuring classic standards like I Could Have Danced All Night.", mcqIdx++));
  q.push(createNumber("What is the minimum seating capacity required for a Manhattan theater venue to be officially classified as a Broadway theatre?", 500, "seats", "500 or more seats", "The Broadway League defines Broadway theatres as professional venues in the Theater District of Manhattan containing 500 or more audience seats."));

  // Cycle 7: Puccini & Verismo Opera
  q.push(createMCQ("Which Giacomo Puccini opera set in the Latin Quarter of Paris portrays the tragic romance between the poet Rodolfo and the seamstress Mimi?", "La Boheme", "Tosca", "Madama Butterfly", "La Boheme captured youthful bohemian artistic life and romantic tragedy, later serving as the direct inspiration for Jonathan Larson's rock musical Rent.", mcqIdx++));
  q.push(createMCQ("Which thrilling Puccini melodrama features the fiery opera singer Floria Tosca, the painter Cavaradossi, and the corrupt police chief Baron Scarpia?", "Tosca", "Turandot", "Manon Lescaut", "Tosca is celebrated for intense psychological drama, featuring Tosca's anguished prayer Vissi d'arte and Cavaradossi's E lucevan le stelle.", mcqIdx++));
  q.push(createMCQ("Which iconic Puccini tenor aria from Turandot culminates with the soaring declaration Vincerò! (I will win!)?", "Nessun dorma", "Che gelida manina", "E lucevan le stelle", "Nessun dorma (None shall sleep) is sung by the unknown prince Calaf, famously popularized globally by Luciano Pavarotti during the 1990 World Cup.", mcqIdx++));
  q.push(createMCQ("Which 1875 French opera by Georges Bizet set in Seville features the famous Habanera and Seguidilla sung by a seductive cigarette factory worker?", "Carmen", "The Pearl Fishers", "Lakme", "Carmen's unapologetic free spirit and tragic murder by her jealous lover Don Jose scandalized its initial audiences before becoming a global triumph.", mcqIdx++));
  q.push(createMCQ("What Italian operatic movement of the late 19th century focused on raw, gritty, violent stories of working-class people rather than mythology or royalty?", "Verismo", "Bel Canto", "Opera Seria", "Verismo (realism) is epitomized by Mascagni's Cavalleria Rusticana, Leoncavallo's Pagliacci, and Puccini's dramatic masterworks.", mcqIdx++));
  q.push(createNumber("How many riddles must Prince Calaf correctly solve to win the hand of the icy Princess Turandot in Puccini's opera?", 3, "riddles", "The 3 Riddles", "Princess Turandot poses three riddles to prospective suitors: Hope, Blood, and Turandot herself; Calaf solves all three to save his life.", mcqIdx++));

  // Cycle 8: Epic Theater & The Absurd
  q.push(createMCQ("Which German Marxist dramatist developed Epic Theater and the Alienation Effect (Verfremdungseffekt) to encourage critical analysis over emotional immersion?", "Bertolt Brecht", "Heiner Muller", "Ernst Toller", "Brecht wrote Mother Courage and Her Children and The Threepenny Opera with Kurt Weill, intentionally reminding audiences they were watching a staged performance.", mcqIdx++));
  q.push(createMCQ("Which Irish absurdist masterpiece by Samuel Beckett features two tramps, Vladimir and Estragon, waiting endlessly by a leafless tree for someone who never arrives?", "Waiting for Godot", "Endgame", "Krapp's Last Tape", "Waiting for Godot stripped away conventional plot and psychological exposition, capturing existential human waiting, routine, and resilient camaraderie.", mcqIdx++));
  q.push(createMCQ("Which Romanian-French absurdist playwright depicted townspeople systematically transforming into aggressive beasts in his anti-totalitarian play Rhinoceros?", "Eugene Ionesco", "Jean Genet", "Arthur Adamov", "Ionesco used surreal comic grotesque situations to satirize mass conformity, herd mentality, and the rise of fascism in mid-20th-century Europe.", mcqIdx++));
  q.push(createMCQ("Which Nobel Prize-winning English playwright was famous for tense domestic power struggles punctuated by menacing dramatic pauses and silences?", "Harold Pinter", "Tom Stoppard", "David Hare", "Pinter's plays like The Homecoming and The Birthday Party coined the term Pinteresque pause for fraught silences loaded with unsaid threat.", mcqIdx++));
  q.push(createMCQ("Which Italian playwright explored subjective reality and role-playing in Six Characters in Search of an Author, winning the 1934 Nobel Prize in Literature?", "Luigi Pirandello", "Dario Fo", "Eduardo De Filippo", "Pirandello blurred the boundary between illusion and reality by having fictional dramatic characters disrupt an ongoing theatrical rehearsal.", mcqIdx++));
  q.push(createNumber("How many characters in Samuel Beckett's play Waiting for Godot ever meet or speak directly with Godot?", 0, "characters", "0 characters meet Godot", "Godot never appears onstage and is never met by any character throughout the entire two-act play, remaining an eternal absent figure."));

  // Cycle 9: Classical Ballet & Choreography
  q.push(createMCQ("Which French-born ballet master served as chief choreographer of the Russian Imperial Ballet, creating the iconic choreography for Swan Lake and The Nutcracker?", "Marius Petipa", "Arthur Saint-Leon", "Jules Perrot", "Petipa dominated Saint Petersburg ballet for five decades, codifying the Grand Pas de Deux and choreographing masterpieces with Tchaikovsky.", mcqIdx++));
  q.push(createMCQ("Which visionary Russian impresario founded the revolutionary Ballets Russes in Paris, uniting avant-garde composers, painters, and dancers?", "Sergei Diaghilev", "Michel Fokine", "Leonide Massine", "Diaghilev commissioned Stravinsky, Picasso, Matisse, and Coco Chanel, launching ballet into the cutting edge of 20th-century modern art.", mcqIdx++));
  q.push(createMCQ("Which legendary Polish-Russian dancer stunned audiences with his gravity-defying leaps and choreographed the scandalous 1913 premiere of The Rite of Spring?", "Vaslav Nijinsky", "Rudolf Nureyev", "Mikhail Baryshnikov", "Nijinsky rejected classical graceful ballet positions in favor of stomping, turned-in feet, and earthy primitive rituals for Stravinsky's pagan score.", mcqIdx++));
  q.push(createMCQ("Which Russian-American choreographer co-founded the New York City Ballet and pioneered neoclassical plotless ballet?", "George Balanchine", "Jerome Robbins", "Twyla Tharp", "Balanchine stripped away elaborate sets and narrative pantomime to focus purely on speed, musicality, and clean neoclassical line.", mcqIdx++));
  q.push(createMCQ("Which American modern dance pioneer developed the contraction and release technique, creating Appalachian Spring in 1944?", "Martha Graham", "Isadora Duncan", "Doris Humphrey", "Martha Graham rooted modern dance in the emotional breath and pelvic core, training generations of dancers across seven decades of performance.", mcqIdx++));
  q.push(createNumber("In what year CE did the legendary Parisian audience riot occur at the Theatre des Champs-Elysees during the premiere of The Rite of Spring?", 1913, "CE", "May 1913", "The Rite of Spring premiered on 29 May 1913 in Paris, where shouting and fistfights broke out between traditionalists and avant-garde supporters."));

  // Cycle 10: Modern Mega-Musicals & Theatrical Records
  q.push(createMCQ("Which English composer created record-breaking global mega-musicals including The Phantom of the Opera, Cats, Evita, and Jesus Christ Superstar?", "Andrew Lloyd Webber", "Claude-Michel Schonberg", "Stephen Schwartz", "Andrew Lloyd Webber is an EGOT winner whose lush, operatic pop scores defined international blockbuster musical theater for four decades.", mcqIdx++));
  q.push(createMCQ("Which revolutionary hip-hop and sung-through musical about founding father Alexander Hamilton was created by and starred Lin-Manuel Miranda in 2015?", "Hamilton", "In the Heights", "Dear Evan Hansen", "Hamilton won 11 Tony Awards and the Pulitzer Prize for Drama, casting Black and Latino performers as America's historical founding figures.", mcqIdx++));
  q.push(createMCQ("What French mega-musical based on Victor Hugo's novel, with music by Claude-Michel Schonberg, features the anthems I Dreamed a Dream and Do You Hear the People Sing?", "Les Miserables", "Miss Saigon", "The Hunchback of Notre Dame", "Les Miserables opened in London in 1985 and became the longest-running musical in West End history, performing continuously for nearly 40 years.", mcqIdx++));
  q.push(createMCQ("Which American theatrical awards, established by the American Theatre Wing in 1947, recognize excellence in Broadway theater productions?", "Tony Awards", "Olivier Awards", "Drama Desk Awards", "Officially named the Antoinette Perry Awards for Excellence in Broadway Theatre, the Tonys are Broadway's highest industry honors.", mcqIdx++));
  q.push(createMCQ("Which Disney theatrical stage adaptation directed by Julie Taymor utilizes innovative African animal puppetry, masks, and shadow play?", "The Lion King", "Aladdin", "Beauty and the Beast", "Julie Taymor became the first woman to win the Tony Award for Best Direction of a Musical for The Lion King, Broadway's highest-grossing production in history.", mcqIdx++));
  q.push(createNumber("How many total record-breaking Broadway performances did Andrew Lloyd Webber's The Phantom of the Opera play before closing in April 2023?", 13981, "performances", "13981 Broadway shows", "The Phantom of the Opera played 13,981 performances across 35 years at the Majestic Theatre, standing as the longest-running show in Broadway history."));

  return {
    id: "theater-opera-performing-arts-60",
    theme: "Theater, Opera & Dramatic Performing Arts",
    title: "Theater, Opera & Dramatic Performing Arts",
    description: "A 60-question grand master assessment exploring ancient Greek tragedy, Commedia dell'arte, Monteverdi, Mozart, Verdi, Ibsen, Stanislavski, Broadway golden age musicals, Puccini verismo, Beckett absurdism, Ballets Russes, and modern blockbuster theater.",
    category: "Arts, Music, Literature & Philosophy",
    difficulty: "moderate",
    createdAt: "2026-08-27T00:00:00Z",
    questions: q
  };
}

// -------------------------------------------------------------
// QUIZ 10: world-religions-sacred-traditions-60
// -------------------------------------------------------------
function getWorldReligionsQuiz() {
  let mcqIdx = 0;
  const q = [];

  // Cycle 1: Hinduism: Sacred Texts & Moksha
  q.push(createMCQ("Which ancient collection of four sacred Sanskrit texts (Rigveda, Samaveda, Yajurveda, and Atharvaveda) forms the foundational scripture of Hinduism?", "The Vedas", "The Puranas", "The Agamas", "The Vedas are considered Shruti (that which is heard/revealed directly by cosmic seers), dating from the 2nd millennium BCE.", mcqIdx++));
  q.push(createMCQ("In Hindu philosophy, what Sanskrit term refers to the eternal cycle of birth, death, and rebirth driven by karma?", "Samsara", "Moksha", "Dharma", "Samsara is the transmigration of the eternal soul (Atman) across successive lifetimes until spiritual liberation is attained.", mcqIdx++));
  q.push(createMCQ("What is the ultimate spiritual goal in Hinduism, describing liberation from the cycle of rebirth and union of the individual soul (Atman) with Brahman?", "Moksha", "Nirvana", "Kaivalya", "Moksha represents the supreme realization of the illusion of separation (Maya) and absolute spiritual freedom.", mcqIdx++));
  q.push(createMCQ("Which philosophical spiritual dialogue within the Mahabharata features Prince Arjuna and Lord Krishna discussing duty and devotion before battle?", "Bhagavad Gita", "Upanishads", "Yoga Sutras", "The 700-verse Bhagavad Gita outlines the paths of Karma Yoga (action), Jnana Yoga (knowledge), and Bhakti Yoga (devotion).", mcqIdx++));
  q.push(createMCQ("Which ancient Hindu philosophical texts, forming the conclusion of the Vedas (Vedanta), explore the non-dual nature of Brahman and the inner Self?", "The Upanishads", "The Brahmanas", "The Aranyakas", "The Upanishads introduced profound philosophical maxims like Tat Tvam Asi (That Thou Art), teaching that individual and universal consciousness are one.", mcqIdx++));
  q.push(createNumber("How many primary canonical Vedas make up the core Vedic sacred literature in Hinduism?", 4, "Vedas", "The 4 Vedas", "The canonical Vedic corpus comprises four texts: the Rigveda, Samaveda, Yajurveda, and Atharvaveda."));

  // Cycle 2: Buddhism: The Middle Path & Enlightenment
  q.push(createMCQ("Under which sacred tree in Bodh Gaya did Prince Siddhartha Gautama meditate and attain supreme spiritual enlightenment as the Buddha?", "Bodhi Tree", "Banyan Tree", "Lotus Tree", "Siddhartha sat under the Ficus religiosa (Bodhi Tree) vowing not to rise until he uncovered the root cause of human suffering.", mcqIdx++));
  q.push(createMCQ("What foundational Buddhist teaching identifies the truth of suffering (Dukkha), its origin (Samudaya), its cessation (Nirodha), and the path to its end (Magga)?", "The Four Noble Truths", "The Three Jewels", "The Twelve Links", "The Buddha delivered his first sermon on the Four Noble Truths in the Deer Park at Sarnath to his five ascetic companions.", mcqIdx++));
  q.push(createMCQ("Which major branch of Buddhism, meaning Great Vehicle, emphasizes the ideal of the Bodhisattva who delays nirvana to save all sentient beings?", "Mahayana", "Theravada", "Vajrayana", "Mahayana Buddhism spread widely across China, Japan, Korea, and Vietnam, promoting universal compassion and Buddha-nature.", mcqIdx++));
  q.push(createMCQ("What is the ultimate state of spiritual liberation in Buddhism, representing the complete extinguishing of greed, hatred, and delusion?", "Nirvana", "Samsara", "Bhavana", "Nirvana translates literally to blowing out or quenching the fires of craving, liberating consciousness from future rebirth.", mcqIdx++));
  q.push(createMCQ("Which Japanese Buddhist school emphasizes seated meditation (Zazen) and paradoxical riddles (Koans) to awaken sudden intuitive insight?", "Zen Buddhism", "Pure Land Buddhism", "Nichiren Buddhism", "Originating from Chinese Chan Buddhism, Zen strips away elaborate ritualism to focus directly on mindful presence and insight into one's true nature.", mcqIdx++));
  q.push(createNumber("How many steps comprise the Noble Eightfold Path taught by the Buddha to achieve liberation from suffering?", 8, "steps", "The Eightfold Path", "The Eightfold Path divides into Right View, Intention, Speech, Action, Livelihood, Effort, Mindfulness, and Concentration."));

  // Cycle 3: Judaism: Torah, Covenant & Heritage
  q.push(createMCQ("What foundational Hebrew scripture comprises the first five books of the Bible (Genesis, Exodus, Leviticus, Numbers, Deuteronomy)?", "The Torah", "The Nevi'im", "The Ketuvim", "Also known as the Pentateuch or Five Books of Moses, the Torah is handwritten on parchment scrolls and read weekly in synagogue liturgy.", mcqIdx++));
  q.push(createMCQ("At which sacred mountain in the desert did Moses receive the Ten Commandments and the divine covenant from God?", "Mount Sinai", "Mount Carmel", "Mount Zion", "The revelation at Mount Sinai forms the core covenantal moment in Jewish history, celebrated annually on the holiday of Shavuot.", mcqIdx++));
  q.push(createMCQ("What comprehensive multi-volume compendium of rabbinic law, ethics, and commentary consists of the Mishnah and the Gemara?", "The Talmud", "The Midrash", "The Zohar", "Compiled between the 3rd and 6th centuries CE in Jerusalem and Babylonia, the Talmud records centuries of vigorous dialectical rabbinic debate.", mcqIdx++));
  q.push(createMCQ("What is the holiest day of the year in Judaism, observed as the Day of Atonement through 25 hours of fasting and intensive prayer?", "Yom Kippur", "Rosh Hashanah", "Passover", "Yom Kippur concludes the Ten Days of Repentance (Yamim Noraim) that begin on Rosh Hashanah, seeking forgiveness for sins.", mcqIdx++));
  q.push(createMCQ("What weekly 25-hour Jewish Sabbath begins at Friday sunset with candle lighting and concludes Saturday evening with the Havdalah ceremony?", "Shabbat", "Sukkot", "Purim", "Shabbat commemorates God's rest on the seventh day of creation and liberation from Egyptian slavery, observed with festive family meals and rest from labor.", mcqIdx++));
  q.push(createNumber("How many total Mitzvot (commandments) are enumerated in the Torah according to the classical rabbinic count codified by Maimonides?", 613, "commandments", "613 Mitzvot", "Rabbinic tradition enumerates exactly 613 commandments in the Torah: 248 positive commandments and 365 negative prohibitions."));

  // Cycle 4: Christianity: Gospels & Early Church
  q.push(createMCQ("Which four books opening the Christian New Testament provide the canonical biographical accounts of the life, ministry, death, and resurrection of Jesus?", "Matthew, Mark, Luke, and John", "Acts, Romans, Corinthians, and Galatians", "Genesis, Exodus, Leviticus, and Deuteronomy", "The Gospels (Good News) comprise three Synoptic Gospels (Matthew, Mark, Luke) sharing similar narrative structures and the theological Gospel of John.", mcqIdx++));
  q.push(createMCQ("Which Jewish-Roman citizen, formerly Saul of Tarsus, experienced a dramatic vision on the road to Damascus and became the apostle to the Gentiles?", "Paul the Apostle", "Peter the Apostle", "James the Just", "Paul wrote numerous foundational theological epistles to early Christian communities in Rome, Corinth, Galatia, and Ephesus.", mcqIdx++));
  q.push(createMCQ("Which landmark ecumenical council convened by Emperor Constantine in 325 CE formulated the Nicene Creed confirming the divine nature of Christ?", "Council of Nicaea", "Council of Chalcedon", "Council of Trent", "The Council of Nicaea affirmed that Jesus Christ is consubstantial (homoousios) with the Father, rejecting the Arian heresy.", mcqIdx++));
  q.push(createMCQ("What is the central Christian theological doctrine affirming that God is one divine being existing eternally in three co-equal persons: Father, Son, and Holy Spirit?", "The Holy Trinity", "Monotheletism", "Docetism", "Trinitarian theology forms the foundational doctrinal cornerstone across Eastern Orthodox, Roman Catholic, and mainstream Protestant traditions.", mcqIdx++));
  q.push(createMCQ("What principal Christian sacrament instituted at the Last Supper involves the ritual blessing and sharing of bread and wine?", "Eucharist / Holy Communion", "Baptism", "Confirmation", "Also known as the Divine Liturgy or Mass, the Eucharist commemorates Christ's sacrificial death and spiritual presence with the faithful.", mcqIdx++));
  q.push(createNumber("How many chosen apostles made up the original inner circle of disciples appointed by Jesus during his ministry?", 12, "apostles", "The Twelve Apostles", "Jesus chose twelve primary apostles corresponding symbolically to the twelve historical tribes of Israel, including Peter, James, and John."));

  // Cycle 5: Islam: The Quran & Five Pillars
  q.push(createMCQ("Who is revered in Islam as the Seal of the Prophets, receiving the divine revelations of the Quran from the Angel Gabriel starting in 610 CE?", "Prophet Muhammad", "Prophet Ibrahim", "Prophet Musa", "Muhammad received revelations over a 23-year period in Mecca and Medina, uniting the Arabian peninsula under Islamic monotheism (Tawhid).", mcqIdx++));
  q.push(createMCQ("What is the sacred scripture of Islam, considered the literal verbatim word of Allah revealed in classical Arabic?", "The Quran", "The Hadith", "The Sunnah", "Composed of 114 chapters (surahs) organized roughly from longest to shortest, the Quran provides moral, spiritual, and legal guidance for Muslims worldwide.", mcqIdx++));
  q.push(createMCQ("What is the first and foundational Pillar of Islam, proclaiming that there is no god but Allah and Muhammad is His messenger?", "Shahada", "Salah", "Zakat", "Reciting the Shahada with sincere conviction before witnesses constitutes the formal entry into the global Islamic community (Ummah).", mcqIdx++));
  q.push(createMCQ("Toward which ancient cubical stone shrine in the courtyard of Masjid al-Haram in Mecca do Muslims orient their daily prayers (Qibla)?", "The Kaaba", "Dome of the Rock", "Al-Masjid an-Nabawi", "Islamic tradition holds that the Kaaba was originally constructed by the prophet Ibrahim (Abraham) and his son Ismail as the first house of monotheistic worship.", mcqIdx++));
  q.push(createMCQ("During which sacred ninth month of the Islamic lunar calendar do Muslims observe daily fasting (Sawm) from dawn until sunset?", "Ramadan", "Muharram", "Shawwal", "Ramadan commemorates the month in which the first verses of the Quran were revealed on the Night of Power (Laylat al-Qadr).", mcqIdx++));
  q.push(createNumber("How many mandatory Pillars of Islam form the fundamental obligatory religious practices of Islamic faith?", 5, "pillars", "The Five Pillars of Islam", "The Five Pillars comprise Shahada (faith), Salah (prayer 5 times daily), Zakat (almsgiving), Sawm (fasting during Ramadan), and Hajj (pilgrimage to Mecca)."));

  // Cycle 6: Daoism & Confucianism
  q.push(createMCQ("Which ancient Chinese philosophical text attributed to sage Laozi opens with the famous line: The Dao that can be told is not the eternal Dao?", "Dao De Jing", "Zhuangzi", "Yijing", "The Dao De Jing (Classic of the Way and Its Virtue) consists of 81 short poetic chapters exploring non-action, water-like flexibility, and cosmic balance.", mcqIdx++));
  q.push(createMCQ("What central Daoist concept translates to effortless action or natural non-striving, acting in spontaneous alignment with the natural flow?", "Wu Wei", "Ren", "Xiao", "Wu Wei teaches that true effectiveness is achieved without aggressive force, comparable to water smoothly carving through solid stone.", mcqIdx++));
  q.push(createMCQ("What core virtue in Confucianism represents benevolence, human-heartedness, and compassionate love for one's fellow human beings?", "Ren", "Li", "Yi", "Ren is the highest moral virtue in Confucian thought, cultivated through empathy, respectful etiquette (Li), and moral self-cultivation.", mcqIdx++));
  q.push(createMCQ("What Confucian foundational principle demands deep respect, obedience, and devotion of children toward their parents and ancestral lineage?", "Filial Piety (Xiao)", "Wu Wei", "Tian", "Filial piety was viewed by Confucius as the root of all moral character and the bedrock of societal harmony and good governance.", mcqIdx++));
  q.push(createMCQ("Which ancient Chinese text of divination and cosmological wisdom uses 64 symbolic hexagrams of broken and solid lines to interpret change?", "Yijing (I Ching)", "Shujing", "Liji", "The Yijing (Book of Changes) is one of the Five Classics, profoundly shaping both Daoist metaphysics and Confucian philosophical commentary.", mcqIdx++));
  q.push(createNumber("How many poetic chapters make up the classical Chinese text Dao De Jing attributed to Laozi?", 81, "chapters", "81 poetic chapters", "The traditional received text of the Dao De Jing is organized into exactly 81 short chapters, divided into two parts: Dao (1-37) and De (38-81)."));

  // Cycle 7: Sikhism: The Gurus & Golden Temple
  q.push(createMCQ("Which 15th-century spiritual master founded Sikhism in the Punjab region, proclaiming: There is no Hindu, there is no Muslim?", "Guru Nanak", "Guru Angad", "Guru Gobind Singh", "Guru Nanak emphasized Ek Onkar (One Supreme Reality), the equality of all human beings regardless of caste or gender, and honest living.", mcqIdx++));
  q.push(createMCQ("What is the central holy scripture of Sikhism, installed as the eternal, living spiritual Guru for all Sikhs by Guru Gobind Singh in 1708?", "Guru Granth Sahib", "Dasam Granth", "Japji Sahib", "The Guru Granth Sahib contains 1,430 pages of devotional poetry composed in musical ragas by Sikh Gurus and Hindu and Muslim saints.", mcqIdx++));
  q.push(createMCQ("What magnificent gilded Sikh gurdwara in Amritsar, Punjab, features doors on all four sides symbolizing welcoming people of every caste and creed?", "Harmandir Sahib (The Golden Temple)", "Takht Sri Patna Sahib", "Hazur Sahib", "Harmandir Sahib sits in the center of the sacred Amrit Sarovar (Pool of Nectar), feeding tens of thousands of pilgrims free daily meals.", mcqIdx++));
  q.push(createMCQ("What is the free community kitchen in every Sikh gurdwara where all visitors sit together on the floor to eat a shared vegetarian meal?", "Langar", "Kirtan", "Seva", "Instituted by Guru Nanak, Langar directly dismantled the discriminatory Hindu caste system by requiring all individuals to eat side by side.", mcqIdx++));
  q.push(createMCQ("Which of the Five Ks (panj kakar) worn by initiated Khalsa Sikhs is the sacred steel bangle symbolizing restraint and unbreakable attachment to God?", "Kara", "Kesh", "Kirpan", "The Five Ks comprise Kesh (uncut hair), Kangha (wooden comb), Kara (iron bracelet), Kachera (cotton undergarment), and Kirpan (curved ceremonial dagger).", mcqIdx++));
  q.push(createNumber("How many human spiritual Gurus guided the Sikh community between Guru Nanak and the final human Guru, Guru Gobind Singh?", 10, "Gurus", "The 10 Human Gurus", "Sikhism was shaped by exactly ten human Gurus between 1469 and 1708, after which spiritual authority was vested eternally in the Guru Granth Sahib."));

  // Cycle 8: Sacred Architecture Across the Globe
  q.push(createMCQ("Which colossal 12th-century temple complex in Cambodia was originally built as a Hindu dedication to Vishnu before transforming into a Buddhist shrine?", "Angkor Wat", "Bayon", "Ta Prohm", "Built under King Suryavarman II, Angkor Wat is the largest religious monument in the world, renowned for bas-reliefs and lotus towers.", mcqIdx++));
  q.push(createMCQ("What 9th-century monumental Mahayana Buddhist temple in Central Java, Indonesia, is built as a colossal three-dimensional cosmic mandala with 72 stupas?", "Borobudur", "Prambanan", "Mendut", "Borobudur features nine stacked platforms representing the path from the world of desire (Kamadhatu) to the world of formlessness (Arupadhatu).", mcqIdx++));
  q.push(createMCQ("What is the most sacred site in Judaism where Jews pray in the Old City of Jerusalem, the lone remaining retaining wall of the Second Temple?", "The Western Wall", "The Golden Gate", "Mount of Olives", "Also known as the Kotel, the Western Wall stood outside the Temple Mount complex expanded by King Herod the Great in the 1st century BCE.", mcqIdx++));
  q.push(createMCQ("Which Renaissance basilica in Vatican City, standing over the traditional tomb of Saint Peter, features Michelangelo's monumental dome?", "St. Peter's Basilica", "St. John Lateran", "Santa Maria Maggiore", "St. Peter's Basilica is the largest Christian church building in the world by interior volume, with a capacity of over 60,000 worshippers.", mcqIdx++));
  q.push(createMCQ("What sacred Shinto shrine in Mie Prefecture, dedicated to the sun goddess Amaterasu, is ritually dismantled and rebuilt every 20 years?", "Ise Grand Shrine", "Fushimi Inari-taisha", "Itsukushima Shrine", "The ritual rebuilding (Shikinen Sengu) has been practiced for over 1,300 years, preserving ancient timber joinery crafts and Shinto renewal philosophy.", mcqIdx++));
  q.push(createNumber("How many openwork perforated bell-shaped stupas containing Buddha statues surround the upper circular platforms of Borobudur?", 72, "stupas", "72 perforated stupas", "Borobudur's three upper circular terraces host exactly 72 perforated stupas, each housing a seated Buddha statue, surrounding the large central stupa."));

  // Cycle 9: Zoroastrianism, Shinto & Jainism
  q.push(createMCQ("Which ancient Iranian monotheistic religion founded by prophet Zarathustra worships Ahura Mazda as the Lord of Wisdom and battles Angra Mainyu?", "Zoroastrianism", "Manichaeism", "Mithraism", "Zoroastrianism was the state religion of the ancient Persian Achaemenid, Parthian, and Sasanian Empires, viewing fire as a symbol of divine purity.", mcqIdx++));
  q.push(createMCQ("In Japanese Shinto, what are the sacred spirits, divine powers, and spiritual essences inhabiting natural phenomena such as trees, waterfalls, and ancestors called?", "Kami", "Yokai", "Oni", "Shinto teaches that humans live in sacred harmony with myriad Kami (yaoyorozu no kami) that animate the natural universe.", mcqIdx++));
  q.push(createMCQ("What distinctive red-orange wooden gateway marks the physical boundary between the profane everyday world and sacred Shinto shrine grounds?", "Torii gate", "Pagoda", "Chorten", "Passing under a Torii gate purifies visitors as they enter the sacred precinct of the kami, famously showcased at Fushimi Inari with thousands of vermilion torii.", mcqIdx++));
  q.push(createMCQ("What supreme ethical principle of radical non-violence toward all living beings is the foundational core of Jain spiritual practice?", "Ahimsa", "Satya", "Asteya", "Jain monks practice strict vegetarianism and sweep the ground before them with small brooms to avoid accidentally harming microscopic insects.", mcqIdx++));
  q.push(createMCQ("Which 6th-century BCE religious reformer and 24th Tirthankara of Jainism revitalized the path of asceticism and spiritual liberation?", "Mahavira", "Parshvanatha", "Rishabhanatha", "Vardhamana Mahavira attained Kevala Jnana (omniscience) after twelve years of severe meditation, codifying Jain monastic vows.", mcqIdx++));
  q.push(createNumber("How many enlightened spiritual conquerors (Tirthankaras or Ford-makers) are recognized in the cyclical timeline of Jain tradition?", 24, "Tirthankaras", "The 24 Tirthankaras", "Jainism honors 24 Tirthankaras in the current cosmic half-cycle, beginning with Lord Rishabhanatha and concluding with Mahavira."));

  // Cycle 10: Sacred Festivals & Pilgrimages
  q.push(createMCQ("What annual mandatory Islamic pilgrimage to the holy city of Mecca must be performed at least once in a lifetime by every physically and financially able Muslim?", "Hajj", "Umrah", "Ziyarat", "During Hajj, millions of pilgrims wear uniform white garments (Ihram) to perform rituals including circumambulating the Kaaba and standing at Mount Arafat.", mcqIdx++));
  q.push(createMCQ("What colossal Hindu festival and pilgrimage, the largest human peaceful gathering on Earth, involves ritual bathing at the confluence of sacred rivers?", "Kumbh Mela", "Diwali", "Holi", "Held at Prayagraj, Haridwar, Ujjain, and Nashik, the Kumbh Mela draws tens of millions of pilgrims to bathe at the Triveni Sangam to cleanse sins.", mcqIdx++));
  q.push(createMCQ("Which autumn Hindu Festival of Lights celebrates the victory of light over darkness and the return of Lord Rama to Ayodhya?", "Diwali (Deepavali)", "Holi", "Navratri", "Celebrated by lighting clay oil lamps (diyas), bursting fireworks, and sharing sweets, Diwali also honors Lakshmi, the goddess of prosperity.", mcqIdx++));
  q.push(createMCQ("Which Jewish springtime festival commemorates the liberation of the Israelites from slavery in ancient Egypt with a ceremonial Seder meal?", "Passover (Pesach)", "Sukkot", "Shavuot", "During the Seder meal, families read the Haggadah, drink four cups of wine, and eat unleavened bread (matzah) to remember the Exodus.", mcqIdx++));
  q.push(createMCQ("What supreme Christian feast celebrates the resurrection of Jesus Christ from the dead on the third day after his crucifixion at Calvary?", "Easter (Pascha)", "Christmas", "Pentecost", "Easter marks the culmination of Holy Week and Lent, celebrated with sunrise vigils and joyful declarations of Christ is Risen!", mcqIdx++));
  q.push(createNumber("Every how many years does the primary cycle of the grand Purna Kumbh Mela pilgrimage recur at each sacred Indian river location?", 12, "years", "12-year primary cycle", "The major Purna Kumbh Mela rotates every 12 years across four holy river sites based on astrological positions of Jupiter, the Sun, and the Moon."));

  return {
    id: "world-religions-sacred-traditions-60",
    theme: "Sacred History: World Religions, Architecture & Lore",
    title: "Sacred History: World Religions, Architecture & Lore",
    description: "A 60-question comprehensive journey exploring Hinduism, the Vedas, the Buddha's Noble Eightfold Path, Judaism and the Torah, Christian gospels and councils, Islam and the Five Pillars, Daoist harmony, Sikh Gurus, sacred architecture, and global pilgrimages.",
    category: "Arts, Music, Literature & Philosophy",
    difficulty: "moderate",
    createdAt: "2026-08-27T00:00:00Z",
    questions: q
  };
}

// -------------------------------------------------------------
// QUIZ 11: olympic-games-records-history-60
// -------------------------------------------------------------
function getOlympicGamesQuiz() {
  let mcqIdx = 0;
  const q = [];

  // Cycle 1: Ancient Olympic Origins
  q.push(createMCQ("In which sacred sanctuary in the western Peloponnese of ancient Greece were the Ancient Olympic Games held in honor of Zeus?", "Olympia", "Delphi", "Nemea", "The ancient sanctuary of Olympia hosted the pan-Hellenic games, featuring the monumental Temple of Zeus and Phidias's ivory and gold statue.", mcqIdx++));
  q.push(createMCQ("What sacred reward was bestowed upon victorious athletes at the Ancient Olympic Games, crafted from branches of a sacred wild olive tree?", "Kotinos (Olive wreath)", "Gold medallion", "Bronze tripod", "Victors received a simple wreath of olive leaves (kotinos) cut with a golden sickle from the sacred tree near the Temple of Zeus, earning immense glory.", mcqIdx++));
  q.push(createMCQ("What ancient brutal Olympic combat sport combined elements of boxing, wrestling, and kicking with virtually no rules except against biting and eye-gouging?", "Pankration", "Pygmachia", "Pale", "Pankration (all powers) was one of the most popular and violent events in antiquity, ending only upon submission or knockout.", mcqIdx++));
  q.push(createMCQ("What was the traditional Greek sacred truce declared before the Ancient Olympics to guarantee safe passage for athletes and spectators across warring states?", "Ekecheiria", "Hoplitodromos", "Stadion", "The Olympic Truce (Ekecheiria) suspended armed conflicts across Greek city-states during the month preceding and following the games.", mcqIdx++));
  q.push(createMCQ("What was the original and sole athletic event contested at the earliest recorded Ancient Olympic Games, a straight footrace of about 192 meters?", "Stadion footrace", "Diaulos", "Dolichos", "The Stadion sprint measured the length of the Olympic stadium, won by cook Coroebus of Elis at the inaugural 776 BCE games.", mcqIdx++));
  q.push(createNumber("In what traditional inaugural year BCE were the first recorded Ancient Olympic Games held in Olympia, Greece?", 776, "BCE", "776 BCE inaugural games", "Classical tradition and Olympic chronologies date the first official recorded Olympic Games back to 776 BCE."));

  // Cycle 2: Rebirth of Modern Olympics
  q.push(createMCQ("Which French aristocrat and educator is recognized as the Father of the Modern Olympic Games, founding the International Olympic Committee in 1894?", "Pierre de Coubertin", "Dimitrios Vikelas", "Henri de Baillet-Latour", "Baron Pierre de Coubertin campaigned to revive the Olympic Games to promote international goodwill, physical education, and athletic excellence.", mcqIdx++));
  q.push(createMCQ("In which historic city were the first modern Olympic Games staged in April 1896 in the reconstructed marble Panathenaic Stadium?", "Athens", "Paris", "London", "The 1896 Athens Games featured 241 male athletes representing 14 nations competing across 43 events.", mcqIdx++));
  q.push(createMCQ("Which Greek water carrier became a national hero by winning the first modern Olympic marathon from the plains of Marathon to Athens in 1896?", "Spyridon Louis", "Charilaos Vasilakos", "Ioannis Mitropoulos", "Spyridon Louis completed the 40-kilometer distance in 2 hours, 58 minutes, and 50 seconds before an ecstatic crowd of 80,000 spectators.", mcqIdx++));
  q.push(createMCQ("What is the traditional Latin motto of the Olympic Games, coined by Dominican priest Henri Didon, meaning Faster, Higher, Stronger?", "Citius, Altius, Fortius", "Veni, Vidi, Vici", "In Hoc Signo Vinces", "In 2021, the International Olympic Committee officially updated the motto to Citius, Altius, Fortius - Communiter (Faster, Higher, Stronger - Together).", mcqIdx++));
  q.push(createMCQ("What do the five interlocking colored rings on the official Olympic flag represent, designed by Pierre de Coubertin in 1913?", "The five inhabited continents of the world", "The five original ancient sports", "The five founding nations", "The blue, yellow, black, green, and red rings on a white background represent Africa, the Americas, Asia, Europe, and Oceania united in sport.", mcqIdx++));
  q.push(createNumber("In what year CE were the first modern Olympic Games officially inaugurated in Athens, Greece?", 1896, "CE", "April 1896", "King George I of Greece officially opened the first modern Olympic Games on 6 April 1896 at the Panathenaic Stadium.", mcqIdx));

  // Cycle 3: Track & Field Immortals
  q.push(createMCQ("Which African American track star shattered Adolf Hitler's Nazi Aryan supremacy propaganda by winning four gold medals at the 1936 Berlin Olympics?", "Jesse Owens", "Ralph Metcalfe", "Cornelius Johnson", "Jesse Owens won golds in the 100m, 200m, long jump, and 4x100m relay, receiving standing ovations from the German public.", mcqIdx++));
  q.push(createMCQ("Which Jamaican sprinting sensation completed the historic Olympic triple-triple, winning 100m and 200m gold medals across Beijing 2008, London 2012, and Rio 2016?", "Usain Bolt", "Yohan Blake", "Asafa Powell", "Usain Bolt established world records of 9.58 seconds in the 100m and 19.19 seconds in the 200m, becoming the fastest human ever timed.", mcqIdx++));
  q.push(createMCQ("Which American track and field legend won nine Olympic gold medals across four games, including four consecutive long jump titles between 1984 and 1996?", "Carl Lewis", "Al Oerter", "Michael Johnson", "Carl Lewis matched Jesse Owens's four golds in a single games at Los Angeles 1984 and dominated the long jump pit for over a decade.", mcqIdx++));
  q.push(createMCQ("Which American long jumper produced a leap of 8.90 meters at the 1968 Mexico City Olympics, shattering the existing world record by 55 centimeters?", "Bob Beamon", "Ralph Boston", "Lynn Davies", "Beamon's legendary jump remained the world record for nearly 23 years and still stands as the longest-standing Olympic track and field record.", mcqIdx++));
  q.push(createMCQ("Which American sprinter won both the 200m and 400m Olympic titles at Atlanta 1996 wearing his famous golden running spikes?", "Michael Johnson", "Maurice Greene", "Jeremy Wariner", "Michael Johnson set a blistering world record of 19.32 seconds in the 200 meters, completing an unprecedented 200m-400m Olympic double.", mcqIdx++));
  q.push(createNumber("What is Usain Bolt's official 100-meter sprinting world record time in seconds, set at the 2009 World Championships?", 9.58, "seconds", "9.58s world record", "Usain Bolt ran the 100 meters in an astonishing 9.58 seconds in Berlin in August 2009, clocking a peak speed of 44.72 km/h."));

  // Cycle 4: Swimming Legends & Aquatics
  q.push(createMCQ("Which American swimmer became the most decorated Olympian of all time, amassing an astonishing 28 total Olympic medals, including 23 gold medals?", "Michael Phelps", "Ryan Lochte", "Caeleb Dressel", "Michael Phelps competed across five Olympic Games from 2000 to 2016, breaking individual records that had stood since ancient Rhodes athlete Leonidas.", mcqIdx++));
  q.push(createMCQ("Which American swimming icon won seven gold medals and set seven world records in a single Olympic Games at Munich 1972?", "Mark Spitz", "Matt Biondi", "Don Schollander", "Spitz's mustache and seven-gold haul stood as the ultimate single-games Olympic benchmark for 36 years until Michael Phelps won eight in Beijing 2008.", mcqIdx++));
  q.push(createMCQ("Which dominant American distance swimmer won nine Olympic gold medals between London 2012 and Paris 2024, dominating the 800m and 1500m freestyle?", "Katie Ledecky", "Jenny Thompson", "Dana Vollmer", "Katie Ledecky became the most decorated American female Olympian in history, remaining undefeated in the Olympic 800m freestyle for four consecutive games.", mcqIdx++));
  q.push(createMCQ("Which Australian swimming prodigy nicknamed The Thorpedo won five Olympic gold medals across Sydney 2000 and Athens 2004?", "Ian Thorpe", "Grant Hackett", "Michael Klim", "Ian Thorpe dominated world middle-distance freestyle in custom full-body black swimming suits before home crowds in Sydney.", mcqIdx++));
  q.push(createMCQ("Which French swimming phenom captured four individual gold medals and set four Olympic records at the Paris 2024 Games under coach Bob Bowman?", "Leon Marchand", "Florent Manaudou", "Alain Bernard", "Leon Marchand completed an unprecedented double on the same evening, winning both the 200m butterfly and 200m breaststroke golds.", mcqIdx++));
  q.push(createNumber("How many total career Olympic gold medals did American swimmer Michael Phelps win between 2004 and 2016?", 23, "gold medals", "23 gold medals", "Michael Phelps won 23 gold medals (plus 3 silver and 2 bronze) for a grand total of 28 Olympic medals, the most in history."));

  // Cycle 5: Gymnastics Royalty & Perfect Scores
  q.push(createMCQ("Which 14-year-old Romanian gymnast made history at the 1976 Montreal Olympics by scoring the first-ever perfect 10.0 in modern Olympic gymnastics?", "Nadia Comaneci", "Nellie Kim", "Olga Korbut", "The scoreboard could only display three digits and showed 1.00 because manufacturers believed a perfect 10.00 was impossible to attain.", mcqIdx++));
  q.push(createMCQ("Which American gymnastics icon, the most decorated gymnast in history, has five eponymous skills named after her in the Code of Points?", "Simone Biles", "Gabby Douglas", "Aly Raisman", "Simone Biles has won 11 Olympic medals across Rio 2016, Tokyo 2020, and Paris 2024, executing superhuman tumbling passes and Yurchenko double pikes.", mcqIdx++));
  q.push(createMCQ("Which Soviet gymnast held the record for the most total Olympic medals by any athlete (18 medals) for 48 years until surpassed by Michael Phelps in 2012?", "Larisa Latynina", "Polina Astakhova", "Ludmilla Tourischeva", "Latynina won nine gold, five silver, and four bronze medals across Melbourne 1956, Rome 1960, and Tokyo 1964.", mcqIdx++));
  q.push(createMCQ("Which charismatic Soviet gymnast captivated the world at Munich 1972 with her daring Korbut Flip on the balance beam and uneven bars?", "Olga Korbut", "Nadia Comaneci", "Elena Mukhina", "Olga Korbut's emotional charm and revolutionary aerial acrobatics catalyzed a massive global explosion in women's artistic gymnastics popularity.", mcqIdx++));
  q.push(createMCQ("Which Japanese men's gymnast nicknamed King Kohei won back-to-back Olympic all-around gold medals in London 2012 and Rio 2016?", "Kohei Uchimura", "Sawao Kato", "Kenzo Shirai", "Kohei Uchimura is widely considered the greatest male gymnast in history, winning six consecutive world all-around titles alongside his Olympic golds.", mcqIdx++));
  q.push(createNumber("What historic score did Nadia Comaneci achieve on the uneven bars at Montreal 1976, marking the first perfect score in Olympic history?", 10, "score", "A Perfect 10.0", "Nadia Comaneci received the first perfect 10.0 score in Olympic gymnastics history on 18 July 1976, earning seven perfect tens across the games."));

  // Cycle 6: Winter Olympic Milestones
  q.push(createMCQ("In which French Alpine resort town were the inaugural Winter Olympic Games held in 1924?", "Chamonix", "Grenoble", "Albertville", "The 1924 International Winter Sports Week in Chamonix was retroactively designated by the IOC as the first Olympic Winter Games.", mcqIdx++));
  q.push(createMCQ("What historic 1980 Lake Placid ice hockey match saw a team of US college players upset the four-time defending champion Soviet national team?", "Miracle on Ice", "The Ice Bowl", "Summit Series", "Coached by Herb Brooks, the underdog United States team defeated the powerhouse Soviet Union 4-3 before capturing the gold medal against Finland.", mcqIdx++));
  q.push(createMCQ("Which American speed skater accomplished the unprecedented sweep of winning all five individual speed skating gold medals at Lake Placid 1980?", "Eric Heiden", "Dan Jansen", "Apolo Ohno", "Eric Heiden won golds at 500m, 1000m, 1500m, 5000m, and 10000m, setting world or Olympic records in every single race.", mcqIdx++));
  q.push(createMCQ("Which American snowboarder won three Olympic gold medals in halfpipe across Turin 2006, Vancouver 2010, and PyeongChang 2018?", "Shaun White", "Danny Davis", "Ayumu Hirano", "Nicknamed The Flying Tomato for his red hair, Shaun White revolutionized competitive snowboarding with massive aerial amplitude and double McTwists.", mcqIdx++));
  q.push(createMCQ("Which Norwegian cross-country skier holds the record for the most successful male Winter Olympian with 15 total medals, including 8 golds?", "Marit Bjorgen and Johannes Klaebo", "Ole Einar Bjorndalen", "Bjorn Daehlie", "Biathlete Ole Einar Bjorndalen earned the moniker The King of Biathlon, competing across six Winter Olympics from 1994 to 2014.", mcqIdx++));
  q.push(createNumber("In what year CE were the first official Winter Olympic Games staged in Chamonix, France?", 1924, "CE", "January 1924", "The inaugural Winter Olympic Games opened on 25 January 1924 in Chamonix at the foot of Mont Blanc."));

  // Cycle 7: Marathon, Distance & Decathlon Immortals
  q.push(createMCQ("Which Ethiopian runner made history at the Rome 1960 Olympics by running barefoot across the cobblestone Appian Way to win marathon gold?", "Abebe Bikila", "Mamo Wolde", "Haile Gebrselassie", "Abebe Bikila became the first sub-Saharan African to win an Olympic gold medal, successfully defending his marathon title with shoes in Tokyo 1964.", mcqIdx++));
  q.push(createMCQ("Which legendary Finnish distance runner, known as the Flying Finn, won nine Olympic gold medals across the 1920s running with a stopwatch in hand?", "Paavo Nurmi", "Ville Ritola", "Hannes Kolehmainen", "Paavo Nurmi won five gold medals in a single games at Paris 1924, winning the 1500m and 5000m finals within two hours of each other.", mcqIdx++));
  q.push(createMCQ("Which Native American athlete won both the pentathlon and decathlon by staggering margins at the 1912 Stockholm Olympics, hailed by King Gustav V as the greatest athlete?", "Jim Thorpe", "Billy Mills", "Ellery Clark", "Thorpe's gold medals were stripped in 1913 over minor semi-pro baseball earnings but were fully restored posthumously by the IOC.", mcqIdx++));
  q.push(createMCQ("Which Czech distance runner pulled off the unique triple crown at Helsinki 1952 by winning the 5,000m, 10,000m, and Marathon in a single games?", "Emil Zatopek", "Ron Clarke", "Alain Mimoun", "Nicknamed the Czech Locomotive for his strained facial grimaces and relentless pace, Zatopek won the marathon in his first-ever attempt at the distance.", mcqIdx++));
  q.push(createMCQ("Which Kenyan distance running legend became the third man to win back-to-back Olympic marathon titles in Rio 2016 and Tokyo 2020?", "Eliud Kipchoge", "Samuel Wanjiru", "Kipchoge Keino", "Eliud Kipchoge dominated global marathon running for over a decade, clocking the first sub-two-hour marathon in a special exhibition in Vienna.", mcqIdx++));
  q.push(createNumber("What is the exact official distance of a standard modern Olympic marathon in meters?", 42195, "meters", "26 miles 385 yards", "The marathon distance was standardized at exactly 42,195 meters (26.2 miles) at London 1908 so the race could start at Windsor Castle and finish in front of the Royal Box."));

  // Cycle 8: Historic Dramas & Turning Points
  q.push(createMCQ("At the 1968 Mexico City Olympics, which two African American sprinters raised black-gloved fists on the medal podium during the US anthem to protest racial injustice?", "Tommie Smith and John Carlos", "Lee Evans and Larry James", "Bob Beamon and Ralph Boston", "Gold medalist Tommie Smith and bronze medalist John Carlos were joined by Australian silver medalist Peter Norman who wore an Olympic Project for Human Rights badge.", mcqIdx++));
  q.push(createMCQ("At the 1972 Munich Olympics, which Palestinian terrorist group took eleven Israeli athletes and coaches hostage, culminating in their tragic deaths?", "Black September", "Hamas", "PLO", "The Munich massacre led to profound soul-searching and transformed modern security protocols for international sports gatherings.", mcqIdx++));
  q.push(createMCQ("Which major Olympic Games was boycotted by the United States and 64 other nations in protest of the 1979 Soviet invasion of Afghanistan?", "1980 Moscow Olympics", "1984 Los Angeles Olympics", "1976 Montreal Olympics", "The Soviet Union and Eastern Bloc nations reciprocated four years later by boycotting the 1984 Los Angeles Summer Olympics.", mcqIdx++));
  q.push(createMCQ("In 1988 at Seoul, which Canadian sprinter was stripped of his 100m gold medal and world record after testing positive for the banned anabolic steroid stanozolol?", "Ben Johnson", "Carl Lewis", "Linford Christie", "The scandal was termed the dirtiest race in history, propelling the international sports community to establish the World Anti-Doping Agency (WADA).", mcqIdx++));
  q.push(createMCQ("Which American heavyweight boxing icon, then known as Cassius Clay, won the light heavyweight Olympic gold medal at Rome 1960?", "Muhammad Ali", "Joe Frazier", "George Foreman", "Clay threw his gold medal into the Ohio River after being refused service in a segregated Louisville restaurant, later receiving a replacement medal in 1996.", mcqIdx++));
  q.push(createNumber("In what year CE did Tommie Smith and John Carlos stage their iconic silent civil rights protest on the medal podium in Mexico City?", 1968, "CE", "October 1968", "The historic podium protest took place on 16 October 1968 following the men's 200-meter final in Mexico City."));

  // Cycle 9: Olympic Symbols & Ceremonies
  q.push(createMCQ("How is the Olympic Flame traditionally ignited in the ruins of ancient Olympia months before each Olympic Games?", "By parabolic mirror concentrating sun rays", "By an electric spark ignition", "By a sacred eternal charcoal flame", "A Greek actress playing a High Priestess captures the pure rays of the sun using a parabolic concave mirror to ignite the Olympic flame at the Temple of Hera.", mcqIdx++));
  q.push(createMCQ("In the Parade of Nations during the Olympic Opening Ceremony, which nation traditionally enters the stadium first as the founder of the ancient games?", "Greece", "The Host Nation", "The United States", "Greece always leads the procession of athletes in honor of the ancient Olympics, while the host country's delegation marches in last.", mcqIdx++));
  q.push(createMCQ("Who composed the inspiring Olympic Hymn that has been officially performed at every Olympic Opening Ceremony since 1960?", "Spyridon Samaras", "Mikis Theodorakis", "John Williams", "With Greek lyrics by poet Kostis Palamas, the anthem premiered at the inaugural 1896 Athens Games and was adopted as the official anthem in 1958.", mcqIdx++));
  q.push(createMCQ("What ceremonial honor is bestowed upon a chosen athlete, judge, and coach who recite the Olympic Oath on behalf of all competitors during the opening ceremony?", "Taking the Olympic Oath", "Lighting the Cauldron", "Carrying the Flag", "The oath commits participants to respect the rules, reject doping, and compete in the true spirit of sportsmanship and fair play.", mcqIdx++));
  q.push(createMCQ("Which iconic boxing legend, trembling with Parkinson's syndrome, emotionally lit the Olympic Cauldron to open the Atlanta 1996 Olympic Games?", "Muhammad Ali", "Evander Holyfield", "Sugar Ray Leonard", "Muhammad Ali lighting the cauldron remains one of the most emotional and enduring moments in modern television and Olympic history.", mcqIdx++));
  q.push(createNumber("How many colored interlocking rings are displayed on the official flag of the International Olympic Committee?", 5, "rings", "The 5 Olympic Rings", "The flag features five interlocking rings: blue, yellow, black, green, and red, representing the union of the world's five continents."));

  // Cycle 10: Modern Superlatives & Paris 2024
  q.push(createMCQ("Which Swedish-American pole vaulter broke his own world record for the ninth time by clearing 6.25 meters to capture gold at Paris 2024?", "Armand Duplantis", "Sam Kendricks", "Renaud Lavillenie", "Armand Mondo Duplantis captivated 80,000 spectators at the Stade de France, clearing 6.25m on his final attempt to solidify his status as the greatest pole vaulter.", mcqIdx++));
  q.push(createMCQ("Which global capital city joined London as the only city in history to host the Summer Olympic Games three separate times in 1900, 1924, and 2024?", "Paris", "Los Angeles", "Tokyo", "Paris hosted the 2024 Olympic Games exactly one century after its 1924 games, featuring the first-ever open-air opening ceremony along the River Seine.", mcqIdx++));
  q.push(createMCQ("Which Pacific island territory of French Polynesia hosted the Olympic surfing competitions during the Paris 2024 Olympic Games?", "Tahiti (Teahupo'o)", "New Caledonia", "Bora Bora", "Teahupo'o is famous for one of the heaviest, most dangerous barreling reef breaks in the world, located 15,000 kilometers from Paris.", mcqIdx++));
  q.push(createMCQ("Which urban dance sport made its official Olympic medal debut at the Paris 2024 Games at the Place de la Concorde?", "Breaking (Breakdancing)", "Skateboarding", "Sport Climbing", "Breaking featured B-Boys and B-Girls battling in one-on-one matches judged on creativity, musicality, technique, and personality.", mcqIdx++));
  q.push(createMCQ("Which American basketball player won his fifth consecutive Olympic gold medal at Paris 2024, becoming the most decorated male basketball Olympian?", "Kevin Durant", "LeBron James", "Stephen Curry", "Kevin Durant won gold in London 2012, Rio 2016, Tokyo 2020, and Paris 2024, scoring more points than any other player in US Olympic basketball history.", mcqIdx++));
  q.push(createNumber("What is the pole vault world record clearance height in meters achieved by Armand Duplantis to win gold at the Paris 2024 Olympics?", 6.25, "meters", "20 ft 6 in", "Duplantis cleared 6.25 meters on 5 August 2024 in Paris, breaking the world record for the ninth time in his career."));

  return {
    id: "olympic-games-records-history-60",
    theme: "The Olympic Games: Ancient Origins to Modern Glory",
    title: "The Olympic Games: Ancient Origins to Modern Glory",
    description: "A 60-question grand master assessment exploring ancient Olympia, the 1896 revival, track and field legends Jesse Owens and Usain Bolt, swimming phenom Michael Phelps, gymnastics perfect 10s, winter games, marathon triumphs, civil rights protests, and Paris 2024.",
    category: "Sports, Records & General Knowledge",
    difficulty: "moderate",
    createdAt: "2026-08-27T00:00:00Z",
    questions: q
  };
}

// -------------------------------------------------------------
// QUIZ 12: world-football-soccer-legends-60
// -------------------------------------------------------------
function getWorldFootballQuiz() {
  let mcqIdx = 0;
  const q = [];

  // Cycle 1: FIFA World Cup Genesis & Brazil Glories
  q.push(createMCQ("In which South American country was the inaugural FIFA World Cup tournament held in 1930, where the hosts defeated Argentina 4 to 2 in the final?", "Uruguay", "Brazil", "Chile", "Uruguay hosted the first 1930 tournament at the newly built Estadio Centenario in Montevideo to celebrate the centenary of their first constitution.", mcqIdx++));
  q.push(createMCQ("Which Brazilian football icon nicknamed O Rei (The King) is the only player in history to win three FIFA World Cup titles (1958, 1962, and 1970)?", "Pele", "Garrincha", "Zico", "Edson Arantes do Nascimento (Pele) debuted at the 1958 World Cup in Sweden at age 17, scoring six goals and leading Brazil to their first world title.", mcqIdx++));
  q.push(createMCQ("What was the original golden trophy awarded to FIFA World Cup champions from 1930 to 1970, named after the pioneering FIFA president?", "Jules Rimet Trophy", "Coupe Henri Delaunay", "Copa America Trophy", "Depicting Nike the Greek goddess of victory, the trophy was permanently awarded to Brazil after their third title in 1970 and later stolen in 1983.", mcqIdx++));
  q.push(createMCQ("What traumatic 1950 World Cup match in Rio de Janeiro saw Uruguay defeat hosts Brazil 2 to 1 before 200,000 stunned spectators in the Maracana?", "The Maracanazo", "The Miracle of Bern", "The Aztec Miracle", "Alcides Ghiggia's 79th-minute winning goal for Uruguay caused widespread national grief in Brazil, prompting the team to abandon their white kits for yellow.", mcqIdx++));
  q.push(createMCQ("Which bowlegged Brazilian winger, nicknamed The Joy of the People, dazzled defenders with his dribbling and led Brazil to victory in 1962 when Pele was injured?", "Garrincha", "Jairzinho", "Tostao", "Garrincha won both the Golden Ball as best player and Golden Boot as joint top scorer during the 1962 World Cup in Chile.", mcqIdx++));
  q.push(createNumber("How many total FIFA World Cup tournament titles did Brazilian legend Pele win as a player during his international career?", 3, "World Cup titles", "3 World Cups (1958, 1962, 1970)", "Pele remains the only footballer in history to win three World Cup championship medals (Sweden 1958, Chile 1962, and Mexico 1970)."));

  // Cycle 2: Diego Maradona & Argentina Glories
  q.push(createMCQ("Which Argentine maestro led his country to World Cup glory in Mexico 1986, scoring two of the most famous goals in football history against England?", "Diego Maradona", "Mario Kempes", "Gabriel Batistuta", "Maradona captained Argentina to victory over West Germany in the 1986 final, winning the Golden Ball as the undisputed player of the tournament.", mcqIdx++));
  q.push(createMCQ("What controversial phrase did Diego Maradona use to describe his unpenalized 51st-minute opening goal against England in the 1986 World Cup quarter-final?", "The Hand of God", "The Miracle Strike", "The Golden Touch", "Maradona famously remarked that the goal was scored a little with the head of Maradona and a little with the hand of God.", mcqIdx++));
  q.push(createMCQ("What 60-meter solo dribble by Diego Maradona past five English players and goalkeeper Peter Shilton in 1986 was voted FIFA's Goal of the Century?", "The Goal of the Century", "The Maracana Run", "The Cosmic Dribble", "Starting in his own half, Maradona took 11 touches over 10 seconds to score what is widely regarded as the greatest individual goal in World Cup history.", mcqIdx++));
  q.push(createMCQ("In which southern Italian city did Diego Maradona become a deity, leading the local club to their first two historic Serie A titles in 1987 and 1990?", "Naples (Napoli)", "Turin (Juventus)", "Milan (AC Milan)", "Maradona transformed SSC Napoli from relegation strugglers into European champions, winning the 1989 UEFA Cup; the stadium was renamed in his honor in 2020.", mcqIdx++));
  q.push(createMCQ("Which flowing-haired striker scored six goals, including two in the 1978 final against the Netherlands, to lead Argentina to their first World Cup title?", "Mario Kempes", "Daniel Passarella", "Osvaldo Ardiles", "Mario El Matador Kempes won both the Golden Ball and Golden Boot as Argentina triumphed after extra time on home soil in Buenos Aires.", mcqIdx++));
  q.push(createNumber("In what minute of the 1986 World Cup quarter-final match against England did Diego Maradona score his iconic Goal of the Century?", 55, "minute", "55th minute", "Four minutes after the Hand of God, Maradona received the ball in the 55th minute from Hector Enrique to embark on his 60-meter solo run."));

  // Cycle 3: Total Football & European Masterminds
  q.push(createMCQ("Which Dutch football genius perfected the fluid tactical philosophy of Total Football with Ajax, Barcelona, and the Netherlands national team?", "Johan Cruyff", "Rinus Michels", "Marco van Basten", "Cruyff won three Ballon d'Or awards and three consecutive European Cups with Ajax, later laying the tactical foundations for Barcelona's La Masia academy.", mcqIdx++));
  q.push(createMCQ("Which German defensive legend nicknamed Der Kaiser won the World Cup as captain of West Germany in 1974 and as manager in 1990?", "Franz Beckenbauer", "Gerd Muller", "Sepp Maier", "Beckenbauer invented the modern role of the attacking sweeper (libero), dictating play from deep defense with unmatched elegance.", mcqIdx++));
  q.push(createMCQ("Which Hungarian goal machine captained the Mighty Magyars of the 1950s and scored 84 goals in 85 international matches, inspiring FIFA's Best Goal award?", "Ferenc Puskas", "Sandor Kocsis", "Nandor Hidegkuti", "Puskas led Hungary to Olympic gold in 1952 and dismantled England at Wembley in 1953 before winning three European Cups with Real Madrid.", mcqIdx++));
  q.push(createMCQ("Which Mozambique-born Portuguese striker nicknamed The Black Panther led Benfica to European glory and scored nine goals at the 1966 World Cup?", "Eusebio", "Luis Figo", "Mario Coluna", "Eusebio was renowned for his blistering speed, athletic power, and ferocious right-footed shot, winning the 1965 Ballon d'Or.", mcqIdx++));
  q.push(createMCQ("Which lethal German striker nicknamed Der Bomber scored 68 goals in 62 international matches, including the 1974 World Cup winning goal?", "Gerd Muller", "Karl-Heinz Rummenigge", "Uwe Seeler", "Gerd Muller possessed unmatched predatory instincts in the penalty box, holding the World Cup all-time scoring record for 32 years.", mcqIdx++));
  q.push(createNumber("How many international goals did Hungarian maestro Ferenc Puskas score in his 85 appearances for the Hungary national team?", 84, "international goals", "84 goals in 85 caps", "Puskas maintained an astonishing scoring rate of nearly one goal per game, netting 84 times for Hungary between 1945 and 1956."));

  // Cycle 4: Lionel Messi vs. Cristiano Ronaldo
  q.push(createMCQ("Which Argentine wizard won a record eight Ballon d'Or awards and captained Argentina to World Cup victory at Qatar 2022?", "Lionel Messi", "Cristiano Ronaldo", "Luka Modric", "Messi scored 7 goals in Qatar 2022, becoming the first player to win the World Cup Golden Ball twice and completing his peerless trophy collection.", mcqIdx++));
  q.push(createMCQ("Which Portuguese superstar holds the all-time international scoring record with over 130 goals and won five UEFA Champions League titles?", "Cristiano Ronaldo", "Bruno Fernandes", "Bernardo Silva", "Cristiano Ronaldo has won five Ballon d'Or awards and is the all-time top goalscorer in Champions League history with 140 goals.", mcqIdx++));
  q.push(createMCQ("What legendary Spanish rivalry between FC Barcelona and Real Madrid was defined for a decade by the fierce individual rivalry between Messi and Ronaldo?", "El Clasico", "Derbi Madrileno", "Superclasico", "Between 2009 and 2018, Messi and Ronaldo shattered scoring records in El Clasico, attracting hundreds of millions of viewers across the globe.", mcqIdx++));
  q.push(createMCQ("In the calendar year 2012, how many official goals did Lionel Messi score for Barcelona and Argentina to set the Guinness World Record for most goals in a year?", "91 goals", "85 goals", "75 goals", "Messi surpassed Gerd Muller's 1972 record of 85 goals by scoring 91 goals in 69 games across 2012.", mcqIdx++));
  q.push(createMCQ("Which international tournament did Cristiano Ronaldo win with Portugal in 2016, overcoming hosts France 1 to 0 in extra time in Paris?", "UEFA European Championship (Euro 2016)", "FIFA Confederations Cup", "UEFA Nations League", "Despite being forced off injured early in the final, Ronaldo passionately coached his teammates from the touchline as Eder scored the winner.", mcqIdx++));
  q.push(createNumber("How many career Ballon d'Or awards has Argentine legend Lionel Messi won as of 2023?", 8, "Ballon d'Or awards", "8 Ballon d'Or trophies", "Lionel Messi holds the all-time record with 8 Ballon d'Or trophies won in 2009, 2010, 2011, 2012, 2015, 2019, 2021, and 2023."));

  // Cycle 5: UEFA Champions League Drama & Real Madrid Royalty
  q.push(createMCQ("Which Spanish club holds the undisputed all-time record for the most European Cup / UEFA Champions League titles, winning their 15th title in 2024?", "Real Madrid", "AC Milan", "Bayern Munich", "Real Madrid dominated the early European Cup with five consecutive titles from 1956 to 1960 and won six UCL trophies between 2014 and 2024.", mcqIdx++));
  q.push(createMCQ("Which French maestro scored a legendary left-footed volley from the edge of the box to win the 2002 Champions League final for Real Madrid in Glasgow?", "Zinedine Zidane", "Thierry Henry", "Michel Platini", "Zidane's exquisite technique on Roberto Carlos's looping cross against Bayer Leverkusen is widely voted the greatest goal in Champions League final history.", mcqIdx++));
  q.push(createMCQ("Which English club completed an unprecedented continental treble under Sir Alex Ferguson in 1999 with two injury-time goals against Bayern Munich?", "Manchester United", "Liverpool", "Chelsea", "Teddy Sheringham and Ole Gunnar Solskjaer scored in the 91st and 93rd minutes at the Camp Nou to complete the Premier League, FA Cup, and UCL treble.", mcqIdx++));
  q.push(createMCQ("What legendary 2005 Champions League final in Istanbul saw Liverpool recover from a three-goal halftime deficit against AC Milan to win on penalties?", "The Miracle of Istanbul", "The Battle of Rome", "The Final of Kings", "Steven Gerrard sparked a six-minute second-half comeback with three goals, before goalkeeper Jerzy Dudek's wobbly legs secured victory in the shootout.", mcqIdx++));
  q.push(createMCQ("Which Italian manager became the first manager in history to win five UEFA Champions League titles across AC Milan and Real Madrid?", "Carlo Ancelotti", "Jose Mourinho", "Pep Guardiola", "Don Carlo won two titles with AC Milan (2003, 2007) and three with Real Madrid (2014, 2022, 2024), also winning league titles in all top five European leagues.", mcqIdx++));
  q.push(createNumber("How many total European Cup and UEFA Champions League titles has Real Madrid won as of their 2024 triumph?", 15, "titles", "15 UCL trophies", "Real Madrid extended their dominant record to 15 European Cup/Champions League titles after defeating Borussia Dortmund at Wembley in June 2024."));

  // Cycle 6: Legendary Club Dynasties & Unbeaten Runs
  q.push(createMCQ("Which manager coached FC Barcelona's legendary Tiki-Taka team to an unprecedented six trophies (the sextuple) in a single calendar year in 2009?", "Pep Guardiola", "Frank Rijkaard", "Luis Enrique", "Guardiola's Barcelona, anchored by Xavi, Iniesta, and Messi, dominated European football with suffocating ball possession and geometric passing triangles.", mcqIdx++));
  q.push(createMCQ("Which English team went the entire 38-game 2003 to 2004 Premier League season undefeated under manager Arsene Wenger, earning the nickname The Invincibles?", "Arsenal", "Chelsea", "Manchester United", "Captained by Patrick Vieira with Thierry Henry scoring 30 league goals, Arsenal won 26 matches and drew 12, receiving a unique gold Premier League trophy.", mcqIdx++));
  q.push(createMCQ("Which Italian club went an astonishing 58 consecutive Serie A matches unbeaten between 1991 and 1993 under Arrigo Sacchi and Fabio Capello?", "AC Milan", "Juventus", "Inter Milan", "AC Milan's legendary defense featured Franco Baresi, Paolo Maldini, Alessandro Costacurta, and Mauro Tassotti.", mcqIdx++));
  q.push(createMCQ("Which French forward is Arsenal's all-time record goalscorer with 228 goals, renowned for his signature curling finishes into the far corner?", "Thierry Henry", "Ian Wright", "Dennis Bergkamp", "Thierry Henry won four Premier League Golden Boots and was the talismanic centerpiece of Arsene Wenger's Invincibles squad.", mcqIdx++));
  q.push(createMCQ("Which Bavarian giant won ten consecutive Bundesliga titles between 2013 and 2022, including two continental trebles in 2013 and 2020?", "Bayern Munich", "Borussia Dortmund", "Bayer Leverkusen", "Bayern Munich established supreme domestic dominance in Germany, powered by superstars like Thomas Muller, Robert Lewandowski, and Manuel Neuer.", mcqIdx++));
  q.push(createNumber("How many matches did Arsenal play without a single defeat in their historic 2003 to 2004 Invincibles Premier League season?", 38, "unbeaten matches", "38 unbeaten league games", "Arsenal played all 38 Premier League fixtures in the 2003 to 2004 season without suffering a single loss (26 wins, 12 draws)."));

  // Cycle 7: All-Time World Cup Goalscorers
  q.push(createMCQ("Which German striker holds the all-time record for the most career FIFA World Cup goals in history, scoring 16 goals across four tournaments?", "Miroslav Klose", "Ronaldo Nazario", "Gerd Muller", "Klose scored his 16th record-breaking World Cup goal during Germany's historic semi-final triumph over Brazil in Belo Horizonte in 2014.", mcqIdx++));
  q.push(createMCQ("Which Brazilian striker, nicknamed Il Fenomeno (R9), scored 15 World Cup goals and led Brazil to victory in 2002 with two goals in the final against Germany?", "Ronaldo Nazario", "Romario", "Rivaldo", "Ronaldo overcame career-threatening knee tendon ruptures to win the 2002 Golden Boot with eight goals, redeeming Brazil's 1998 final heartbreak.", mcqIdx++));
  q.push(createMCQ("Which French striker holds the record for the most goals scored in a single FIFA World Cup tournament, netting 13 goals in Sweden 1958?", "Just Fontaine", "Jean-Pierre Papin", "Michel Platini", "Fontaine scored 13 goals in just six matches in 1958, a single-tournament scoring record that has remained untouched for nearly seven decades.", mcqIdx++));
  q.push(createMCQ("Which French forward became the second player in history to score a hat-trick in a World Cup final during the thrilling 3 to 3 draw against Argentina in Qatar 2022?", "Kylian Mbappe", "Antoine Griezmann", "Karim Benzema", "Mbappe won the 2022 Golden Boot with 8 goals, scoring twice in 97 seconds to force extra time and converting his third in the 118th minute.", mcqIdx++));
  q.push(createMCQ("Who was the first player in history to score a hat-trick in a World Cup final, leading England to a 4 to 2 victory over West Germany at Wembley in 1966?", "Geoff Hurst", "Bobby Charlton", "Jimmy Greaves", "Sir Geoff Hurst's controversial second goal struck the underside of the crossbar and bounced down, awarded by referee Gottfried Dienst.", mcqIdx++));
  q.push(createNumber("What is the all-time career FIFA World Cup tournament scoring record held by Germany's Miroslav Klose?", 16, "goals", "16 World Cup goals", "Miroslav Klose scored 16 goals across 24 World Cup matches between 2002 and 2014, surpassing Ronaldo Nazario's mark of 15."));

  // Cycle 8: Defensive Walls & Goalkeeping Immortals
  q.push(createMCQ("Which Soviet goalkeeper, nicknamed The Black Spider for his all-black kit and acrobatics, remains the only goalkeeper in history to win the Ballon d'Or (1963)?", "Lev Yashin", "Dino Zoff", "Gordon Banks", "Yashin saved an estimated 150 penalty kicks throughout his career and pioneered commanding his penalty area and punching crosses away.", mcqIdx++));
  q.push(createMCQ("Which English goalkeeper made the famous Save of the Century, diving low to claw away a point-blank bouncing header from Pele in 1970?", "Gordon Banks", "Peter Shilton", "Ray Clemence", "Gordon Banks's breathtaking reflex save against Brazil in the searing heat of Guadalajara is universally celebrated among the greatest saves ever made.", mcqIdx++));
  q.push(createMCQ("Which Italian goalkeeping legend played 176 times for Italy, captained them to the 2006 World Cup, and made over 1,100 career appearances?", "Gianluigi Buffon", "Walter Zenga", "Francesco Toldo", "Buffon conceded only two goals (an own goal and a penalty) throughout the entire 2006 World Cup, finishing runner-up for the 2006 Ballon d'Or.", mcqIdx++));
  q.push(createMCQ("Which legendary AC Milan captain spent his entire 25-season professional career at the club, making 902 appearances and winning five European Cups?", "Paolo Maldini", "Franco Baresi", "Alessandro Nesta", "Maldini was the quintessential complete defender, renowned for flawless positioning, tactical intelligence, and rarely needing to make slide tackles.", mcqIdx++));
  q.push(createMCQ("Which German goalkeeper revolutionized the sweeper-keeper role, playing far outside his penalty box during Germany's 2014 World Cup triumph?", "Manuel Neuer", "Oliver Kahn", "Jens Lehmann", "Neuer acted as an auxiliary sweeper with extraordinary passing and aggressive ball interception outside the box, redefining modern goalkeeping.", mcqIdx++));
  q.push(createNumber("In what year CE did legendary Soviet goalkeeper Lev Yashin win the prestigious Ballon d'Or award?", 1963, "CE", "1963 Ballon d'Or", "Lev Yashin was awarded the Ballon d'Or in December 1963, remaining the only goalkeeper to win the award in over six decades."));

  // Cycle 9: Women's World Cup & Global Icons
  q.push(createMCQ("Which country has won the most FIFA Women's World Cup titles in history, capturing four championships in 1991, 1999, 2015, and 2019?", "United States", "Germany", "Japan", "The US Women's National Team (USWNT) established international dominance, propelled by stars like Michelle Akers, Mia Hamm, and Megan Rapinoe.", mcqIdx++));
  q.push(createMCQ("Which Brazilian legend is the all-time top goalscorer in FIFA World Cup history (men or women) with 17 goals across six tournaments?", "Marta", "Formiga", "Cristiane", "Marta Vieira da Silva has been named FIFA World Player of the Year six times, widely celebrated as the greatest female footballer of all time.", mcqIdx++));
  q.push(createMCQ("Which American soccer star scored the winning penalty in the 1999 Women's World Cup final shootout against China, famously celebrating in her sports bra?", "Brandi Chastain", "Mia Hamm", "Julie Foudy", "Chastain's spontaneous celebration before 90,185 fans at the Pasadena Rose Bowl became an iconic landmark photograph in women's sports history.", mcqIdx++));
  q.push(createMCQ("Which Spanish midfielder won the 2023 FIFA Women's World Cup and consecutive Ballon d'Or Feminin awards in 2023 and 2024?", "Aitana Bonmati", "Alexia Putellas", "Jennifer Hermoso", "Bonmati orchestrated Spain's possession-based victory in Australia and New Zealand, winning the Golden Ball as the tournament's top player.", mcqIdx++));
  q.push(createMCQ("Which Asian nation made history by winning the 2011 FIFA Women's World Cup in Germany, defeating the USA in a dramatic penalty shootout?", "Japan", "China", "South Korea", "Captained by tournament top scorer Homare Sawa, Japan's Nadeshiko provided national inspiration following the devastating 2011 tsunami.", mcqIdx++));
  q.push(createNumber("How many career FIFA Women's World Cup goals has Brazilian superstar Marta scored, setting the all-time tournament record?", 17, "goals", "17 tournament goals", "Marta has scored 17 World Cup goals across six tournament appearances between 2003 and 2023, the most by any player in World Cup history."));

  // Cycle 10: Pitch Dimensions, Rules & Curiosities
  q.push(createMCQ("What English referee conceived the yellow and red card disciplinary system after experiencing communication difficulties with foreign players at the 1966 World Cup?", "Ken Aston", "Jack Taylor", "Pierluigi Collina", "Inspired by traffic lights while waiting at a Kensington road junction, Aston proposed color-coded cards that were introduced at Mexico 1970.", mcqIdx++));
  q.push(createMCQ("What video technology system was officially introduced to the FIFA World Cup in Russia 2018 to review clear and obvious refereeing errors?", "VAR (Video Assistant Referee)", "Goal-Line Technology", "Hawk-Eye", "VAR assists match officials on four match-changing situations: goals, penalty decisions, direct red cards, and mistaken identity.", mcqIdx++));
  q.push(createMCQ("What is the radius of the center circle on a standard regulation association football pitch?", "9.15 meters (10 yards)", "5.5 meters", "12 meters", "Opposing players must remain outside the 9.15-meter (10-yard) radius during kick-offs, just as defensive walls must retreat 9.15 meters on free kicks.", mcqIdx++));
  q.push(createMCQ("What penalty rule was introduced in 1970 to resolve tied knockout matches, replacing coin tosses and replays?", "Penalty Shootout", "Golden Goal", "Corner Countback", "Before penalty shootouts, major finals like Italy's 1968 European Championship semi-final were decided by the toss of a coin.", mcqIdx++));
  q.push(createMCQ("In association football, a player cannot be penalized for an offside offense directly from which of the following set pieces?", "Throw-in, corner kick, or goal kick", "Direct free kick", "Indirect free kick", "Law 11 of the IFAB Laws of the Game explicitly states there is no offside offense if a player receives the ball directly from a throw-in, corner, or goal kick.", mcqIdx++));
  q.push(createNumber("What is the exact distance in meters from the penalty spot to the goal line on a standard football pitch?", 11, "meters", "12 yards (10.97m)", "The penalty spot is positioned exactly 12 yards (10.97 meters, rounded to 11 meters in metric standards) from the center of the goal line."));

  return {
    id: "world-football-soccer-legends-60",
    theme: "World Football (Soccer): World Cups & Club Legends",
    title: "World Football (Soccer): World Cups & Club Legends",
    description: "A 60-question grand master assessment exploring the FIFA World Cup from Uruguay 1930 to Qatar 2022, Pele, Diego Maradona, Cruyff and Total Football, Messi vs. Ronaldo, UEFA Champions League drama, Real Madrid royalty, Lev Yashin, and Women's World Cup icons.",
    category: "Sports, Records & General Knowledge",
    difficulty: "moderate",
    createdAt: "2026-08-27T00:00:00Z",
    questions: q
  };
}

module.exports = {
  getTheaterOperaQuiz,
  getWorldReligionsQuiz,
  getOlympicGamesQuiz,
  getWorldFootballQuiz
};

if (require.main === module) {
  const quizzes = [
    getTheaterOperaQuiz(),
    getWorldReligionsQuiz(),
    getOlympicGamesQuiz(),
    getWorldFootballQuiz()
  ];
  
  for (const quiz of quizzes) {
    const dir = path.join('quizzes', quiz.id);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, 'dataset.json'), JSON.stringify(quiz, null, 2), 'utf8');
    console.log(`Wrote: ${dir}/dataset.json`);
  }
}
