const fs = require('fs');
const path = require('path');

function createMCQ(question, correctOption, wrongOption1, wrongOption2, explanation, mcqIndex) {
  const targetSlot = mcqIndex % 3;
  const options = [];
  if (targetSlot === 0) {
    options.push(correctOption, wrongOption1, wrongOption2);
  } else if (targetSlot === 1) {
    options.push(wrongOption1, correctOption, wrongOption2);
  } else {
    options.push(wrongOption1, wrongOption2, correctOption);
  }
  const cleanOptions = options.map(o => o.replace(/[()[\]{}]/g, '').trim());
  return {
    type: 'mcq',
    question: question.trim(),
    options: cleanOptions,
    correctIndex: targetSlot,
    explanation: explanation.trim()
  };
}

function createNumber(question, target, metricUnit, imperialDisplay, explanation) {
  return {
    type: 'number',
    question: question.trim(),
    target: typeof target === 'number' ? target : parseFloat(target),
    metricUnit: metricUnit.trim(),
    imperialDisplay: imperialDisplay ? imperialDisplay.trim() : undefined,
    explanation: explanation.trim()
  };
}

// -------------------------------------------------------------
// QUIZ 5: architecture-wonders-styles-60
// -------------------------------------------------------------
function getArchitectureQuiz() {
  let mcqIdx = 0;
  const q = [];

  // Cycle 1: Classical Antiquity & Ancient Megastructures
  q.push(createMCQ("Which iconic Doric temple dedicated to Athena Parthenos crowns the Acropolis of Athens, built under Pericles in the 5th century BCE?", "Parthenon", "Erechtheion", "Temple of Hephaestus", "Designed by architects Ictinus and Callicrates with Phidias as chief sculptor, the Parthenon represents the zenith of classical Greek architecture.", mcqIdx++));
  q.push(createMCQ("Which ancient Roman amphitheatre in Rome, inaugurated under Emperor Titus in 80 CE, could accommodate over 50,000 spectators?", "Colosseum", "Circus Maximus", "Theater of Marcellus", "The Flavian Amphitheatre (Colosseum) utilized travertine stone, tuff, and innovative concrete vaulting to stage gladiatorial spectacles.", mcqIdx++));
  q.push(createMCQ("Which Roman temple rebuilt by Emperor Hadrian features a massive unreinforced solid concrete dome with a central open oculus?", "Pantheon", "Temple of Vesta", "Temple of Saturn", "The Pantheon dome remains the world's largest unreinforced solid concrete dome almost two millennia after its completion in 125 CE.", mcqIdx++));
  q.push(createMCQ("What is the oldest and largest of the Giza pyramid complex monuments, constructed for Pharaoh Khufu during Egypt's Old Kingdom?", "Great Pyramid of Giza", "Pyramid of Khafre", "Pyramid of Menkaure", "Standing at an original height of 146.6 meters, the Great Pyramid remained the tallest human-made structure in the world for over 3,800 years.", mcqIdx++));
  q.push(createMCQ("What massive stepped pyramid structures with exterior staircases served as sacred religious platforms in ancient Mesopotamia?", "Ziggurats", "Mastabas", "Dolmens", "Built from sun-baked mudbrick with baked brick facades, ziggurats like the Great Ziggurat of Ur elevated temples toward the sky.", mcqIdx++));
  q.push(createNumber("What is the internal diameter of the unreinforced concrete dome of the Roman Pantheon in meters?", 43, "meters", "approx. 142 feet", "The interior diameter and the interior height of the Pantheon are exactly identical at 43.3 meters (142 feet), forming a perfect sphere."));

  // Cycle 2: Byzantine & Islamic Marvels
  q.push(createMCQ("Which monumental cathedral in Istanbul, featuring a revolutionary pendentive dome, was built under Byzantine Emperor Justinian I?", "Hagia Sophia", "Hagia Irene", "Church of the Holy Apostles", "Engineered by Isidore of Miletus and Anthemius of Tralles, Hagia Sophia was dedicated in 537 CE as the greatest church in Christendom.", mcqIdx++));
  q.push(createMCQ("Which magnificent Islamic palace and fortress complex in Granada, Spain, is famous for the Court of the Lions and intricate muqarnas vaulting?", "Alhambra", "Alcazar of Seville", "Mezquita of Cordoba", "Constructed by the Nasrid dynasty, the Alhambra features exquisite Arabesque plasterwork, serene reflecting pools, and poetic calligraphy.", mcqIdx++));
  q.push(createMCQ("Which iconic ivory-white marble mausoleum on the Yamuna river in Agra was commissioned by Mughal Emperor Shah Jahan for his wife Mumtaz Mahal?", "Taj Mahal", "Humayun's Tomb", "Bibi Ka Maqbara", "Completed in 1653 with symmetrical gardens and minarets, the Taj Mahal stands as the pinnacle of Indo-Islamic Mughal architecture.", mcqIdx++));
  q.push(createMCQ("Which 7th-century Islamic shrine on the Temple Mount in Jerusalem is distinguished by its glittering octagonal gilded dome and tilework?", "Dome of the Rock", "Al-Aqsa Mosque", "Umayyad Mosque", "Built by the Umayyad Caliph Abd al-Malik in 691 CE, the Dome of the Rock is one of the earliest existing masterpieces of Islamic architecture.", mcqIdx++));
  q.push(createMCQ("Which architectural element in a mosque indicates the precise direction of the qibla toward Mecca for daily prayer?", "Mihrab", "Minbar", "Muqarnas", "The mihrab is a semicircular decorative niche in the wall of a mosque that orients worshippers toward the Kaaba in Mecca.", mcqIdx++));
  q.push(createNumber("In what year CE was the grand Byzantine cathedral Hagia Sophia completed and consecrated in Constantinople?", 537, "CE", "December 537 CE", "Justinian I inaugurated the magnificent Hagia Sophia on 27 December 537 CE, declaring: Solomon, I have surpassed thee!"));

  // Cycle 3: Gothic Splendor & Flying Buttresses
  q.push(createMCQ("Which structural innovation enabled Gothic cathedrals to build soaring, thin walls filled with colorful stained glass by transferring roof loads outward?", "Flying buttresses", "Barrel vaults", "Corbel arches", "Flying buttresses channeled the lateral thrust of stone vaults away from the walls into exterior piers, allowing towering clerestory windows.", mcqIdx++));
  q.push(createMCQ("Which Parisian Gothic cathedral on the Ile de la Cite is world-renowned for its rose windows, twin west towers, and gargoyles?", "Notre-Dame de Paris", "Sainte-Chapelle", "Saint-Denis Basilica", "Begun in 1163 under Bishop Maurice de Sully, Notre-Dame represents early and high French Gothic architectural mastery.", mcqIdx++));
  q.push(createMCQ("Which German Gothic masterpiece took more than six centuries to finish, possessing the largest twin-spired cathedral facade on Earth?", "Cologne Cathedral", "Ulm Minster", "Freiburg Minster", "Construction on Cologne Cathedral began in 1248, was halted for centuries, and was finally completed in 1880 following original medieval plans.", mcqIdx++));
  q.push(createMCQ("Which French High Gothic cathedral is celebrated for having nearly all of its original 13th-century cobalt-blue stained glass intact?", "Chartres Cathedral", "Amiens Cathedral", "Reims Cathedral", "Chartres Cathedral is famous for Chartres blue glass and its perfectly preserved labyrinth inlaid on the nave floor.", mcqIdx++));
  q.push(createMCQ("What architectural term refers to the stone or lead spouts carved in grotesque monstrous forms to divert rainwater away from masonry walls?", "Gargoyles", "Grotesques", "Finials", "Unlike purely decorative grotesques, functional gargoyles feature open mouths and hollow channels that eject rainwater from roofs.", mcqIdx++));
  q.push(createNumber("How many years did the construction of Cologne Cathedral take from its start in 1248 to its completion in 1880?", 632, "years", "632 total years", "Spanning from 1248 to 1880, Cologne Cathedral required 632 years to complete, surviving World War II bombings as a towering symbol of persistence."));

  // Cycle 4: Renaissance & Baroque Mastery
  q.push(createMCQ("Which Renaissance genius engineered the revolutionary double-shelled brick dome of the Florence Cathedral (Santa Maria del Fiore) without wooden scaffolding?", "Filippo Brunelleschi", "Leon Battista Alberti", "Donato Bramante", "Brunelleschi employed a herringbone brick-laying pattern and internal stone chains to construct the largest masonry dome ever built.", mcqIdx++));
  q.push(createMCQ("Which Roman Baroque sculptor and architect designed the majestic elliptical colonnade embracing St. Peter's Square in the Vatican?", "Gian Lorenzo Bernini", "Francesco Borromini", "Pietro da Cortona", "Bernini's monumental quadruple colonnade of 284 Doric columns was designed to symbolize the maternal arms of the church embracing humanity.", mcqIdx++));
  q.push(createMCQ("Which opulent royal chateau expanded by King Louis XIV near Paris came to epitomize French Baroque grandiosity and absolutism?", "Palace of Versailles", "Chateau de Chambord", "Chateau de Fontainebleau", "Versailles features the legendary Hall of Mirrors, sprawling axial gardens by Andre Le Notre, and over 700 rooms.", mcqIdx++));
  q.push(createMCQ("Which English architect designed the magnificent baroque St. Paul's Cathedral in London following the Great Fire of 1666?", "Sir Christopher Wren", "Inigo Jones", "John Vanbrugh", "Sir Christopher Wren rebuilt 52 city parish churches in London, with St. Paul's soaring triple-dome as his crowning achievement.", mcqIdx++));
  q.push(createMCQ("Which 16th-century Italian Renaissance architect authored The Four Books of Architecture, establishing a classical villa style that influenced global buildings?", "Andrea Palladio", "Giacomo Barozzi da Vignola", "Sebastiano Serlio", "Palladian architecture, based on harmonic symmetry and Roman temple porticos, profoundly shaped British and American public architecture.", mcqIdx++));
  q.push(createNumber("What is the diameter width of the octagonal base span of Brunelleschi's Florence Cathedral dome in meters?", 45, "meters", "approx. 148 feet", "The base of the octagonal dome spans approximately 45 meters (148 feet), remaining the largest unreinforced masonry dome on the planet."));

  // Cycle 5: Neoclassicism & Historicism
  q.push(createMCQ("Which Paris monument commissioned by Napoleon Bonaparte in 1806 stands at the western end of the Champs-Elysees to honor the Grande Armee?", "Arc de Triomphe", "Pantheon", "La Madeleine", "Designed by Jean Chalgrin in neoclassical style with relief sculptures like La Marseillaise, the arch honors French soldiers who fought in the Revolution and Empire.", mcqIdx++));
  q.push(createMCQ("Which Bavarian fairy-tale castle perched on a rugged cliff was commissioned by King Ludwig II as a romanticized tribute to Richard Wagner?", "Neuschwanstein Castle", "Hohenzollern Castle", "Linderhof Palace", "Neuschwanstein's Romanesque Revival towers and theatrical interiors inspired the iconic design of Walt Disney's Cinderella and Sleeping Beauty castles.", mcqIdx++));
  q.push(createMCQ("Which Gothic Revival complex on the River Thames in London was rebuilt by Charles Barry and Augustus Pugin after an 1834 fire?", "Palace of Westminster", "Buckingham Palace", "Hampton Court Palace", "The Palace of Westminster houses the UK Parliament and includes the famous Elizabeth Tower, which houses the great bell Big Ben.", mcqIdx++));
  q.push(createMCQ("Which neoclassical French landmark in the Latin Quarter of Paris, originally built as the Church of Sainte-Genevieve, serves as a secular mausoleum?", "Pantheon", "Les Invalides", "Saint-Sulpice", "The Paris Pantheon bears the famous inscription: Aux grands hommes, la patrie reconnaissante (To great men, the grateful homeland).", mcqIdx++));
  q.push(createMCQ("What distinct architectural order features elaborate acanthus leaf carvings on its capital, originating in ancient Greece and favored by Rome?", "Corinthian order", "Doric order", "Ionic order", "The Corinthian order is the most ornate of the three classical orders, prized for its decorative slender columns and floral capitals.", mcqIdx++));
  q.push(createNumber("What is the total height of the Arc de Triomphe in Paris in meters?", 50, "meters", "approx. 164 feet", "Standing 50 meters (164 feet) tall, the Arc de Triomphe was the tallest triumphal arch in the world until the 1980s."));

  // Cycle 6: The Industrial Revolution & Iron/Glass
  q.push(createMCQ("Which 300-meter wrought-iron lattice tower was erected as the grand entrance arch for the 1889 Paris Exposition Universelle?", "Eiffel Tower", "Tokyo Tower", "Blackpool Tower", "Engineered by Gustave Eiffel's company, the tower surpassed the Washington Monument to become the world's tallest human-made structure until 1930.", mcqIdx++));
  q.push(createMCQ("Which revolutionary cast-iron and plate-glass structure designed by Joseph Paxton housed the 1851 Great Exhibition in London's Hyde Park?", "The Crystal Palace", "Palm House at Kew", "Euston Station", "Paxton used prefabricated modular iron and glass components inspired by giant water lily leaves to build the massive hall in under nine months.", mcqIdx++));
  q.push(createMCQ("Which historic suspension bridge connecting Manhattan and Brooklyn was designed by John Augustus Roebling and completed in 1883?", "Brooklyn Bridge", "Manhattan Bridge", "Williamsburg Bridge", "The Brooklyn Bridge was the first steel-wire suspension bridge in history, recognized for its massive neo-Gothic limestone towers.", mcqIdx++));
  q.push(createMCQ("Which French engineer designed the internal load-bearing iron truss framework that supports the copper skin of the Statue of Liberty?", "Gustave Eiffel", "Eugene Viollet-le-Duc", "Frederic-Auguste Bartholdi", "While Bartholdi sculpted Liberty's exterior copper form, Eiffel engineered the flexible internal pylon that allows the statue to sway safely in high winds.", mcqIdx++));
  q.push(createMCQ("Which American city is celebrated as the birthplace of the modern skyscraper following the Great Fire of 1871 and the Home Insurance Building in 1885?", "Chicago", "New York City", "Philadelphia", "William Le Baron Jenney's Home Insurance Building in Chicago pioneered internal steel-frame skeleton construction, eliminating masonry load limits.", mcqIdx++));
  q.push(createNumber("What was the original architectural height in meters of the Eiffel Tower upon its completion in 1889?", 300, "meters", "approx. 984 feet", "Upon opening in 1889, the Eiffel Tower measured exactly 300 meters, holding the record as the world's tallest structure for over 41 years."));

  // Cycle 7: Art Nouveau & Art Deco
  q.push(createMCQ("Which Catalan architect designed the breathtaking, organic basilica of the Sagrada Familia in Barcelona, under construction since 1882?", "Antoni Gaudi", "Lluis Domenech i Montaner", "Josep Puig i Cadafalch", "Gaudi's organic Art Nouveau masterpiece mimics forest canopies, hyperbolic vaults, and natural geometric curves, set for completion in the late 2020s.", mcqIdx++));
  q.push(createMCQ("Which 102-story Art Deco skyscraper in Midtown Manhattan held the title of world's tallest building from 1931 until 1970?", "Empire State Building", "Chrysler Building", "Rockefeller Center", "Built in an astonishing 13.5 months during the Great Depression, the Empire State Building rose to 381 meters at its roof (443.2m to tip).", mcqIdx++));
  q.push(createMCQ("Which Art Deco skyscraper in New York City is famous for its terraced crown of sunburst patterns crafted from Nirosta stainless steel?", "Chrysler Building", "Woolworth Building", "Flatiron Building", "Designed by William Van Alen, the Chrysler Building briefly took the title of world's tallest building in 1930 with its secret 56-meter spire.", mcqIdx++));
  q.push(createMCQ("Which German design school founded by Walter Gropius in 1919 championed functionalism and the principle that form follows function?", "Bauhaus", "De Stijl", "Wiener Werkstatte", "The Bauhaus revolutionized modern architecture and industrial design by uniting fine art, craft, and industrial mass production.", mcqIdx++));
  q.push(createMCQ("Which Belgian architect pioneered the Art Nouveau style with whip-lash curves and open ironwork in the 1893 Hotel Tassel in Brussels?", "Victor Horta", "Henry van de Velde", "Hector Guimard", "Victor Horta integrated decorative ironwork, mosaics, and curved glass into unified biological aesthetic spaces.", mcqIdx++));
  q.push(createNumber("How many total commercial and observation floors comprise the main tower of the Empire State Building?", 102, "floors", "102 stories", "The Empire State Building contains 102 floors, with open-air observation decks on the 86th and 102nd floors visited by millions annually."));

  // Cycle 8: Modernism & The International Style
  q.push(createMCQ("Which Swiss-French modernist pioneer formulated the Five Points of Architecture and designed the iconic Villa Savoye near Paris?", "Le Corbusier", "Ludwig Mies van der Rohe", "Walter Gropius", "Le Corbusier's Five Points included pilotis (stilts), roof gardens, open floor plans, horizontal ribbon windows, and free facade design.", mcqIdx++));
  q.push(createMCQ("Which American master architect designed the iconic private residence Fallingwater in Pennsylvania, cantilevered over a natural waterfall?", "Frank Lloyd Wright", "Louis Sullivan", "Philip Johnson", "Frank Lloyd Wright's organic architecture sought harmony between human habitation and nature, using reinforced concrete trays over Bear Run.", mcqIdx++));
  q.push(createMCQ("Which German-American architect coined the aphorisms Less is more and God is in the details, designing the minimalist Seagram Building in New York?", "Ludwig Mies van der Rohe", "Marcel Breuer", "Richard Neutra", "Mies van der Rohe perfected the International Style glass-and-bronze corporate tower, leaving structural elements frankly expressed.", mcqIdx++));
  q.push(createMCQ("Which Brazilian architect designed the futuristic civic monuments of Brasilia, including the Cathedral of Brasilia and National Congress?", "Oscar Niemeyer", "Lucio Costa", "Roberto Burle Marx", "Niemeyer was renowned for sculptural reinforced concrete curves, stating he was attracted to free and sensual curves inspired by Brazil's mountains and women.", mcqIdx++));
  q.push(createMCQ("Which Frank Lloyd Wright masterpiece in New York City features a continuous spiraling ramp museum gallery wrapping around an open atrium?", "Solomon R. Guggenheim Museum", "Whitney Museum", "Metropolitan Museum", "Completed in 1959, the Guggenheim's inverted organic ziggurat allows visitors to take an elevator to the top and descend smoothly down the spiral ramp.", mcqIdx++));
  q.push(createNumber("In what year CE did Frank Lloyd Wright complete construction on his organic architectural masterpiece Fallingwater?", 1939, "CE", "circa 1939", "Fallingwater was constructed for the Kaufmann family in southwestern Pennsylvania between 1936 and 1939."));

  // Cycle 9: Postmodernism, Deconstructivism & High-Tech
  q.push(createMCQ("Which Canadian-American architect designed the titanium-clad, sculptural Guggenheim Museum in Bilbao, Spain, sparking the Bilbao Effect?", "Frank Gehry", "Daniel Libeskind", "Rem Koolhaas", "Gehry's 1997 undulating titanium structure transformed the decaying industrial port of Bilbao into a world-class global cultural destination.", mcqIdx++));
  q.push(createMCQ("Which Danish architect designed the world-famous Sydney Opera House, featuring iconic precast concrete shell roofs resembling billowing sails?", "Jorn Utzon", "Arne Jacobsen", "Alvar Aalto", "Utzon won the international design competition in 1957; the revolutionary vaulted roof shells required years of innovative spherical geometry calculations.", mcqIdx++));
  q.push(createMCQ("Which high-tech Parisian museum designed by Renzo Piano and Richard Rogers placed its mechanical services and colorful escalators on the exterior?", "Centre Pompidou", "Musee d'Orsay", "Fondation Louis Vuitton", "Opened in 1977, the Centre Pompidou exposed color-coded pipes (blue for air, green for water, yellow for electricity, red for circulation) on the outside.", mcqIdx++));
  q.push(createMCQ("Which British-Iraqi architect, known as the Queen of the Curve, became the first woman to win the prestigious Pritzker Architecture Prize in 2004?", "Zaha Hadid", "Kazuyo Sejima", "Yvonne Farrell", "Hadid pioneered parametric design with fluid, dynamic geometries in structures like the Guangzhou Opera House and London Aquatics Centre.", mcqIdx++));
  q.push(createMCQ("Which Chinese-American architect designed the glass-and-metal Louvre Pyramid in Paris and the National Gallery of Art East Building in Washington DC?", "I.M. Pei", "Maya Lin", "Kenzo Tange", "I.M. Pei's 1989 glass pyramid at the Louvre created a modern underground reception hall while contrasting boldly with historic French Renaissance facades.", mcqIdx++));
  q.push(createNumber("In what year CE was the iconic Sydney Opera House in Australia officially opened by Queen Elizabeth II?", 1973, "CE", "October 1973", "The Sydney Opera House was inaugurated on 20 October 1973, sixteen years after Jorn Utzon won the design competition in 1957."));

  // Cycle 10: Contemporary Megatall Skyscrapers
  q.push(createMCQ("In which United Arab Emirates city does the Burj Khalifa, the world's tallest building standing at 828 meters, soar into the sky?", "Dubai", "Abu Dhabi", "Doha", "Designed by architect Adrian Smith of Skidmore, Owings & Merrill, the Burj Khalifa features a Y-shaped stepped footprint inspired by the desert Hymenocallis flower.", mcqIdx++));
  q.push(createMCQ("Which 632-meter skyscraper in China features a twisting 120-degree cylindrical facade designed to reduce wind loads during typhoons?", "Shanghai Tower", "Ping An Finance Centre", "Canton Tower", "Designed by Gensler, Shanghai Tower possesses the world's highest observation deck and energy-efficient double-skin glass curtain walls.", mcqIdx++));
  q.push(createMCQ("Which Taiwanese skyscraper, shaped like a tiered bamboo stalk, held the title of world's tallest building from 2004 to 2010?", "Taipei 101", "Petronas Towers", "Jin Mao Tower", "Taipei 101 features a visible 660-tonne tuned mass golden pendulum damper suspended between the 87th and 92nd floors to withstand earthquakes.", mcqIdx++));
  q.push(createMCQ("Which Malaysian twin towers in Kuala Lumpur, designed by Cesar Pelli, are connected by a double-decker skybridge on the 41st and 42nd floors?", "Petronas Twin Towers", "Merdeka 118", "The Exchange 106", "The 451.9-meter Petronas Towers incorporate Islamic geometric motifs based on the Rub el Hizb eight-pointed star in their floor plates.", mcqIdx++));
  q.push(createMCQ("What is the primary skyscraper built on the World Trade Center site in Lower Manhattan, reaching a symbolic architectural height of 1,776 feet?", "One World Trade Center", "Two World Trade Center", "Three World Trade Center", "Designed by David Childs of SOM, One World Trade Center's 1,776-foot height directly commemorates the year of the United States Declaration of Independence.", mcqIdx++));
  q.push(createNumber("What is the exact architectural height in meters of the Burj Khalifa in Dubai, the tallest building on Earth?", 828, "meters", "2717 feet", "The Burj Khalifa stands at an extraordinary height of 828 meters (2,717 feet), containing 163 habitable floors."));

  return {
    id: "architecture-wonders-styles-60",
    theme: "Architecture: Gothic Cathedrals, Baroque & Modernism",
    title: "Architecture: Gothic Cathedrals, Baroque & Modernism",
    description: "A 60-question grand master assessment exploring classical antiquity, Byzantine domes, Gothic buttresses, Renaissance symmetry, Versailles Baroque, iron age landmarks, Bauhaus modernism, and contemporary megatall skyscrapers.",
    category: "Arts, Music, Literature & Philosophy",
    difficulty: "moderate",
    createdAt: "2026-08-27T00:00:00Z",
    questions: q
  };
}

// -------------------------------------------------------------
// QUIZ 6: world-languages-linguistics-60
// -------------------------------------------------------------
function getWorldLanguagesQuiz() {
  let mcqIdx = 0;
  const q = [];

  // Cycle 1: Indo-European Roots & Language Families
  q.push(createMCQ("Which reconstructed ancestral language is considered the common forebear of English, Spanish, Hindi, Russian, and Greek?", "Proto-Indo-European", "Proto-Afroasiatic", "Proto-Uralic", "Linguists reconstructed Proto-Indo-European through comparative phonological and lexical analysis of cognates across European and Asian tongues.", mcqIdx++));
  q.push(createMCQ("Which branch of the Indo-European family includes Italian, French, Spanish, Portuguese, and Romanian?", "Romance languages", "Germanic languages", "Slavic languages", "Romance languages evolved directly from Vulgar Latin spoken across the territories of the Western Roman Empire.", mcqIdx++));
  q.push(createMCQ("Which language family includes Hungarian, Finnish, and Estonian, standing distinctly apart from most neighboring European languages?", "Uralic family", "Altaic family", "Indo-European family", "The Finno-Ugric branch of the Uralic family features extensive agglutinative morphology and vowel harmony rather than grammatical gender.", mcqIdx++));
  q.push(createMCQ("Which sound law discovered in 1822 describes the systematic consonant shift separating Germanic languages from other Indo-European tongues?", "Grimm's Law", "Verner's Law", "Grassmann's Law", "Formulated by Jacob Grimm, the law showed how Proto-Indo-European voiceless stops (p, t, k) shifted into Germanic voiceless fricatives (f, th, h).", mcqIdx++));
  q.push(createMCQ("Which ancient classical language of India preserves the oldest liturgical texts of Hinduism and sacred grammar by Panini?", "Sanskrit", "Prakrit", "Pali", "Panini's 4th-century BCE Ashtadhyayi laid down 3,959 algebraic grammatical rules for Sanskrit, hailed as the earliest formal generative grammar.", mcqIdx++));
  q.push(createNumber("Approximately how many distinct living languages are actively spoken across the world today according to Ethnologue?", 7168, "living languages", "approx. 7100+ languages", "Linguistic databases such as Ethnologue document approximately 7,168 living spoken and signed languages across the globe."));

  // Cycle 2: Writing Systems & Ancient Scripts
  q.push(createMCQ("Which ancient writing system developed in southern Mesopotamia around 3400 BCE utilized wedge-shaped styluses on wet clay tablets?", "Cuneiform", "Hieratic", "Demotic", "Invented by the Sumerians to record grain inventories and trade, cuneiform evolved from pictograms into a sophisticated logo-syllabic script.", mcqIdx++));
  q.push(createMCQ("Which trading seafaring civilization of the Levant developed the first widespread phonemic alphabet that gave rise to Greek and Latin scripts?", "Phoenicians", "Hittites", "Philistines", "The 22-consonant Phoenician abjad simplified writing by abandoning hundreds of complex logograms in favor of one sign per consonant sound.", mcqIdx++));
  q.push(createMCQ("Which multilingual granite stele discovered in Egypt in 1799 allowed Jean-Francois Champollion to decipher Egyptian hieroglyphs?", "Rosetta Stone", "Behistun Inscription", "Palermo Stone", "The Rosetta Stone contained the same royal decree of Ptolemy V in three scripts: Ancient Greek, Demotic, and Egyptian Hieroglyphs.", mcqIdx++));
  q.push(createMCQ("Which ancient Minoan and Mycenaean script written on clay tablets was successfully deciphered by English architect Michael Ventris in 1952?", "Linear B", "Linear A", "Cretan Hieroglyphic", "Ventris demonstrated that Linear B recorded an early archaic dialect of Greek, four centuries before Homer.", mcqIdx++));
  q.push(createMCQ("What ancient writing medium made from the pith of a wetland reed plant was heavily used for scribal records throughout ancient Egypt and the Mediterranean?", "Papyrus", "Parchment", "Vellum", "Manufactured from the Cyperus papyrus plant along the Nile River, papyrus scrolls were the primary writing surface of classical antiquity.", mcqIdx++));
  q.push(createNumber("How many consonant letters made up the classical Phoenician abjad alphabet?", 22, "letters", "22 consonant characters", "The Phoenician alphabet consisted of exactly 22 consonant signs, written from right to left without vowel markers."));

  // Cycle 3: Alphabets, Abjads, Abugidas & Logograms
  q.push(createMCQ("What linguistic term describes a writing system such as Arabic or Hebrew in which only consonants are written while vowels are omitted or indicated with diacritics?", "Abjad", "Abugida", "Logogram", "Abjads require the reader to deduce appropriate vowel sounds based on grammatical knowledge and linguistic context.", mcqIdx++));
  q.push(createMCQ("What writing system, used for Hindi Devanagari and Thai, features consonant characters with an inherent vowel modified by diacritics?", "Abugida", "Alphabet", "Syllabary", "In an abugida (alphasyllabary), consonants have an default inherent vowel (like 'a') unless altered by a vowel diacritic mark.", mcqIdx++));
  q.push(createMCQ("Which writing system uses individual characters that represent whole words or meaningful morphemes, as in Chinese Hanzi characters?", "Logographic", "Alphabetic", "Phonetic", "Logograms convey meaning directly rather than phonemes alone, allowing speakers of mutually unintelligible dialects to read the same text.", mcqIdx++));
  q.push(createMCQ("Which script, derived from the Greek alphabet by disciples of Saints Cyril and Methodius, is used today for Russian, Ukrainian, and Bulgarian?", "Cyrillic script", "Glagolitic script", "Coptic script", "Developed in the First Bulgarian Empire in the 9th century CE, Cyrillic adapted Greek letters to Slavic phonology.", mcqIdx++));
  q.push(createMCQ("What writing system developed in ancient Greece was written alternating lines left-to-right and right-to-left, named as the ox turns?", "Boustrophedon", "Hieratic", "Cursive", "Boustrophedon mimics the path of an ox plowing a field, reversing text direction on every subsequent line.", mcqIdx++));
  q.push(createNumber("How many letters are in the modern standard Russian Cyrillic alphabet?", 33, "letters", "33 Cyrillic letters", "The standard modern Russian alphabet comprises exactly 33 letters: 10 vowels, 21 consonants, and 2 signs (hard sign and soft sign)."));

  // Cycle 4: The Latin Alphabet & English Evolution
  q.push(createMCQ("Which historical linguistic event between 1400 and 1700 fundamentally transformed the pronunciation of all English long vowels?", "The Great Vowel Shift", "The Norman Conquest", "The Grimm Shift", "The Great Vowel Shift raised and diphthongized Middle English long vowels, explaining why English spelling differs greatly from modern pronunciation.", mcqIdx++));
  q.push(createMCQ("Which Germanic language dialect spoken by Anglo-Saxons from the 5th century until around 1100 CE is preserved in the epic Beowulf?", "Old English", "Middle English", "Early Modern English", "Old English featured a complex four-case noun system, grammatical genders, and strong verb conjugations closely resembling Old Saxon.", mcqIdx++));
  q.push(createMCQ("Which landmark 1066 historical event introduced thousands of Anglo-Norman French vocabulary words into English government, law, and cuisine?", "The Norman Conquest", "The Hundred Years' War", "The Viking Invasion", "Following William the Conqueror's victory at Hastings, French became the language of the English court, creating English's vast dual Germanic-Romance vocabulary.", mcqIdx++));
  q.push(createMCQ("What is the term for a word borrowed from another language, such as 'tsunami' from Japanese or 'kindergarten' from German?", "Loanword", "Calque", "Cognate", "Loanwords enter languages through trade, conquest, or cultural exchange without translation of their individual morphemes.", mcqIdx++));
  q.push(createMCQ("What linguistic term describes words in different languages that share a common ancestral etymological origin, such as English 'father' and Latin 'pater'?", "Cognates", "Homophones", "Antonyms", "Cognates descend from the same parent word in an ancestral proto-language, retaining parallel phonological correspondences.", mcqIdx++));
  q.push(createNumber("How many letters make up the standard modern basic ISO Latin alphabet used in modern English?", 26, "letters", "26 standard letters", "The standard ISO basic Latin alphabet consists of exactly 26 letters, from A through Z."));

  // Cycle 5: East Asian Language Dynamics
  q.push(createMCQ("Which Korean monarch commissioned the creation of the scientific, highly phonetic Hangul alphabet in 1443 to increase public literacy?", "King Sejong the Great", "King Taejo", "King Yeongjo", "King Sejong designed Hangul letter shapes to mimic the physical configuration of the mouth, tongue, and throat when pronouncing each sound.", mcqIdx++));
  q.push(createMCQ("Which Japanese writing system consists of two phonetic syllabaries alongside adopted Chinese logographic characters (Kanji)?", "Hiragana and Katakana", "Hangul and Hanja", "Pinyin and Zhuyin", "Japanese combines native Hiragana for grammatical particles, Katakana for foreign loanwords, and Kanji for content root words.", mcqIdx++));
  q.push(createMCQ("How many distinct vocal tones are used in standard Mandarin Chinese to distinguish word meanings on a single syllable?", "Four tones", "Two tones", "Seven tones", "Standard Mandarin uses four pitched tones (high level, rising, dipping, falling) plus a neutral tone, where 'ma' can mean mother, hemp, horse, or scold.", mcqIdx++));
  q.push(createMCQ("Which Romanization system is the official international standard for transcribing Mandarin Chinese into the Latin alphabet?", "Pinyin", "Wade-Giles", "Yale Romanization", "Developed in China in the 1950s by linguist Zhou Youguang, Hanyu Pinyin uses Latin letters with tone accent marks.", mcqIdx++));
  q.push(createMCQ("Which Southeast Asian language adapted the Latin alphabet with extensive diacritics in the 17th century through Jesuit missionary Alexandre de Rhodes?", "Vietnamese", "Thai", "Khmer", "Known as Chu Quoc ngu, the Latin-based script replaced traditional Chinese-derived Chu Nom and became Vietnam's official national writing system.", mcqIdx++));
  q.push(createNumber("How many original basic alphabetic letters were introduced by King Sejong in the 1446 Hunminjeongeum text that created Hangul?", 28, "letters", "28 original letters", "The original Hangul system consisted of 28 letters (17 consonants and 11 vowels), four of which later became obsolete, leaving 24 in modern use."));

  // Cycle 6: Semitic & Afroasiatic Languages
  q.push(createMCQ("Which Semitic language underwent a historic modern revival from a purely liturgical sacred tongue into a living national vernacular led by Eliezer Ben-Yehuda?", "Hebrew", "Aramaic", "Amharic", "Eliezer Ben-Yehuda coined thousands of modern words for items like bicycles and ice cream, making Hebrew the only successful dead language spoken revival in history.", mcqIdx++));
  q.push(createMCQ("In Semitic languages like Arabic and Hebrew, words are fundamentally formed by slotting vowels into a root system consisting of how many consonants?", "Three consonants", "Two consonants", "Five consonants", "The triconsonantal root system (e.g. k-t-b related to writing in Arabic: kitab = book, kataba = he wrote, maktab = office) forms words through vowel templates.", mcqIdx++));
  q.push(createMCQ("Which Semitic language served as the primary everyday lingua franca of the Near East during the Persian Empire and was spoken by Jesus of Nazareth?", "Aramaic", "Akkadian", "Phoenician", "Aramaic was widely adopted as the diplomatic and trade language across the Middle East for over a millennium.", mcqIdx++));
  q.push(createMCQ("Which European island nation speaks a national language that is linguistically Semitic (descended from Siculo-Arabic) but written in the Latin alphabet?", "Malta", "Cyprus", "Crete", "Maltese is the only Semitic language that holds official national language status within the European Union and is written exclusively in Latin script.", mcqIdx++));
  q.push(createMCQ("What is the official working and national language of Ethiopia, written in the distinctive Ge'ez Fidel abugida script?", "Amharic", "Oromo", "Tigrinya", "Amharic is the second most widely spoken Semitic language in the world after Arabic, utilizing the ancient Ge'ez script.", mcqIdx++));
  q.push(createNumber("How many consonant letters make up the traditional Hebrew alphabet script?", 22, "letters", "22 Hebrew consonants", "The Hebrew alphabet consists of 22 consonant letters, five of which take special final forms (sofit) when written at the end of words."));

  // Cycle 7: Language Isolates & Mysterious Tongues
  q.push(createMCQ("Which language spoken in the Pyrenees region between Spain and France has no proven genealogical relationship to any other known language family?", "Basque", "Catalan", "Galician", "Basque (Euskara) is Western Europe's sole surviving language isolate, predating the arrival of Indo-European languages on the continent.", mcqIdx++));
  q.push(createMCQ("Which indigenous language of northern Japan, spoken by the native people of Hokkaido and Sakhalin, is an endangered language isolate?", "Ainu", "Ryukyuan", "Nivkh", "Ainu possesses distinct polysynthetic morphology and rich oral epic storytelling (Yukar) completely unrelated to Japanese.", mcqIdx++));
  q.push(createMCQ("Which extinct ancient language of pre-Roman central Italy was written in an alphabet derived from Greek but remains largely undeciphered in its grammar?", "Etruscan", "Oscan", "Umbrian", "Etruscan was non-Indo-European; though readable phonetically, its vocabulary and grammatical system remain isolated from other known language families.", mcqIdx++));
  q.push(createMCQ("Which Amazonian language spoken by an indigenous hunter-gatherer tribe has famously challenged universal grammar with claims of lacking numbers and recursive clauses?", "Piraha", "Yanomami", "Guarani", "Studied extensively by linguist Daniel Everett, Piraha features one of the smallest phoneme inventories and lacks grammatical recursion.", mcqIdx++));
  q.push(createMCQ("What linguistic classification is given to a natural language that has no demonstrable genetic relationship with any other living or dead language?", "Language isolate", "Pidgin", "Creole", "Language isolates represent the lone surviving members of otherwise extinct language families, like Basque, Korean (by some classifications), and Ainu.", mcqIdx++));
  q.push(createNumber("How many known living related sister languages belong to the same language family as Basque?", 0, "sister languages", "0 related living languages", "Basque is a complete language isolate with zero known surviving relative languages anywhere in the world."));

  // Cycle 8: Phonetics, Phonology & Grammar
  q.push(createMCQ("What international standardized alphabetic system was created by linguists in 1888 to accurately represent every sound of human speech?", "International Phonetic Alphabet", "NATO Phonetic Alphabet", "Universal Alphabet", "The International Phonetic Alphabet (IPA) provides a one-to-one symbol correspondence for every distinct phone across all world languages.", mcqIdx++));
  q.push(createMCQ("Which family of southern African languages, including Xhosa and Zulu, is famous for incorporating distinctive non-pulmonic click consonants?", "Khoisan and Bantu languages", "Niger-Congo isolates", "Nilo-Saharan languages", "Click sounds are produced by creating suction with the tongue in the oral cavity, representing some of the rarest consonants in human speech.", mcqIdx++));
  q.push(createMCQ("What morphological language type, exemplified by Turkish, Hungarian, and Swahili, builds complex words by stringing together distinct unvarying affixes?", "Agglutinative", "Isolating", "Fusional", "In agglutinative languages, each morpheme cleanly represents a single grammatical function (e.g. Turkish: ev = house, ev-ler = houses, ev-ler-im = my houses).", mcqIdx++));
  q.push(createMCQ("What is the term for the smallest unit of sound in a language that can distinguish one word from another, such as /p/ and /b/ in 'pat' and 'bat'?", "Phoneme", "Morpheme", "Grapheme", "Changing a single phoneme changes the semantic meaning of a word in minimal pairs.", mcqIdx++));
  q.push(createMCQ("What linguistic phenomenon occurs when a speaker alternates between two or more languages or dialects within a single conversation?", "Code-switching", "Diglossia", "Pidginization", "Code-switching is a natural and sophisticated communicative strategy used by multilingual speakers depending on social context and conversational nuance.", mcqIdx++));
  q.push(createNumber("How many primary official consonant symbols are defined on the standard chart of the International Phonetic Alphabet (IPA)?", 107, "symbols", "approx. 107 core symbols", "The standard IPA chart defines 107 primary symbols representing consonants and vowels, augmented by various diacritics and suprasegmentals."));

  // Cycle 9: Constructed & Universal Languages
  q.push(createMCQ("Which Polish ophthalmologist created the international auxiliary language Esperanto in 1887 under the pseudonym Doktoro Esperanto?", "L.L. Zamenhof", "Volapuk Schleyer", "Alexander Gode", "Ludwik Lejzer Zamenhof designed Esperanto with regular grammar and European roots to foster international peace and mutual understanding.", mcqIdx++));
  q.push(createMCQ("Which constructed warrior language with a guttural phonology was created by linguist Marc Okrand for the Star Trek science fiction franchise?", "Klingon", "Elvish", "Dothraki", "Okrand developed Klingon (tlhIngan Hol) with an unusual Object-Verb-Subject (OVS) word order to give it an alien grammatical structure.", mcqIdx++));
  q.push(createMCQ("Which Oxford philologist and author constructed the Elvish languages Quenya and Sindarin before writing The Lord of the Rings?", "J.R.R. Tolkien", "C.S. Lewis", "Philip Pullman", "Tolkien famously stated that his fantasy stories were written to provide a mythological world for his constructed languages, rather than vice versa.", mcqIdx++));
  q.push(createMCQ("Which philosophical minimalist constructed language created by Sonja Lang in 2001 utilizes only around 120 basic root words?", "Toki Pona", "Lojban", "Ithkuil", "Toki Pona was designed around Taoist simplicity, expressing complex thoughts through combinations of basic universal concepts.", mcqIdx++));
  q.push(createMCQ("Which 19th-century priest invented Volapuk, one of the earliest constructed international auxiliary languages, before Esperanto surpassed it?", "Johann Martin Schleyer", "Charles K. Bliss", "John Wilkins", "Schleyer claimed God instructed him in a dream to create an international tongue, publishing Volapuk in 1879.", mcqIdx++));
  q.push(createNumber("How many core root words were in the original vocabulary of the minimalist constructed language Toki Pona?", 120, "words", "120 original words", "Sonja Lang's original Toki Pona specification published in 2001 contained exactly 120 essential root words."));

  // Cycle 10: Linguistic Records & Endangered Tongues
  q.push(createMCQ("Which language has the largest number of native (first-language) speakers in the world, with over 900 million native speakers?", "Mandarin Chinese", "Spanish", "English", "Mandarin Chinese leads all global languages in native primary speakers, predominantly spoken across mainland China, Taiwan, and Singapore.", mcqIdx++));
  q.push(createMCQ("Which South American nation shares the record for having 37 official languages recognized in its national constitution alongside Spanish?", "Bolivia", "Peru", "Ecuador", "Bolivia's 2009 constitution officially recognizes Spanish and 36 indigenous indigenous languages including Quechua, Aymara, and Guarani.", mcqIdx++));
  q.push(createMCQ("Which island nation in the southwestern Pacific has the highest linguistic density in the world, with over 800 indigenous languages spoken?", "Papua New Guinea", "Madagascar", "New Zealand", "Papua New Guinea's rugged mountain valleys isolated human communities for millennia, fostering more than 840 distinct languages.", mcqIdx++));
  q.push(createMCQ("What is the linguistic term for a simplified contact language developed between two groups without a shared tongue, which later evolves into a native creole?", "Pidgin", "Patois", "Dialect", "When children acquire a pidgin as their primary first language and expand its grammar, it becomes classified as a fully developed creole.", mcqIdx++));
  q.push(createMCQ("Approximately what percentage of the world's remaining languages are estimated by UNESCO to be endangered of extinction by 2100?", "Fifty percent", "Ten percent", "Ninety percent", "Linguists estimate that roughly half (50%) of all currently spoken languages may fall silent by the end of the 21st century without active revitalization.", mcqIdx++));
  q.push(createNumber("How many official national languages are recognized in the constitution of South Africa following the addition of Sign Language in 2023?", 12, "official languages", "12 recognized languages", "South Africa recognizes 12 official languages: Zulu, Xhosa, Afrikaans, English, Sepedi, Setswana, Sesotho, Xitsonga, siSwati, Tshivenda, Ndebele, and SASL."));

  return {
    id: "world-languages-linguistics-60",
    theme: "Languages & Linguistics: Alphabets, Etymology & Scripts",
    title: "Languages & Linguistics: Alphabets, Etymology & Scripts",
    description: "A 60-question comprehensive linguistic exploration into Proto-Indo-European, ancient cuneiform and hieroglyphs, alphabets and abjads, the evolution of English, Hangul, Hebrew revival, language isolates, phonetics, Esperanto, and world linguistic records.",
    category: "Arts, Music, Literature & Philosophy",
    difficulty: "moderate",
    createdAt: "2026-08-27T00:00:00Z",
    questions: q
  };
}

// -------------------------------------------------------------
// QUIZ 7: philosophy-great-thinkers-60
// -------------------------------------------------------------
function getPhilosophyQuiz() {
  let mcqIdx = 0;
  const q = [];

  // Cycle 1: Pre-Socratics & Early Metaphysics
  q.push(createMCQ("Which ancient thinker from Miletus is traditionally hailed as the first Western philosopher, proposing that water is the fundamental origin of all things?", "Thales", "Anaximander", "Anaximenes", "Thales of Miletus broke away from mythological explanations of the cosmos, initiating rational natural philosophy around 600 BCE.", mcqIdx++));
  q.push(createMCQ("Which Greek philosopher famously asserted that reality is in perpetual flux and fire, stating that one cannot step into the same river twice?", "Heraclitus", "Parmenides", "Empedocles", "Heraclitus of Ephesus taught that universal logos governs the perpetual unity and conflict of opposing cosmic forces.", mcqIdx++));
  q.push(createMCQ("Which Eleatic philosopher argued the radical opposite of Heraclitus, maintaining that change and motion are illusions and that Being is one and unchangeable?", "Parmenides", "Zeno of Elea", "Xenophanes", "Parmenides established rationalist ontology in his poem On Nature, declaring that what is cannot come from what is not.", mcqIdx++));
  q.push(createMCQ("Which ancient Greek philosopher and mathematician founded a mystical brotherhood in Croton that believed numbers constituted the true essence of reality?", "Pythagoras", "Archimedes", "Euclid", "Pythagoreans discovered the mathematical ratios behind musical harmony and formulated early theories of the transmigration of souls.", mcqIdx++));
  q.push(createMCQ("Which Greek thinker developed atomism, proposing that the entire universe consists solely of indivisible particles (atoms) moving through empty void?", "Democritus", "Leucippus", "Epicurus", "Democritus was known as The Laughing Philosopher and provided a purely materialistic foundation for physics without divine intervention.", mcqIdx++));
  q.push(createNumber("In what year BCE was the landmark philosopher Socrates condemned to death by drinking hemlock in democratic Athens?", 399, "BCE", "399 BCE trial", "Socrates was tried, convicted of impiety and corrupting the youth, and executed in Athens in 399 BCE at age 70."));

  // Cycle 2: The Athenian Golden Age
  q.push(createMCQ("What method of cooperative argumentative dialogue did Socrates use to draw out underlying assumptions through relentless questioning?", "Socratic method", "Dialectical materialism", "Scholastic disputation", "The Socratic method (elenchus) exposes contradictions in a student's definitions, leading them to acknowledge their own ignorance.", mcqIdx++));
  q.push(createMCQ("In Plato's Republic, which famous philosophical allegory illustrates human liberation from the illusions of sensory perception to the light of truth?", "Allegory of the Cave", "Ring of Gyges", "Myth of Er", "Plato describes prisoners chained in a dark cave seeing only projected shadows on a wall, mistaking them for true reality.", mcqIdx++));
  q.push(createMCQ("What metaphysical theory developed by Plato asserts that the physical world is merely a flawed shadow of non-physical, perfect, eternal Forms or Ideas?", "Theory of Forms", "Nominalism", "Atomism", "Plato's Theory of Forms (Eidos) posits that abstract concepts like Justice, Beauty, and the Good exist in a higher realm of objective reality.", mcqIdx++));
  q.push(createMCQ("Which student of Plato tutored Alexander the Great and founded the Lyceum, writing foundational treatises on logic, ethics, biology, and politics?", "Aristotle", "Theophrastus", "Speusippus", "Aristotle developed syllogistic logic and empirical observation, shaping Western scientific thought for nearly two millennia.", mcqIdx++));
  q.push(createMCQ("In the Nicomachean Ethics, what central concept did Aristotle identify as the ultimate goal of human existence, translated as human flourishing or happiness?", "Eudaimonia", "Ataraxia", "Apatheia", "Aristotle argued that eudaimonia is achieved by cultivating moral and intellectual virtues according to the Golden Mean between extremes.", mcqIdx++));
  q.push(createNumber("How many distinct books comprise Marcus Aurelius's classic Stoic journal Meditations?", 12, "books", "12 personal books", "Marcus Aurelius wrote his 12 books of Meditations in Greek as private personal reflections on duty and resilience while campaigning on the Danube."));

  // Cycle 3: Hellenistic Schools of Life
  q.push(createMCQ("Which Hellenistic philosophical school founded by Zeno of Citium taught that virtue is the only good and that emotions should be governed by reason?", "Stoicism", "Epicureanism", "Cynicism", "Stoicism was practiced by Greek and Roman thinkers including Seneca, Epictetus, and Emperor Marcus Aurelius to maintain inner tranquility.", mcqIdx++));
  q.push(createMCQ("Which Greek philosopher taught in his Athens garden that the highest good is ataraxia (tranquility) and freedom from fear, through modest pleasures and friendship?", "Epicurus", "Metrodorus", "Lucretius", "Epicurus argued that death is nothing to us and that natural, simple desires eliminate physical pain and mental anxiety.", mcqIdx++));
  q.push(createMCQ("Which notorious Cynic philosopher lived in a ceramic storage jar in the Athens marketplace, carrying a lamp in daylight looking for an honest man?", "Diogenes of Sinope", "Antisthenes", "Crates of Thebes", "Diogenes rejected social conventions, luxury, and hypocrisy, famously telling Alexander the Great to stand out of his sunlight.", mcqIdx++));
  q.push(createMCQ("Which freed Greek slave became a major Stoic philosopher in Rome, whose teachings on self-mastery were recorded by Arrian in the Discourses and Enchiridion?", "Epictetus", "Seneca", "Musonius Rufus", "Epictetus taught that freedom comes from distinguishing what is within our control (our thoughts and actions) from what is not.", mcqIdx++));
  q.push(createMCQ("What ancient Greek philosophical school founded by Pyrrho of Elis advocated epoché (suspension of judgment) to achieve mental peace?", "Pyrrhonism", "Hedonism", "Neoplatonism", "Skeptics held that because sensory perceptions and dogmatic claims are uncertain, withholding belief frees the mind from turmoil.", mcqIdx++));
  q.push(createNumber("How many steps make up the Noble Eightfold Path in Buddhist philosophy to end suffering and achieve liberation?", 8, "steps", "The Eightfold Path", "The Buddha's Noble Eightfold Path consists of Right View, Resolve, Speech, Action, Livelihood, Effort, Mindfulness, and Concentration."));

  // Cycle 4: Eastern Philosophical Masters
  q.push(createMCQ("Which Chinese sage emphasized social harmony, filial piety (xiao), and benevolence (ren) in teachings compiled in the Analects?", "Confucius", "Mencius", "Xunzi", "Confucius (Kong Fuzi) shaped Chinese moral education, governance, and family ethics for more than two millennia.", mcqIdx++));
  q.push(createMCQ("Which legendary Chinese philosopher is revered as the author of the Dao De Jing and the founder of philosophical Daoism?", "Laozi", "Zhuangzi", "Han Feizi", "Laozi taught the principle of Wu Wei (effortless action) and living in spontaneous harmony with the natural flow of the Dao.", mcqIdx++));
  q.push(createMCQ("Which Daoist philosopher wrote the famous philosophical parable questioning whether he was a man dreaming he was a butterfly, or a butterfly dreaming he was a man?", "Zhuangzi", "Liezi", "Huainanzi", "Zhuangzi used wit, allegories, and paradoxes to challenge human epistemological certainty and rigid distinctions.", mcqIdx++));
  q.push(createMCQ("What Chinese philosophical concept describes the harmonious balance of complementary, interconnected cosmic forces in nature?", "Yin and Yang", "Wu Wei", "Li and Qi", "Yin represents the dark, receptive, and passive principle, while Yang represents the bright, active, and creative principle.", mcqIdx++));
  q.push(createMCQ("Which ancient Indian prince attained supreme enlightenment under the Bodhi Tree and formulated the Four Noble Truths concerning the nature of suffering?", "Siddhartha Gautama", "Mahavira", "Adi Shankara", "The Buddha taught that suffering (dukkha) arises from attachment (tanha) and can be extinguished through the Middle Way.", mcqIdx++));
  q.push(createNumber("How many logical arguments (The Five Ways or Quinque Viae) did Thomas Aquinas formulate for the existence of God in his Summa Theologiae?", 5, "arguments", "The Five Ways", "Aquinas formulated Five Ways: arguments from motion, efficient cause, contingency, degree of perfection, and teleological design."));

  // Cycle 5: Medieval Scholasticism & Islamic Golden Age
  q.push(createMCQ("Which 13th-century Dominican friar synthesized Christian theology with Aristotelian philosophy in his monumental Summa Theologiae?", "Thomas Aquinas", "Duns Scotus", "William of Ockham", "Declared the Doctor Angelicus, Saint Thomas Aquinas harmonized faith and reason, establishing the foundation of Thomist philosophy.", mcqIdx++));
  q.push(createMCQ("Which Persian polymath of the Islamic Golden Age wrote The Book of Healing and proposed the famous Floating Man thought experiment on human self-awareness?", "Avicenna", "Al-Farabi", "Al-Kindi", "Avicenna (Ibn Sina) argued that a human suspended in empty space with no sensory input would still possess direct conscious awareness of their own existence.", mcqIdx++));
  q.push(createMCQ("Which Andalusian philosopher from Cordoba, known in the West as The Commentator, wrote master commentaries on Aristotle and defended philosophy in The Incoherence of the Incoherence?", "Averroes", "Ibn Tufayl", "Ibn Arabi", "Averroes (Ibn Rushd) exerted profound influence on Christian Scholasticism and European Renaissance humanism.", mcqIdx++));
  q.push(createMCQ("Which 14th-century English Franciscan friar formulated the methodological principle that entities should not be multiplied beyond necessity?", "William of Ockham", "Roger Bacon", "John Buridan", "Occam's Razor states that when presented with competing hypotheses, the simplest explanation requiring the fewest assumptions should be preferred.", mcqIdx++));
  q.push(createMCQ("Which Jewish philosopher from Cordoba authored The Guide for the Perplexed in Judeo-Arabic to reconcile the Torah with Aristotelian philosophy?", "Moses Maimonides", "Yehuda Halevi", "Baruch Spinoza", "Maimonides was a royal physician in Cairo whose philosophical and legal works remain central to Jewish rabbinic thought.", mcqIdx++));
  q.push(createNumber("How many individual Meditations comprise Rene Descartes's 1641 foundational philosophical treatise Meditations on First Philosophy?", 6, "meditations", "6 formal meditations", "Descartes divided his classic work into six meditations, systematically doubting all sensory beliefs before proving his own existence and God."));

  // Cycle 6: The Rationalists vs. The Empiricists
  q.push(createMCQ("Which French philosopher founded modern Western philosophy with his method of radical doubt, formulating the famous maxim Cogito, ergo sum (I think, therefore I am)?", "Rene Descartes", "Blaise Pascal", "Nicolas Malebranche", "Descartes used foundational doubt to find an indubitable truth: the very act of doubting proves the existence of a thinking mind.", mcqIdx++));
  q.push(createMCQ("Which 17th-century Jewish-Dutch philosopher developed a revolutionary pantheistic metaphysics in his Ethics, declaring that God and Nature are one and the same substance?", "Baruch Spinoza", "Gottfried Wilhelm Leibniz", "Thomas Hobbes", "Spinoza was excommunicated from the Amsterdam Jewish community for his radical identification of Deus sive Natura (God or Nature).", mcqIdx++));
  q.push(createMCQ("Which English philosopher argued in An Essay Concerning Human Understanding that the human mind begins at birth as a blank slate (tabula rasa)?", "John Locke", "George Berkeley", "David Hume", "Locke established British empiricism, asserting that all knowledge, concepts, and ideas originate entirely from sensory experience and reflection.", mcqIdx++));
  q.push(createMCQ("Which Scottish Enlightenment philosopher challenged rationalism by highlighting the Problem of Induction and arguing that reason is the slave of the passions?", "David Hume", "Adam Smith", "Thomas Reid", "Hume showed that we cannot logically prove the sun will rise tomorrow based purely on past observation without assuming the uniformity of nature.", mcqIdx++));
  q.push(createMCQ("Which English political theorist wrote Leviathan in 1651, describing the natural state of humanity without government as solitary, poor, nasty, brutish, and short?", "Thomas Hobbes", "Jean-Jacques Rousseau", "John Stuart Mill", "Hobbes argued that individuals enter into a social contract, surrendering absolute liberty to an absolute sovereign in exchange for security and order.", mcqIdx++));
  q.push(createNumber("In what year CE did Immanuel Kant publish his landmark masterwork Critique of Pure Reason in Riga?", 1781, "CE", "1781 first edition", "Kant published the first edition (A edition) of Kritik der reinen Vernunft in 1781, revolutionizing epistemology and metaphysics."));

  // Cycle 7: The Enlightenment & German Idealism
  q.push(createMCQ("Which German philosopher synthesized rationalism and empiricism through transcendental idealism, formulating the Categorical Imperative in moral philosophy?", "Immanuel Kant", "G.W.F. Hegel", "Johann Gottlieb Fichte", "Kant argued that we perceive phenomena structured by innate mental categories of space and time, but cannot know the ding an sich (thing-in-itself).", mcqIdx++));
  q.push(createMCQ("Which Genevan philosopher declared in The Social Contract that Man is born free, and everywhere he is in chains?", "Jean-Jacques Rousseau", "Voltaire", "Denis Diderot", "Rousseau advocated for popular sovereignty and governance guided by the General Will, deeply influencing the French Revolution.", mcqIdx++));
  q.push(createMCQ("Which German idealist philosopher developed the dialectical method of history progressing through thesis, antithesis, and synthesis toward absolute spirit?", "Georg Wilhelm Friedrich Hegel", "Friedrich Schelling", "Arthur Schopenhauer", "Hegel's Phenomenology of Spirit viewed human history as the dialectical self-realization of Reason and freedom over successive eras.", mcqIdx++));
  q.push(createMCQ("Which French Enlightenment satirist wrote the novella Candide to mock Leibniz's optimistic doctrine that this is the best of all possible worlds?", "Voltaire", "Montesquieu", "Marquis de Condorcet", "Voltaire exposed the absurdities of blind optimism in the face of human cruelty and natural disasters, concluding that we must cultivate our garden.", mcqIdx++));
  q.push(createMCQ("What is the term for Kant's supreme moral principle, which commands that you act only according to maxims you could will to become a universal law?", "Categorical Imperative", "Utilitarian calculus", "Golden Mean", "Kant's deontological ethics holds that moral duties are unconditional and that human beings must always be treated as ends in themselves, never merely as means.", mcqIdx++));
  q.push(createNumber("In what year CE did Karl Marx and Friedrich Engels publish The Communist Manifesto in London?", 1848, "CE", "February 1848", "The Communist Manifesto was published in German on 21 February 1848, coinciding with the outbreak of the revolutions of 1848 across Europe."));

  // Cycle 8: Utilitarianism, Dialectics & 19th Century Rebels
  q.push(createMCQ("Which British philosopher formulated classical Utilitarianism, asserting that the right action produces the greatest happiness for the greatest number?", "Jeremy Bentham", "John Stuart Mill", "Henry Sidgwick", "Bentham proposed the felicific calculus to quantitatively measure pleasure and pain, advocating legal and penal reform in Victorian Britain.", mcqIdx++));
  q.push(createMCQ("Which English philosopher refined utilitarianism in On Liberty and Utilitarianism, distinguishing between higher intellectual and lower bodily pleasures?", "John Stuart Mill", "Herbert Spencer", "Bertrand Russell", "Mill formulated the famous Harm Principle: the only purpose for which power can be rightfully exercised over any individual against his will is to prevent harm to others.", mcqIdx++));
  q.push(createMCQ("Which German philosopher and economist co-authored Das Kapital, arguing that all human history is the history of class struggles driven by material conditions?", "Karl Marx", "Friedrich Engels", "Max Weber", "Marx developed historical materialism, predicting that internal contradictions in capitalism would lead to proletarian revolution and a classless society.", mcqIdx++));
  q.push(createMCQ("Which German pessimist philosopher wrote The World as Will and Representation, influenced by the Upanishads to view human life as endless striving and suffering?", "Arthur Schopenhauer", "Eduard von Hartmann", "Ludwig Feuerbach", "Schopenhauer argued that the blind, insatiable Will to Live drives all reality, with aesthetic contemplation of art and asceticism offering rare escape.", mcqIdx++));
  q.push(createMCQ("Which Danish philosopher is recognized as the Father of Christian Existentialism, writing Fear and Trembling under pseudonyms about the leap of faith?", "Soren Kierkegaard", "Henrik Ibsen", "Hans Christian Andersen", "Kierkegaard examined human anxiety (angst) and the subjective choice of the individual standing before God without rational guarantees.", mcqIdx++));
  q.push(createNumber("How many parts make up Friedrich Nietzsche's philosophical work Thus Spoke Zarathustra (Also sprach Zarathustra)?", 4, "parts", "4 narrative parts", "Nietzsche wrote Thus Spoke Zarathustra in four distinct parts between 1883 and 1885, using biblical poetic style to proclaim the Ubermensch."));

  // Cycle 9: Friedrich Nietzsche & Existential Revolt
  q.push(createMCQ("Which provocative German philosopher proclaimed the Death of God in The Gay Science and advocated the creation of new values through the Ubermensch (Overman)?", "Friedrich Nietzsche", "Max Stirner", "Martin Heidegger", "Nietzsche warned that the decline of Christian metaphysical belief would lead to nihilism, requiring humanity to forge life-affirming values.", mcqIdx++));
  q.push(createMCQ("What philosophical concept did Nietzsche propose as a supreme psychological test of life affirmation, asking if you would willingly live your identical life over and over for eternity?", "Eternal Recurrence", "Amor Fati", "Will to Power", "Nietzsche considered Eternal Recurrence the heaviest burden, requiring unconditional love of one's fate (Amor Fati) to embrace joyfully.", mcqIdx++));
  q.push(createMCQ("In On the Genealogy of Morals, what two moral systems did Nietzsche contrast, critiquing Christian morality as a slave revolt against noble values?", "Master morality and Slave morality", "Deontology and Consequentialism", "Stoicism and Epicureanism", "Nietzsche argued that slave morality inverted ancient noble values (strength, excellence) into virtues of meekness, pity, and ressentiment.", mcqIdx++));
  q.push(createMCQ("What psychological drive did Nietzsche identify in Beyond Good and Evil as the fundamental driving engine of all human ambition and natural striving?", "Will to Power", "Will to Pleasure", "Will to Meaning", "Nietzsche viewed the Will to Power (Der Wille zur Macht) not merely as political dominance, but as the impulse to overcome oneself and create greatness.", mcqIdx++));
  q.push(createMCQ("In which Swiss mountain village in the Upper Engadin valley did Nietzsche spend his most productive summers conceiving Zarathustra near Lake Silvaplana?", "Sils Maria", "Zermatt", "Davos", "A pyramid-shaped boulder by Lake Silvaplana inspired Nietzsche's sudden revelation of the Eternal Recurrence in August 1881.", mcqIdx++));
  q.push(createNumber("In what year CE did Albert Camus publish his classic existential philosophical essay The Myth of Sisyphus in Paris?", 1942, "CE", "1942 publication", "Camus published Le Mythe de Sisyphe in 1942 during the Nazi occupation of France, opening with the question of suicide and the Absurd."));

  // Cycle 10: 20th Century Existentialism & Analytic Thought
  q.push(createMCQ("Which French existentialist philosopher declared in Being and Nothingness that existence precedes essence and that humanity is condemned to be free?", "Jean-Paul Sartre", "Maurice Merleau-Ponty", "Gabriel Marcel", "Sartre argued that humans possess no predetermined nature or divine blueprint; we define our essence entirely through our conscious choices.", mcqIdx++));
  q.push(createMCQ("Which French philosopher and feminist pioneer wrote The Second Sex in 1949, famously stating, One is not born, but rather becomes, a woman?", "Simone de Beauvoir", "Helene Cixous", "Luce Irigaray", "Beauvoir established foundational feminist existentialism, analyzing how patriarchal culture constructs womanhood as the inferior Other.", mcqIdx++));
  q.push(createMCQ("Which Austrian-British philosopher published the Tractatus Logico-Philosophicus in 1921, concluding: Whereof one cannot speak, thereof one must be silent?", "Ludwig Wittgenstein", "Karl Popper", "Rudolf Carnap", "Wittgenstein investigated the logical limits of language and meaning, later transforming philosophy with his concept of language games in Philosophical Investigations.", mcqIdx++));
  q.push(createMCQ("Which British philosopher and logician co-wrote Principia Mathematica with Alfred North Whitehead and won the 1950 Nobel Prize in Literature?", "Bertrand Russell", "G.E. Moore", "A.J. Ayer", "Russell was a leader of the analytic revolution, known for Russell's Paradox in set theory and passionate public pacifism.", mcqIdx++));
  q.push(createMCQ("In The Myth of Sisyphus, how did Albert Camus conclude his reflection on the absurd hero condemned to roll a boulder up a mountain for eternity?", "One must imagine Sisyphus happy", "Sisyphus must abandon the rock", "Sisyphus is defeated by the gods", "Camus argued that Sisyphus triumphs over his pointless fate through conscious defiance, finding meaning and joy in the struggle itself.", mcqIdx++));
  q.push(createNumber("How many numbered propositions form the core logical skeleton of Ludwig Wittgenstein's 1921 masterwork Tractatus Logico-Philosophicus?", 7, "propositions", "7 major propositions", "The Tractatus is organized around exactly seven central numbered propositions, detailing the logical relationship between language and reality."));

  return {
    id: "philosophy-great-thinkers-60",
    theme: "Philosophy: Socratic Dialogue to Modern Existentialism",
    title: "Philosophy: Socratic Dialogue to Modern Existentialism",
    description: "A 60-question grand master assessment exploring Pre-Socratic metaphysics, Socrates, Plato's Republic, Aristotle, Stoicism, Eastern philosophy, medieval scholasticism, Descartes, Kant, Nietzsche, and 20th-century existentialism.",
    category: "Arts, Music, Literature & Philosophy",
    difficulty: "moderate",
    createdAt: "2026-08-27T00:00:00Z",
    questions: q
  };
}

// -------------------------------------------------------------
// QUIZ 8: culinary-arts-world-cuisines-60
// -------------------------------------------------------------
function getCulinaryArtsQuiz() {
  let mcqIdx = 0;
  const q = [];

  // Cycle 1: French Classical Haute Cuisine
  q.push(createMCQ("Which legendary French chef codified the five French Mother Sauces and instituted the modern kitchen brigade system (Brigade de cuisine)?", "Auguste Escoffier", "Marie-Antoine Careme", "Paul Bocuse", "Auguste Escoffier modernized professional restaurant kitchens at the Savoy and Ritz hotels, authoring the landmark culinary reference Le Guide Culinaire.", mcqIdx++));
  q.push(createMCQ("Which French mother sauce consists of a rich white sauce made from milk thickened with a white roux (equal parts butter and flour)?", "Bechamel", "Veloute", "Espagnole", "Bechamel serves as the base for many classic derivative sauces, including Mornay sauce and cream sauces.", mcqIdx++));
  q.push(createMCQ("What traditional aromatic French flavor base consists of two parts diced onions, one part carrots, and one part celery gently cooked in butter?", "Mirepoix", "Bouquet garni", "Soffritto", "Mirepoix provides the essential foundational aromatic background for classic French stocks, soups, stews, and braises.", mcqIdx++));
  q.push(createMCQ("What French cooking technique involves vacuum-sealing food in a plastic pouch and cooking it in a precisely temperature-controlled water bath?", "Sous-vide", "Braising", "Confit", "Sous-vide (under vacuum) ensures uniform, edge-to-edge cooking at precise temperatures without moisture or flavor loss.", mcqIdx++));
  q.push(createMCQ("What tire company originally launched the prestigious red gastronomic restaurant guide in 1900 to encourage French road travel and dining?", "Michelin", "Pirelli", "Goodyear", "The Michelin Guide introduced its three-star rating system in 1931, where three stars signifies exceptional cuisine worth a special journey.", mcqIdx++));
  q.push(createNumber("How many classical Mother Sauces did chef Auguste Escoffier establish in French haute cuisine?", 5, "mother sauces", "The 5 Mother Sauces", "Escoffier defined five foundational mother sauces: Bechamel, Veloute, Espagnole, Sauce Tomat, and Hollandaise."));

  // Cycle 2: Italian Regional Gastronomy
  q.push(createMCQ("Which Italian city is the historical birthplace of authentic Neapolitan pizza, protected by UNESCO intangible cultural heritage status?", "Naples", "Rome", "Florence", "Associazione Verace Pizza Napoletana requires San Marzano tomatoes, fresh Mozzarella di Bufala, and wood-fired baking at 485 degrees Celsius for 60 to 90 seconds.", mcqIdx++));
  q.push(createMCQ("Which protected Italian hard cheese from Emilia-Romagna is nicknamed The King of Cheeses, produced from unpasteurized cow's milk?", "Parmigiano-Reggiano", "Pecorino Romano", "Grana Padano", "Authentic PDO Parmigiano-Reggiano must be aged for a minimum of 12 months, inspected with a special silver hammer, and pin-stamped along its rind.", mcqIdx++));
  q.push(createMCQ("What Italian culinary term describes pasta cooked to be firm to the bite rather than mushy or overcooked?", "Al dente", "Al forno", "All'arrabbiata", "Al dente (to the tooth) preserves optimal pasta texture and maintains a lower glycemic index compared to overcooked pasta.", mcqIdx++));
  q.push(createMCQ("In which northern Italian province is Traditional Balsamic Vinegar (Aceto Balsamico Tradizionale) aged for a minimum of 12 years in wooden barrels?", "Modena", "Bologna", "Parma", "Made from simmered Trebbiano and Lambrusco grape must, traditional balsamic vinegar passes through a battery of aging wooden casks.", mcqIdx++));
  q.push(createMCQ("What Italian variety of high-starch, short-grain rice from the Po Valley is the gold standard for creating creamy authentic risotto?", "Arborio and Carnaroli", "Basmati", "Jasmine", "Carnaroli and Arborio rice release amylopectin starch during continuous stirring, creating a luxurious creamy emulsion without adding cream.", mcqIdx++));
  q.push(createNumber("What is the minimum required aging period in months for authentic certified PDO Parmigiano-Reggiano cheese?", 12, "months", "12 months minimum", "Consorzio del Formaggio Parmigiano-Reggiano mandates that every cheese wheel must age for at least 12 full months before inspection."));

  // Cycle 3: Japanese Culinary Art & Sushi
  q.push(createMCQ("Which fifth basic taste was identified in 1908 by Japanese chemist Kikunae Ikeda, describing a savory, meaty flavor triggered by glutamate?", "Umami", "Kokumi", "Kombu", "Ikeda extracted glutamic acid from kombu seaweed kelp dashi broth, isolating the taste that complements sweet, salty, sour, and bitter.", mcqIdx++));
  q.push(createMCQ("Which Japanese culinary style consists of an elaborate, highly formal multi-course traditional dinner showcasing seasonal ingredients and exquisite plating?", "Kaiseki", "Izakaya", "Teppanyaki", "Kaiseki originated in conjunction with the traditional Japanese tea ceremony, emphasizing aesthetic balance, harmony, and seasonal nature.", mcqIdx++));
  q.push(createMCQ("What pungent green rhizome plant is grated with a sharkskin grater (oroshigane) to serve as authentic condiment with sushi?", "Wasabi", "Horseradish", "Daikon", "True wasabi (Wasabia japonica) is notoriously difficult to cultivate in clean mountain spring water, providing a sharp aroma that clears the nasal passage.", mcqIdx++));
  q.push(createMCQ("Which Japanese beef from specifically bred Kuroge cattle is world-renowned for its dense, buttery intramuscular marbling (sashi)?", "Wagyu beef", "Angus beef", "Hanwoo beef", "Kobe beef, the most famous variety of Wagyu from Hyogo prefecture, is graded up to A5 based on intense marbling and fat melting point.", mcqIdx++));
  q.push(createMCQ("What traditional Japanese soup stock made by simmering kombu kelp and dried fermented skipjack tuna flakes (katsuobushi) forms the backbone of Japanese cuisine?", "Dashi", "Miso", "Mirin", "Dashi provides the foundational umami synergy between glutamate from seaweed and inosinate from bonito flakes.", mcqIdx++));
  q.push(createNumber("How many primary human basic tastes are scientifically recognized on the human palate worldwide?", 5, "tastes", "5 basic tastes", "The five scientifically established basic tastes are Sweet, Sour, Salty, Bitter, and Umami."));

  // Cycle 4: The Global Spice Trade & Flavor Science
  q.push(createMCQ("Which precious crimson spice, harvested by hand from the delicate stigmas of Crocus sativus flowers, is the most expensive spice by weight on Earth?", "Saffron", "Cardamom", "Vanilla", "It requires approximately 75,000 individual crocus flowers to produce just one pound of dried saffron threads, explaining its high market price.", mcqIdx++));
  q.push(createMCQ("Which spice harvested from the cured seed pods of an orchid vine is the second most expensive spice in the world, primarily grown in Madagascar?", "Vanilla", "Nutmeg", "Cinnamon", "Vanilla planifolia orchid blossoms must be hand-pollinated within a single morning during bloom, followed by months of sweating and sun-curing.", mcqIdx++));
  q.push(createMCQ("Which historic spice, known as Black Gold and King of Spices, drove European maritime exploration to India's Malabar Coast?", "Black pepper", "Cloves", "Cumin", "Derived from Piper nigrum dried berries, black pepper gets its signature spicy bite from the active chemical compound piperine.", mcqIdx++));
  q.push(createMCQ("What measurement scale developed by an American pharmacist in 1912 quantifies the pungency and heat of chili peppers based on capsaicin content?", "Scoville scale", "Mohs scale", "Baume scale", "Wilbur Scoville's scale measures heat in Scoville Heat Units (SHU), from zero for sweet bell peppers to over 2 million for the Carolina Reaper.", mcqIdx++));
  q.push(createMCQ("Which spice tree native to the Maluku Islands of Indonesia produces both nutmeg from its inner seed and mace from its red lacy aril covering?", "Myristica fragrans", "Cinnamomum verum", "Syzygium aromaticum", "Nutmeg and mace are the only two distinct culinary spices derived from different parts of the same single fruit tree.", mcqIdx++));
  q.push(createNumber("How many delicate red stigmas are harvested from inside each individual Crocus sativus flower to make saffron?", 3, "stigmas", "3 red stigmas per bloom", "Each purple saffron crocus flower produces exactly three scarlet-red stigmas that must be picked by hand during morning harvest."));

  // Cycle 5: Mexican & Mesoamerican Traditions
  q.push(createMCQ("Which complex, velvety Mexican sauce from Puebla blends dried chilies, Mexican chocolate, spices, seeds, and fruits over hours of simmering?", "Mole Poblano", "Salsa Verde", "Chimichurri", "Legend attributes Mole Poblano to colonial nuns at the Convent of Santa Rosa in Puebla preparing an elaborate feast for an arriving archbishop.", mcqIdx++));
  q.push(createMCQ("What ancient Mesoamerican process involves soaking and cooking raw field corn in an alkaline lime solution (calcium hydroxide) to make masa?", "Nixtamalization", "Fermentation", "Caramelization", "Nixtamalization unlocks essential vitamin B3 (niacin), improves protein quality, and allows corn to form cohesive masa dough for tortillas.", mcqIdx++));
  q.push(createMCQ("What volcanic stone mortar and pestle has been used in Mexican kitchens since pre-Columbian times to grind salsas and guacamole?", "Molcajete", "Metate", "Tagine", "Carved from porous basalt volcanic rock, a well-seasoned molcajete imparts subtle mineral flavors and rustic texture to crushed ingredients.", mcqIdx++));
  q.push(createMCQ("Which Mexican distilled spirit made exclusively from blue Weber agave in Jalisco is protected by strict appellation of origin laws?", "Tequila", "Mezcal", "Bacanora", "Tequila must contain at least 51% blue agave sugars, while 100% pure blue agave tequilas are aged in oak barrels as Blanco, Reposado, or Anejo.", mcqIdx++));
  q.push(createMCQ("Which Mesoamerican crop was consumed as a frothy, bitter ceremonial beverage called xocolatl by Maya and Aztec nobility before reaching Europe?", "Cacao", "Vanilla", "Amaranth", "Aztecs ground roasted cacao beans with chili, vanilla, and achiote, using cacao seeds as standardized currency throughout their empire.", mcqIdx++));
  q.push(createNumber("Approximately how many distinct ingredients are combined and simmered to prepare an authentic traditional Mexican Mole Poblano?", 20, "ingredients", "approx. 20 to 30 ingredients", "Authentic recipes for Mole Poblano traditionally incorporate between 20 and 30 distinct ingredients including mulato, ancho, and pasilla chilies."));

  // Cycle 6: Chinese Culinary Diversity
  q.push(createMCQ("Which regional Chinese cuisine is world-famous for its tongue-numbing málà sensation produced by Sichuan peppercorns and chili oil?", "Sichuan cuisine", "Cantonese cuisine", "Shandong cuisine", "Sichuan peppercorns contain hydroxy-alpha-sanshool, which stimulates tactile vibrating mechanoreceptors on the tongue at roughly 50 Hertz.", mcqIdx++));
  q.push(createMCQ("What Cantonese culinary tradition of small steamed, baked, and fried bite-sized dishes translates literally to touch the heart?", "Dim sum", "Hot pot", "Char siu", "Dim sum originated in traditional teahouses along the ancient Silk Road, paired with the tea-drinking ritual of yum cha.", mcqIdx++));
  q.push(createMCQ("Which imperial dish from Beijing is celebrated for its paper-thin crispy skin and tender meat sliced tableside and wrapped in thin pancakes?", "Peking Duck", "Beggar's Chicken", "Dongpo Pork", "Prepared in specialized hung ovens with fruitwood, Peking Duck has been served to Chinese royalty since the Yuan dynasty.", mcqIdx++));
  q.push(createMCQ("What Cantonese culinary term describes the complex smoky, charred flavor imparted to food from searing in a red-hot carbon steel wok?", "Wok hei", "Searing", "Deglazing", "Wok hei (breath of the wok) results from rapid oil atomization and high-heat Maillard reactions as food is tossed over intense roaring flames.", mcqIdx++));
  q.push(createMCQ("Which Chinese cooking technique involves immersing food in a dark, aromatic stock infused with soy sauce, rock sugar, star anise, and cassia bark?", "Red braising (Hongshao)", "Stir-frying", "Steaming", "Red braising (Hongshao) caramelizes sugar and slow-simmers meats like pork belly into a glossy, deeply savory mahogany-red glaze.", mcqIdx++));
  q.push(createNumber("How many Major Regional Great Cuisines are traditionally recognized in classical Chinese culinary culture?", 8, "regional cuisines", "The Eight Great Cuisines", "Chinese culinary tradition identifies Eight Great Cuisines: Sichuan, Cantonese, Shandong, Jiangsu, Zhejiang, Fujian, Hunan, and Anhui."));

  // Cycle 7: Middle Eastern & Mediterranean Traditions
  q.push(createMCQ("What iconic Levantine dip is prepared by blending cooked chickpeas, tahini paste, freshly squeezed lemon juice, garlic, and olive oil?", "Hummus", "Baba ghanoush", "Labneh", "Hummus (full name Hummus bi Tahina) is a staple across the eastern Mediterranean and Middle East, rich in protein and dietary fiber.", mcqIdx++));
  q.push(createMCQ("What Middle Eastern condiment made from toasted sesame seeds ground into a smooth, pourable oily paste is essential in hummus and halva?", "Tahini", "Harissa", "Dukkah", "Tahini provides nutty richness, emulsifying power, and healthy fats across Middle Eastern, Mediterranean, and North African cuisines.", mcqIdx++));
  q.push(createMCQ("What Middle Eastern herb blend consists of dried wild thyme, toasted sesame seeds, salt, and tart ground crimson sumac berries?", "Za'atar", "Baharat", "Ras el hanout", "Za'atar is traditionally mixed with extra virgin olive oil and spread over flatbread dough before baking (manakish).", mcqIdx++));
  q.push(createMCQ("Which multi-layered dessert popular throughout the former Ottoman Empire consists of paper-thin phyllo pastry filled with chopped nuts and sweetened with honey or syrup?", "Baklava", "Knafeh", "Basbousa", "Baklava originated in the imperial Topkapi Palace kitchens of Istanbul, requiring dozens of translucent pastry sheets brushed with clarified butter.", mcqIdx++));
  q.push(createMCQ("What grade of olive oil is produced by the first cold mechanical pressing of freshly harvested olives with no chemical solvents and minimal acidity?", "Extra Virgin Olive Oil", "Virgin Olive Oil", "Pure Olive Oil", "International Olive Council standards mandate that Extra Virgin Olive Oil must possess flawless organoleptic qualities and less than 0.8% free acidity.", mcqIdx++));
  q.push(createNumber("What is the maximum allowed percentage of free fatty acidity for certified Extra Virgin Olive Oil according to International Olive Council standards?", 0.8, "percent acidity", "max 0.8%", "To qualify as Extra Virgin Olive Oil, the oil must have a free acidity expressed as oleic acid of no more than 0.8 grams per 100 grams (0.8%)."));

  // Cycle 8: Indian Spices & Regional Curries
  q.push(createMCQ("What cylindrical clay or metal oven embedded in the earth and fired with charcoal reaches intense heat to bake naan bread and tandoori chicken?", "Tandoor", "Karahi", "Degchi", "A tandoor reaches temperatures over 450 degrees Celsius; flatbreads are slapped directly onto the curved inner clay walls to blister and cook in seconds.", mcqIdx++));
  q.push(createMCQ("Which warm, aromatic Indian spice blend translates to hot spice mix, typically combining cardamom, cinnamon, cloves, cumin, and black pepper?", "Garam Masala", "Curry Powder", "Panch Phoron", "Unlike raw spice pastes cooked early, garam masala is frequently sprinkled near the conclusion of cooking to preserve volatile essential oils.", mcqIdx++));
  q.push(createMCQ("Which golden-yellow spice containing the powerful antioxidant compound curcumin provides the signature color in Indian curries and lentils?", "Turmeric", "Fenugreek", "Mustard seed", "Turmeric rhizomes are boiled, dried, and ground into fine golden powder, utilized for centuries in Ayurvedic medicine and cooking.", mcqIdx++));
  q.push(createMCQ("Which elaborate Mughal-influenced Indian rice dish layers marinated spiced meat with fragrant long-grain basmati rice, saffron, and fried onions?", "Biryani", "Pulao", "Kichdi", "Authentic Dum Biryani is cooked in a sealed heavy pot (dum pukht) with dough around the rim to trap steam and infuse rich aromatics.", mcqIdx++));
  q.push(createMCQ("What traditional clarified butter, simmered until water evaporates and milk solids caramelize, is the primary cooking fat in Indian cuisine?", "Ghee", "Paneer", "Makhani", "Ghee has a high smoke point of 250 degrees Celsius, allowing high-heat tempering (tadka) of whole spices without burning.", mcqIdx++));
  q.push(createNumber("Approximately what temperature in degrees Celsius is reached inside a fully heated traditional Indian tandoor oven?", 480, "degrees Celsius", "approx. 900 °F", "Traditional charcoal-fired tandoor clay ovens regularly reach sustained temperatures between 450 and 480 degrees Celsius (840 to 900 °F)."));

  // Cycle 9: Fermentation, Cheese & Food Chemistry
  q.push(createMCQ("What chemical reaction between amino acids and reducing sugars at elevated temperatures produces the appetizing golden-brown crust on seared steaks and baked bread?", "Maillard reaction", "Caramelization", "Pyrolysis", "Discovered in 1912 by Louis-Camille Maillard, the reaction generates hundreds of distinct flavor compounds responsible for rich roasted aromas.", mcqIdx++));
  q.push(createMCQ("Which blue-veined French sheep's milk cheese is aged inside the natural damp limestone caves of Mount Combalou in Roquefort-sur-Soulzon?", "Roquefort", "Gorgonzola", "Stilton", "Roquefort is inoculated with the blue mold Penicillium roqueforti, yielding sharp, tangy veins throughout its creamy ivory paste.", mcqIdx++));
  q.push(createMCQ("What microscopic single-celled fungus responsible for fermenting sugars into alcohol and carbon dioxide is used in brewing and bread baking?", "Saccharomyces cerevisiae", "Lactobacillus", "Aspergillus oryzae", "Known as brewer's or baker's yeast, Saccharomyces cerevisiae is humanity's oldest and most vital domesticated microbial organism in food production.", mcqIdx++));
  q.push(createMCQ("What staple Korean side dish consists of salted, fermented napa cabbage and radishes seasoned with gochugaru chili, garlic, ginger, and jeotgal?", "Kimchi", "Banchan", "Gochujang", "Lactic acid fermentation by Leuconostoc and Lactobacillus bacteria gives kimchi its signature sour tang and probiotic health benefits.", mcqIdx++));
  q.push(createMCQ("What is the living symbiotic culture of wild yeast and lactic acid bacteria used to ferment traditional artisan sourdough bread called?", "Sourdough starter", "Poolish", "Biga", "A sourdough starter (levain) ferments flour and water naturally, eliminating the need for commercial manufactured baker's yeast.", mcqIdx++));
  q.push(createNumber("At approximately what temperature in degrees Celsius does the Maillard browning reaction begin to rapidly accelerate in cooking?", 140, "degrees Celsius", "approx. 284 °F", "The Maillard reaction accelerates rapidly between 140 and 165 degrees Celsius (284 to 330 °F), producing optimal browning on roasted foods."));

  // Cycle 10: Modernist Gastronomy & Coffee Culture
  q.push(createMCQ("Which Spanish avant-garde chef pioneered modernist culinary techniques such as culinary foams and spherification at his restaurant El Bulli?", "Ferran Adria", "Joan Roca", "Andoni Luis Aduriz", "El Bulli in Catalonia was named the World's Best Restaurant five times, using sodium alginate and calcium baths to encapsulate liquids in spheres.", mcqIdx++));
  q.push(createMCQ("What culinary technique uses sodium alginate and calcium chloride baths to shape flavored liquids into spheres that pop in the mouth like caviar?", "Spherification", "Gelification", "Emulsification", "Direct and reverse spherification transform juices, wines, and purees into delicate fluid-filled spheres with thin gelatinous membranes.", mcqIdx++));
  q.push(createMCQ("What standard pump water pressure in bars is utilized by commercial espresso machines to force near-boiling water through tamped coffee grounds?", "Nine bars of pressure", "Two bars of pressure", "Twenty bars of pressure", "Standard espresso extraction utilizes 9 bars of pressure (approx. 130 psi) at 90 to 96 degrees Celsius to produce concentrated coffee crowned with rich crema.", mcqIdx++));
  q.push(createMCQ("Which British multi-Michelin-starred chef at The Fat Duck is renowned for scientific multi-sensory dining, introducing bacon-and-egg ice cream?", "Heston Blumenthal", "Gordon Ramsay", "Marco Pierre White", "Blumenthal uses soundscapes (Sound of the Sea), liquid nitrogen, and flavor pairing chemistry to create evocative culinary memories.", mcqIdx++));
  q.push(createMCQ("What species of coffee plant accounts for roughly 60 to 70 percent of global coffee production, celebrated for its complex floral and fruity acidity?", "Coffea arabica", "Coffea canephora", "Coffea liberica", "Arabica grows best at high altitudes with cooler temperatures, containing lower caffeine and higher sugar content than hardier Robusta coffee.", mcqIdx++));
  q.push(createNumber("What is the standard water pressure in bars required to pull a classic Italian espresso shot in commercial machines?", 9, "bars", "9 bars pressure", "The Italian Espresso National Institute standard specifies 9 ± 1 bars of water extraction pressure to achieve classic crema and emulsified aromatic oils."));

  return {
    id: "culinary-arts-world-cuisines-60",
    theme: "Culinary Arts: Global Gastronomy, Spices & Cuisines",
    title: "Culinary Arts: Global Gastronomy, Spices & Cuisines",
    description: "A 60-question grand master assessment exploring French mother sauces, Italian DOC traditions, Japanese sushi artistry, the global spice trade, Mesoamerican chocolate and mole, Chinese regional cuisines, Middle Eastern mezze, Indian curries, fermentation science, and modernist gastronomy.",
    category: "Arts, Music, Literature & Philosophy",
    difficulty: "moderate",
    createdAt: "2026-08-27T00:00:00Z",
    questions: q
  };
}

module.exports = {
  getArchitectureQuiz,
  getWorldLanguagesQuiz,
  getPhilosophyQuiz,
  getCulinaryArtsQuiz
};

if (require.main === module) {
  const quizzes = [
    getArchitectureQuiz(),
    getWorldLanguagesQuiz(),
    getPhilosophyQuiz(),
    getCulinaryArtsQuiz()
  ];
  
  for (const quiz of quizzes) {
    const dir = path.join('quizzes', quiz.id);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, 'dataset.json'), JSON.stringify(quiz, null, 2), 'utf8');
    console.log(`Wrote: ${dir}/dataset.json`);
  }
}
