const { buildQuiz } = require('./generate_helpers.cjs');

// -------------------------------------------------------------
// 10. solar-system-planets-moons-60
// -------------------------------------------------------------
const solarSystemCycles = [
  // Cycle 1: Terrestrial Planets (Mercury, Venus, Earth, Mars)
  {
    mcqs: [
      {
        q: "What innermost planet has no substantial atmosphere, experiences surface temperatures from -180 °C to 430 °C, and possesses a colossal metallic iron core?",
        correct: "Mercury",
        w1: "Venus",
        w2: "Mars",
        exp: "Mercury metallic iron core occupies roughly 85 percent of the planetary radius, causing its crust to contract and form massive lobate scarp cliffs."
      },
      {
        q: "What is the hottest planet in the Solar System, where a runaway carbon dioxide greenhouse effect creates surface temperatures of 465 °C?",
        correct: "Venus",
        w1: "Mercury",
        w2: "Mars",
        exp: "Venus atmosphere is 96 percent carbon dioxide beneath sulfuric acid clouds, exerting a surface pressure over 90 times greater than Earth."
      },
      {
        q: "What colossal shield volcano on Mars is the tallest volcano and mountain in the Solar System, rising over 21 km above the datum surface?",
        correct: "Olympus Mons",
        w1: "Ascraeus Mons",
        w2: "Elysium Mons",
        exp: "Olympus Mons is nearly three times the height of Mount Everest, covering a footprint the size of the state of Arizona due to Mars lack of mobile tectonic plates."
      },
      {
        q: "What immense canyon system on Mars stretches over 4,000 km long and reaches depths of 7 km, dwarfing Earth Grand Canyon?",
        correct: "Valles Marineris",
        w1: "Noctis Labyrinthus",
        w2: "Ares Vallis",
        exp: "Valles Marineris is a colossal tectonic fracture system along the Tharsis volcanic bulge, spanning nearly a quarter of the Martian circumference."
      },
      {
        q: "What mineral chemical compound oxidizes in Martian surface regolith to give the Red Planet its characteristic rust-red hue?",
        correct: "Iron Oxide Ferric Rust",
        w1: "Silicon Dioxide",
        w2: "Titanium Dioxide",
        exp: "Fine dust grains of ferric iron oxide (Fe2O3) suspend in the thin Martian atmosphere and coat the surface rocks, creating its iconic reddish appearance."
      }
    ],
    number: {
      q: "What is the average surface atmospheric pressure on Venus measured in atmospheres atm compared to Earth sea level?",
      target: 92,
      unit: "atm",
      imperial: "92 atmospheres (approx 9.3 MPa)",
      exp: "Surface pressure on Venus is 92 bars (approx 9.3 MPa or 1,350 PSI), equivalent to the crushing hydrostatic pressure found 900 meters underwater on Earth."
    }
  },

  // Cycle 2: The Gas Giants: Jupiter & Saturn
  {
    mcqs: [
      {
        q: "What is the largest planet in the Solar System by mass and volume, containing more mass than all other planets and asteroids combined?",
        correct: "Jupiter",
        w1: "Saturn",
        w2: "Neptune",
        exp: "Jupiter is 318 times more massive than Earth, with a powerful magnetic field generated by metallic liquid hydrogen churning in its interior."
      },
      {
        q: "What colossal anticyclonic storm in Jupiter southern hemisphere has raged continuously for at least 350 years, with diameters larger than Earth?",
        correct: "Great Red Spot",
        w1: "Oval BA",
        w2: "South Tropical Disturbance",
        exp: "The Great Red Spot is a high-pressure vortex rotating counter-clockwise with wind speeds exceeding 430 km/h, reaching deep into Jupiter troposphere."
      },
      {
        q: "What two primary gases constitute over 99 percent of the total chemical composition of gas giants Jupiter and Saturn?",
        correct: "Hydrogen and Helium",
        w1: "Methane and Nitrogen",
        w2: "Carbon Dioxide and Ammonia",
        exp: "Jupiter and Saturn closely mirror the primordial chemical abundance of the solar nebula, composed of roughly 75% hydrogen and 24% helium by mass."
      },
      {
        q: "What planet has the lowest mean density in the entire Solar System at roughly 0.687 g/cm3, light enough to float in a theoretical cosmic ocean of water?",
        correct: "Saturn",
        w1: "Uranus",
        w2: "Neptune",
        exp: "Saturn is composed primarily of light hydrogen and helium gases, making its bulk density lower than liquid water (1.0 g/cm3)."
      },
      {
        q: "What persistent, geometric hexagonal atmospheric jet-stream storm pattern rotates stably around the north pole of Saturn?",
        correct: "Saturn Hexagon",
        w1: "Great White Spot",
        w2: "Polar Vortex Eye",
        exp: "Discovered by Voyager in 1981 and studied by Cassini, the six-sided wave pattern is a 30,000-km-wide jet stream flowing at 320 km/h."
      }
    ],
    number: {
      q: "How many Earth masses does the giant planet Jupiter contain within its colossal gravitational body?",
      target: 318,
      unit: "Earth masses",
      imperial: "318 Earth masses (1.90 x 10^27 kg)",
      exp: "Jupiter has a mass of 1.898 x 10^27 kg, equivalent to approximately 317.8 Earth masses, dominating the gravitational architecture of the Solar System."
    }
  },

  // Cycle 3: The Ice Giants: Uranus & Neptune
  {
    mcqs: [
      {
        q: "What atmospheric trace gas absorbs red light and reflects blue wavelengths, giving Uranus and Neptune their cyan and deep azure hues?",
        correct: "Methane",
        w1: "Ammonia",
        w2: "Hydrogen Sulfide",
        exp: "Methane in the upper tropospheres of ice giants absorbs red wavelengths in the visible spectrum, reflecting back vibrant cyan and blue light."
      },
      {
        q: "What extreme rotational characteristic distinguishes Uranus from all other planets, tilting its axis by 97.8 degrees relative to its orbital plane?",
        correct: "It rotates completely on its side with retrograde spin",
        w1: "It has zero planetary magnetic field",
        w2: "It takes longer to rotate than to orbit the Sun",
        exp: "Uranus spins on its side with poles facing the Sun during solstices, likely caused by a massive giant impact with an Earth-sized protoplanet during solar system formation."
      },
      {
        q: "Which planet in the Solar System experiences the most violent sustained wind speeds, measured at over 2,100 km/h in its upper atmosphere?",
        correct: "Neptune",
        w1: "Uranus",
        w2: "Saturn",
        exp: "Despite receiving little solar energy, Neptune internal heat engine drives supersonic eastward jet streams reaching speeds of up to 600 m/s (2,160 km/h)."
      },
      {
        q: "What massive Earth-sized anticyclonic storm system was photographed in Neptune southern hemisphere by NASA Voyager 2 spacecraft in 1989?",
        correct: "Great Dark Spot",
        w1: "Small Dark Spot",
        w2: "Scooter Cloud",
        exp: "The Great Dark Spot was a high-pressure atmospheric hole in Neptune methane cloud deck that vanished by 1994, replaced by new northern spots."
      },
      {
        q: "Which French mathematician calculated the precise coordinates of Neptune based solely on gravitational perturbations in Uranus orbit before its 1846 visual discovery?",
        correct: "Urbain Le Verrier",
        w1: "John Couch Adams",
        w2: "Johann Galle",
        exp: "Le Verrier calculations allowed astronomer Johann Galle at the Berlin Observatory to point a telescope and locate Neptune within 1 degree of the predicted spot."
      }
    ],
    number: {
      q: "What is the axial tilt in degrees of the ice giant planet Uranus relative to its orbital plane?",
      target: 97.8,
      unit: "degrees",
      imperial: "97.8° axial tilt",
      exp: "Uranus has an axial tilt of 97.77 degrees, meaning its rotational axis is almost parallel with the plane of the Solar System."
    }
  },

  // Cycle 4: Moons of the Outer Solar System
  {
    mcqs: [
      {
        q: "Which icy moon of Jupiter is the smoothest solid body in the Solar System, harboring a global saltwater ocean beneath a 20-km ice shell?",
        correct: "Europa",
        w1: "Ganymede",
        w2: "Callisto",
        exp: "Europa subsurface ocean is estimated to hold twice as much liquid water as all Earth oceans combined, warmed by tidal flexure from Jupiter gravity."
      },
      {
        q: "What giant moon of Saturn is the only moon with a dense nitrogen atmosphere and liquid hydrocarbon lakes of methane and ethane on its surface?",
        correct: "Titan",
        w1: "Enceladus",
        w2: "Mimas",
        exp: "Titan has a surface atmospheric pressure 1.5 times Earth, featuring methane rainfall, river channels, dunes of tholin organics, and vast polar seas like Kraken Mare."
      },
      {
        q: "What volcanic moon of Jupiter is the most geologically active body in the Solar System, with hundreds of sulfur volcanoes powered by extreme tidal heating?",
        correct: "Io",
        w1: "Europa",
        w2: "Ganymede",
        exp: "Gravitational tugs between Jupiter, Europa, and Ganymede create orbital resonance that flexes Io solid rock interior by 100 meters, driving continuous volcanism."
      },
      {
        q: "What small icy moon of Saturn vents plumes of water vapor, organic molecules, and silica grains into space from tiger stripe fractures at its south pole?",
        correct: "Enceladus",
        w1: "Dione",
        w2: "Rhea",
        exp: "Cassini flew through Enceladus cryovolcanic plumes, discovering hydrothermal vent chemistry in a warm subsurface global ocean capable of supporting life."
      },
      {
        q: "What is the largest moon in the Solar System, larger in diameter than planet Mercury and possessing its own internally generated magnetic field?",
        correct: "Ganymede",
        w1: "Titan",
        w2: "Callisto",
        exp: "Ganymede measures 5,268 km across, containing a liquid iron-rich core that generates a magnetosphere embedded inside Jupiter giant magnetic field."
      }
    ],
    number: {
      q: "What is the diameter in kilometers of Ganymede, the largest planetary moon in the Solar System?",
      target: 5268,
      unit: "km",
      imperial: "3,273 miles (5,268 km)",
      exp: "Ganymede has a diameter of 5,268 kilometers, making it roughly 8% larger than planet Mercury (4,879 km) and the largest satellite in the Solar System."
    }
  },

  // Cycle 5: Dwarf Planets & The Kuiper Belt
  {
    mcqs: [
      {
        q: "What dwarf planet was classified as the ninth planet from its discovery in 1930 until the International Astronomical Union redefined planet criteria in 2006?",
        correct: "Pluto",
        w1: "Eris",
        w2: "Ceres",
        exp: "Pluto was reclassified because it has not cleared the neighborhood around its orbit, residing among thousands of icy bodies in the Kuiper Belt."
      },
      {
        q: "What massive, heart-shaped nitrogen-ice glacier basin was revealed on Pluto by NASA New Horizons spacecraft in July 2015?",
        correct: "Sputnik Planitia",
        w1: "Tombaugh Regio",
        w2: "Cthulhu Macula",
        exp: "Sputnik Planitia is a 1,000-km-wide basin of churning nitrogen and carbon monoxide ice undergoing active convective cellular turnover."
      },
      {
        q: "What massive dwarf planet in the scattered disc beyond Neptune was discovered in 2005, whose massive mass triggered the formal IAU redefinition of a planet?",
        correct: "Eris",
        w1: "Haumea",
        w2: "Makemake",
        exp: "Eris is 27 percent more massive than Pluto, orbiting the Sun in an eccentric 558-year orbit accompanied by its small moon Dysnomia."
      },
      {
        q: "What fast-spinning Kuiper Belt dwarf planet rotates once every 3.9 hours, stretching its icy body into an elongated triaxial ellipsoid football shape?",
        correct: "Haumea",
        w1: "Quaoar",
        w2: "Sedna",
        exp: "Haumea rapid rotation is the fastest of any large Solar System body over 100 km, accompanied by a crystalline water-ice surface, two moons, and a dark ring."
      },
      {
        q: "What largest moon of Pluto is so massive relative to Pluto (approx 1:8 mass ratio) that the two orbit a common barycenter in empty space above Pluto surface?",
        correct: "Charon",
        w1: "Nix",
        w2: "Hydra",
        exp: "Pluto and Charon are mutually tidally locked, always presenting the exact same hemisphere to each other across a distance of 19,640 km."
      }
    ],
    number: {
      q: "In what year CE did the International Astronomical Union IAU formally vote to establish the modern definition of a planet and reclassify Pluto as a dwarf planet?",
      target: 2006,
      unit: "CE",
      imperial: "2006 CE",
      exp: "At the IAU General Assembly in Prague on August 24, 2006, astronomers voted to define a planet as a body orbiting the Sun, with hydrostatic equilibrium, that has cleared its orbit."
    }
  },

  // Cycle 6: Asteroid Belt, Comets & Oort Cloud
  {
    mcqs: [
      {
        q: "What is the largest object and only recognized dwarf planet located inside the main Asteroid Belt between Mars and Jupiter?",
        correct: "1 Ceres",
        w1: "4 Vesta",
        w2: "2 Pallas",
        exp: "Ceres accounts for roughly one-third of the total mass of the asteroid belt, containing a rocky core and water-ice mantle with cryovolcanic salt domes like Ahuna Mons."
      },
      {
        q: "What rocky protoplanet in the asteroid belt features a colossal south polar impact crater named Rheasilvia and is the source of HED meteorites on Earth?",
        correct: "4 Vesta",
        w1: "2 Pallas",
        w2: "10 Hygiea",
        exp: "Vesta is a differentiated asteroid with a basaltic crust, mantle, and metallic iron core, surveyed in detail by NASA Dawn spacecraft in 2011."
      },
      {
        q: "What periodic comet orbits the Sun every 75 to 76 years, being the only naked-eye comet regularly seen twice in a single human lifespan?",
        correct: "Halley Comet 1P/Halley",
        w1: "Comet Encke",
        w2: "Comet Hale-Bopp",
        exp: "Edmond Halley used Newtonian gravitational mechanics to predict its 1758 return; its next perihelion passage will occur in mid-2061."
      },
      {
        q: "What theoretical spherical cloud of trillions of icy planetesimals extends up to 100,000 AU from the Sun, generating long-period comets?",
        correct: "Oort Cloud",
        w1: "Kuiper Belt",
        w2: "Hills Cloud",
        exp: "Proposed by Jan Oort in 1950, the Oort Cloud marks the outer gravitational boundary of the Solar System, extending halfway to Alpha Centauri."
      },
      {
        q: "What cigar-shaped interstellar object discovered passing through our Solar System on a hyperbolic trajectory in 2017 was named from the Hawaiian word for scout?",
        correct: "Oumuamua 1I/2017 U1",
        w1: "2I/Borisov",
        w2: "Comet Bernardinelli-Bernstein",
        exp: "Oumuamua showed non-gravitational acceleration likely caused by outgassing of nitrogen or hydrogen ice as it swung past the Sun at 87 km/s."
      }
    ],
    number: {
      q: "What is the orbital period in years of Halley Comet 1P/Halley as it travels along its highly eccentric elliptical orbit around the Sun?",
      target: 76,
      unit: "years",
      imperial: "75 to 76 years",
      exp: "Halley Comet completes one orbit around the Sun every 75 to 76 years, last appearing in 1986 and scheduled to return to the inner Solar System in 2061."
    }
  },

  // Cycle 7: The Sun: Core, Corona & Solar Activity
  {
    mcqs: [
      {
        q: "What nuclear fusion cycle converts four hydrogen protons into a single helium nucleus inside the Sun core at 15 million Kelvin?",
        correct: "Proton-Proton Chain Reaction",
        w1: "CNO Cycle",
        w2: "Triple-Alpha Process",
        exp: "The p-p chain fuses 600 million tons of hydrogen into helium every second in the solar core, converting 4.3 million tons of mass directly into pure energy ($E=mc^2$)."
      },
      {
        q: "What outermost atmospheric layer of the Sun consists of superheated, low-density plasma reaching 1 to 3 million Kelvin, visible during total solar eclipses?",
        correct: "Solar Corona",
        w1: "Chromosphere",
        w2: "Photosphere",
        exp: "The corona is heated to millions of degrees by magnetic reconnection and Alfven waves, accelerating solar wind particles out into interplanetary space."
      },
      {
        q: "What dark, cooler magnetic regions on the solar photosphere are caused by intense magnetic flux loops suppressing convective heat rising from below?",
        correct: "Sunspots",
        w1: "Solar Plages",
        w2: "Coronal Holes",
        exp: "Sunspots appear dark against the blinding photosphere because their 3,800 °C temperatures are cooler than the surrounding 5,500 °C convective plasma granules."
      },
      {
        q: "What massive eruptions of magnetized plasma and magnetic fields blast billions of tons of solar particles into space at speeds up to 3,000 km/s?",
        correct: "Coronal Mass Ejections CMEs",
        w1: "Solar Prominences",
        w2: "Photospheric Granules",
        exp: "When CMEs impact Earth magnetosphere, they trigger intense geomagnetic storms, spectacular auroral displays, and potential electrical grid disruptions."
      },
      {
        q: "What continuous stream of charged protons, electrons, and alpha particles expands outward from the Sun through the entire Solar System at 400 to 800 km/s?",
        correct: "Solar Wind",
        w1: "Galactic Cosmic Rays",
        w2: "Poynting Flux",
        exp: "The solar wind creates the heliospheric bubble that shields inner planets from high-energy interstellar cosmic radiation."
      }
    ],
    number: {
      q: "What is the average surface effective temperature of the Sun photosphere in degrees Celsius?",
      target: 5500,
      unit: "celsius",
      imperial: "5,500 °C (9,932 °F)",
      exp: "The visible surface of the Sun (the photosphere) has an effective blackbody temperature of approximately 5,500 °C (5,778 Kelvin or 9,932 °F)."
    }
  },

  // Cycle 8: Orbital Mechanics & Gravitational Physics
  {
    mcqs: [
      {
        q: "What first law of planetary motion formulated by Johannes Kepler states that all planets orbit the Sun in what geometric trajectory?",
        correct: "Ellipses with the Sun located at one focus",
        w1: "Concentric perfect circles",
        w2: "Parabolic trajectories with the Sun at the vertex",
        exp: "Published in Astronomia Nova (1609), Kepler First Law overthrew the ancient Aristotelian assumption of uniform circular celestial orbits."
      },
      {
        q: "What five positions in an orbital configuration allow a small object to maintain a fixed position relative to two larger orbiting bodies?",
        correct: "Lagrange Equilibrium Points",
        w1: "Barycenter nodes",
        w2: "Perihelion axes",
        exp: "Lagrangian points (L1 to L5) balance gravitational pull and centrifugal force, with L2 hosting space telescopes like James Webb and Gaia."
      },
      {
        q: "What minimum distance from a primary body can an orbiting celestial body held together only by gravity approach before being torn apart by tidal forces?",
        correct: "Roche Limit",
        w1: "Chandrasekhar Limit",
        w2: "Hill Sphere Radius",
        exp: "If a moon crosses inside the Roche limit of its planet, tidal stretching exceeds the moon self-gravitation, shredding it into a planetary ring system."
      },
      {
        q: "What orbital flight maneuver uses the gravitational pull and orbital velocity of a passing planet to accelerate or decelerate a spacecraft without propellant?",
        correct: "Gravity Assist Slingshot Maneuver",
        w1: "Hohmann Transfer",
        w2: "Aerocapture Burn",
        exp: "Spacecraft like Voyager, Cassini, and New Horizons utilized gravitational slingshots around Jupiter to gain velocity and reach the outer Solar System in years."
      },
      {
        q: "What boundary marks the outer edge of the heliosphere where the solar wind pressure is balanced by the opposing pressure of the interstellar medium?",
        correct: "Heliopause",
        w1: "Termination Shock",
        w2: "Bow Shock Wave",
        exp: "Voyager 1 crossed the heliopause at 121 AU in August 2012, detecting an abrupt drop in solar wind particles and a dramatic surge in galactic cosmic rays."
      }
    ],
    number: {
      q: "How many distinct gravitational Lagrange equilibrium points L1 through L5 exist for any two-body orbital system in space?",
      target: 5,
      unit: "Lagrange points",
      imperial: "5 Lagrange points (L1-L5)",
      exp: "There are exactly five Lagrange points in any two-body orbital system: three collinear unstable points (L1, L2, L3) and two stable triangular points (L4, L5)."
    }
  },

  // Cycle 9: Robotic Exploration & Planetary Probes
  {
    mcqs: [
      {
        q: "What robotic spacecraft launched in 1977 is the most distant human-made object from Earth, traveling through interstellar space beyond 160 AU?",
        correct: "Voyager 1",
        w1: "Pioneer 10",
        w2: "New Horizons",
        exp: "Voyager 1 carries a gold-plated audio-visual Golden Record and continues transmitting telemetry powered by radioisotope thermoelectric generators RTGs."
      },
      {
        q: "What joint NASA-ESA robotic flagship mission orbited Saturn for 13 years and deployed the European Huygens probe to land on the surface of Titan?",
        correct: "Cassini-Huygens",
        w1: "Galileo Mission",
        w2: "Juno Mission",
        exp: "Cassini discovered active geysers on Enceladus, methane seas on Titan, and complex ring structures before executing a planned plunge into Saturn in 2017."
      },
      {
        q: "What car-sized NASA rover landed inside Jezero Crater on Mars in February 2021 to cache rock cores and search for ancient microbial biosignatures?",
        correct: "Perseverance Rover",
        w1: "Curiosity Rover",
        w2: "Opportunity Rover",
        exp: "Perseverance deployed the MOXIE oxygen production experiment and carried the Ingenuity helicopter, sampling sedimentary delta mudstones."
      },
      {
        q: "What ESA robotic spacecraft completed the first orbital rendezvous and soft lander touchdown Philae on the nucleus of Comet 67P in 2014?",
        correct: "Rosetta",
        w1: "Giotto",
        w2: "Deep Impact",
        exp: "Rosetta escorted Comet 67P/Churyumov-Gerasimenko through perihelion, discovering organic molecules, complex dust grains, and molecular oxygen."
      },
      {
        q: "What NASA spacecraft launched in 2018 is flying directly through the Sun corona, surviving 1,400 °C heat to measure solar magnetic reconnection up close?",
        correct: "Parker Solar Probe",
        w1: "SOHO Observatory",
        w2: "Solar Orbiter",
        exp: "Parker Solar Probe uses a 11.4-cm carbon-composite heat shield, reaching record orbital velocities exceeding 690,000 km/h (430,000 mph) near perihelion."
      }
    ],
    number: {
      q: "How many total flight minutes did the Ingenuity Mars Helicopter fly across its historic 72 flights on Mars, initially designed for just 5 test flights?",
      target: 128,
      unit: "minutes",
      imperial: "128.8 minutes of powered flight",
      exp: "Ingenuity completed 72 powered flights across Mars thin atmosphere, accumulating 128.8 minutes of flight time and covering 17 kilometers before mission retirement."
    }
  },

  // Cycle 10: Formation & Evolution of the Solar System
  {
    mcqs: [
      {
        q: "What leading astrophysical model describes the birth of the Sun and planets from the gravitational collapse of a rotating giant molecular gas cloud?",
        correct: "Solar Nebular Hypothesis",
        w1: "Tidal Capture Theory",
        w2: "Fission Centrifugal Model",
        exp: "Proposed by Kant and Laplace and refined by modern astrophysics, conservation of angular momentum flattened the collapsing cloud into a protoplanetary accretion disc."
      },
      {
        q: "What dynamic migration model proposes that outer gas giants shifted their orbits in early history, scattering planetesimals and causing the Late Heavy Bombardment?",
        correct: "Nice Model",
        w1: "Grand Tack Scenario",
        w2: "Core Accretion Model",
        exp: "The Nice model explains that resonant interactions between Jupiter and Saturn destabilized the orbits of Uranus and Neptune, flinging Neptune outward into the Kuiper Belt."
      },
      {
        q: "What thermal boundary in the protoplanetary disc separated inner terrestrial regions from outer cold zones where volatile ices could condense?",
        correct: "Frost Line Snow Line",
        w1: "Roche Limit",
        w2: "Kuiper Cliff",
        exp: "Inside the frost line (approx 2.7 AU), only metals and silicate minerals condensed into rocky planetesimals; beyond it, abundant water and methane ice built giant cores."
      },
      {
        q: "What scientific theory explains the origin of Earth Moon through a catastrophic collision between the proto-Earth and a Mars-sized protoplanet named Theia?",
        correct: "Giant Impact Hypothesis",
        w1: "Gravitational Capture Model",
        w2: "Co-accretion Hypothesis",
        exp: "The giant impact vaporized outer mantles, throwing molten debris into orbit that rapidly coalesced into the Moon, explaining the Moon depleted iron core."
      },
      {
        q: "What calcium-aluminum-rich inclusions CAIs found in primitive carbonaceous chondrite meteorites like Allende provide the definitive baseline age of the Solar System?",
        correct: "4.567 billion years",
        w1: "3.800 billion years",
        w2: "6.200 billion years",
        exp: "Uranium-lead radiometric dating of refractory CAIs dates the earliest solid mineral condensates of the solar nebula precisely to 4.5673 billion years ago."
      }
    ],
    number: {
      q: "How many billion years ago did our Solar System and the Sun form from the gravitational collapse of the solar nebula?",
      target: 4.567,
      unit: "billion years",
      imperial: "4.567 billion years ago",
      exp: "High-precision radiometric lead-lead dating of calcium-aluminum-rich inclusions (CAIs) in meteorites dates the formation of the Solar System to 4.567 billion years."
    }
  }
];

buildQuiz({
  id: 'solar-system-planets-moons-60',
  theme: 'The Solar System: Planets, Moons & Asteroid Belts',
  title: 'The Solar System: Planets, Moons & Asteroid Belts',
  description: 'A 60-question grand master assessment exploring terrestrial planets, gas giant dynamics, icy ocean moons, dwarf planets, asteroid geology, and solar physics.',
  category: 'Astronomy, Physics & Chemistry',
  difficulty: 'moderate'
}, solarSystemCycles);

// -------------------------------------------------------------
// 11. deep-space-black-holes-cosmology-60
// -------------------------------------------------------------
const cosmologyCycles = [
  // Cycle 1: Black Hole Fundamentals & Horizons
  {
    mcqs: [
      {
        q: "What theoretical boundary surface around a black hole marks the threshold within which the escape velocity exceeds the speed of light?",
        correct: "Event Horizon",
        w1: "Photon Sphere",
        w2: "Ergosphere",
        exp: "Once matter or radiation crosses inside the event horizon, all future light cones tilt inward toward the central singularity, making escape physically impossible."
      },
      {
        q: "What equation radius named after a German physicist defines the event horizon radius of a non-rotating spherically symmetric black hole based on its mass?",
        correct: "Schwarzschild Radius",
        w1: "Hubble Radius",
        w2: "Bohr Radius",
        exp: "Calculated as $R_s = 2GM/c^2$, any object compressed inside its Schwarzschild radius collapses gravitationally into a black hole."
      },
      {
        q: "What theoretical point of zero volume, infinite density, and infinite spacetime curvature resides at the center of a non-rotating black hole?",
        correct: "Gravitational Singularity",
        w1: "Planck Core",
        w2: "Event Node",
        exp: "General relativity predicts that mass collapses into an infinitely dense point singularity, where classical equations break down and quantum gravity is needed."
      },
      {
        q: "What physical process stretches an object vertically and compresses it horizontally as it approaches a stellar-mass black hole due to extreme tidal gravity?",
        correct: "Spaghettification",
        w1: "Frame Dragging",
        w2: "Gravitational Blueshift",
        exp: "The gravitational gradient across the length of an astronaut feet versus head produces extreme differential tidal forces that pull the body into a long noodle string."
      },
      {
        q: "What quantum thermal radiation predicted by Stephen Hawking causes black holes to slowly lose mass and evaporate over astronomical timescales?",
        correct: "Hawking Radiation",
        w1: "Unruh Radiation",
        w2: "Cherenkov Radiation",
        exp: "Quantum vacuum virtual particle-antiparticle pairs near the event horizon can separate, with one falling in while the other escapes as thermal radiation."
      }
    ],
    number: {
      q: "What is the Schwarzschild event horizon radius in kilometers for a black hole with the exact mass of our Sun (1 Solar Mass)?",
      target: 3,
      unit: "km",
      imperial: "1.86 miles (2.95 km)",
      exp: "For a solar mass object ($1.989 \\times 10^{30}$ kg), the Schwarzschild radius $R_s = 2GM/c^2$ equals approximately 2.95 kilometers (approx 3 km)."
    }
  },

  // Cycle 2: Supermassive Black Holes & Active Galactic Nuclei
  {
    mcqs: [
      {
        q: "What supermassive black hole containing roughly 4.15 million solar masses resides at the dynamical center of our Milky Way Galaxy?",
        correct: "Sagittarius A*",
        w1: "Cygnus X-1",
        w2: "Centaurus A",
        exp: "Tracking orbital paths of high-speed S-stars like S2 over decades confirmed a compact mass of 4.15 million solar masses at the radio source Sagittarius A*."
      },
      {
        q: "What giant elliptical galaxy in the Virgo Cluster contains the 6.5-billion-solar-mass black hole famously imaged by the Event Horizon Telescope in 2019?",
        correct: "Messier 87 M87*",
        w1: "Andromeda M31",
        w2: "Sombrero Galaxy M104",
        exp: "The EHT collaboration linked radio dishes worldwide into an Earth-sized virtual telescope, resolving the bright emission ring and shadow of M87*."
      },
      {
        q: "What extremely luminous active galactic nucleus AGN is powered by matter accreting onto a supermassive black hole, outshining an entire host galaxy?",
        correct: "Quasar Quasi-Stellar Radio Source",
        w1: "Pulsar",
        w2: "Magnetar",
        exp: "Quasars release gravitational potential energy as friction in superheated accretion discs, radiating trillions of times more luminosity than our Sun."
      },
      {
        q: "What oblate region outside the event horizon of a rotating Kerr black hole drags the fabric of spacetime along with its spin?",
        correct: "Ergosphere",
        w1: "Accretion Torus",
        w2: "Photon Sphere",
        exp: "Inside the ergosphere, frame-dragging forces everything—including spacetime and light—to co-rotate with the black hole spin."
      },
      {
        q: "What theoretical energy extraction process allows particles entering the ergosphere of a rotating black hole to split and escape with rotational energy?",
        correct: "Penrose Process",
        w1: "Blandford-Znajek Process",
        w2: "Fermi Acceleration",
        exp: "Roger Penrose showed that if a particle breaks apart in the ergosphere with one piece falling on a negative-energy orbit, the escaping piece gains net energy."
      }
    ],
    number: {
      q: "How many million solar masses is the supermassive black hole Sagittarius A* at the center of our Milky Way Galaxy?",
      target: 4.15,
      unit: "million solar masses",
      imperial: "4.15 million solar masses",
      exp: "Decades of stellar orbital tracking by Nobel laureates Reinhard Genzel and Andrea Ghez established the mass of Sagittarius A* at 4.15 million solar masses."
    }
  },

  // Cycle 3: Galaxy Morphologies & The Local Group
  {
    mcqs: [
      {
        q: "What barred spiral galaxy contains our Solar System, spanning approximately 100,000 light-years in diameter with over 100 billion stars?",
        correct: "The Milky Way",
        w1: "Andromeda Galaxy",
        w2: "Triangulum Galaxy",
        exp: "The Milky Way has a central bar and four major spiral arms (Perseus, Scutum-Centaurus, Sagittarius, and Outer), with our Sun located in the Orion Spur."
      },
      {
        q: "What largest spiral galaxy in our Local Group is on a direct collision course to merge with the Milky Way in approximately 4.5 billion years?",
        correct: "Andromeda Galaxy Messier 31",
        w1: "Triangulum Galaxy M33",
        w2: "Large Magellanic Cloud",
        exp: "Andromeda is approaching the Milky Way at roughly 110 km/s, and their future merger will transform the pair into a giant elliptical galaxy nicknamed Milkomeda."
      },
      {
        q: "What famous classification diagram devised by Edwin Hubble categorizes galaxies into ellipticals, lenticulars, and ordinary/barred spirals?",
        correct: "Hubble Tuning Fork Diagram",
        w1: "Hertzsprung-Russell Diagram",
        w2: "Oort Sequence",
        exp: "Hubble morphological scheme arranges galaxies from round ellipticals (E0 to E7) branching into unbarred (Sa, Sb, Sc) and barred spirals (SBa, SBb, SBc)."
      },
      {
        q: "What two irregular dwarf satellite galaxies orbiting the Milky Way are visible to the naked eye from Earth Southern Hemisphere?",
        correct: "Large and Small Magellanic Clouds",
        w1: "Fornax and Carina Dwarfs",
        w2: "Sculptor and Draco Dwarfs",
        exp: "The Magellanic Clouds are gravitationally bound dwarf galaxies undergoing starburst activity, containing active star nurseries like the Tarantula Nebula."
      },
      {
        q: "What dense, spherical clusters containing hundreds of thousands of ancient stars orbit in the outer halo of the Milky Way?",
        correct: "Globular Clusters",
        w1: "Open Star Clusters",
        w2: "Stellar Associations",
        exp: "Globular clusters like Omega Centauri contain population II metal-poor stars dating back over 12 billion years to the early formation of the galaxy."
      }
    ],
    number: {
      q: "Approximately how many billion years from now are the Milky Way and Andromeda galaxies predicted to collide and begin merging?",
      target: 4.5,
      unit: "billion years",
      imperial: "4.5 billion years in the future",
      exp: "High-precision Hubble Space Telescope proper-motion measurements calculate that Andromeda and the Milky Way will experience their first close pass in roughly 4.5 billion years."
    }
  },

  // Cycle 4: The Big Bang & Cosmic Expansion
  {
    mcqs: [
      {
        q: "What fundamental cosmological law states that distant galaxies recede from Earth at velocities directly proportional to their distance?",
        correct: "Hubble-Lemaitre Law",
        w1: "Kepler Third Law",
        w2: "Wien Displacement Law",
        exp: "Expressed as $v = H_0 d$, the law reflects the metric expansion of space itself rather than galaxies traveling through static space."
      },
      {
        q: "What shift in spectral absorption lines toward longer wavelengths in light from distant galaxies provides empirical proof of expanding space?",
        correct: "Cosmological Redshift",
        w1: "Gravitational Blueshift",
        w2: "Doppler Dispersion",
        exp: "As light waves travel across expanding intergalactic space over billions of years, their wavelengths are stretched proportionally to cosmic scale factor expansion."
      },
      {
        q: "What brief epoch in the first split second ($10^{-36}$ s) after the Big Bang saw space expand exponentially faster than the speed of light by a factor of $10^{26}$?",
        correct: "Cosmic Inflation",
        w1: "Recombination",
        w2: "Baryogenesis",
        exp: "Proposed by Alan Guth, inflation resolves the Horizon and Flatness problems, smoothing primordial spacetime and stretching quantum fluctuations into galaxy seeds."
      },
      {
        q: "What Belgian Catholic priest and theoretical physicist first derived the expanding universe equations and proposed the Primeval Atom hypothesis in 1927?",
        correct: "Georges Lemaitre",
        w1: "Alexander Friedmann",
        w2: "Willem de Sitter",
        exp: "Lemaitre independently derived Friedmann solutions to Einstein field equations, proposing that the universe expanded from an initial high-density state."
      },
      {
        q: "What nucleosynthesis epoch in the first 20 minutes after the Big Bang forged all primordial hydrogen, helium-4, deuterium, and trace lithium in the cosmos?",
        correct: "Big Bang Nucleosynthesis BBN",
        w1: "Stellar Nucleosynthesis",
        w2: "Supernova Nucleosynthesis",
        exp: "BBN accurately predicts that primordial cosmic matter should consist of roughly 75% hydrogen and 25% helium-4 by mass, matching astronomical observations."
      }
    ],
    number: {
      q: "What is the current best-measured age of the Universe in billion years based on Planck Satellite cosmic microwave background measurements?",
      target: 13.8,
      unit: "billion years",
      imperial: "13.787 billion years old",
      exp: "The European Space Agency Planck mission determined the age of the Universe to be 13.787 +/- 0.020 billion years within the standard Lambda-CDM model."
    }
  },

  // Cycle 5: Cosmic Microwave Background CMB
  {
    mcqs: [
      {
        q: "What faint thermal relic radiation permeating all of space was released roughly 380,000 years after the Big Bang when neutral atoms first formed?",
        correct: "Cosmic Microwave Background CMB",
        w1: "Cosmic Neutrino Background",
        w2: "Diffuse X-ray Background",
        exp: "The CMB is the oldest electromagnetic radiation in the universe, redshifted from incandescent 3,000 K plasma down to microwave wavelengths at 2.725 Kelvin."
      },
      {
        q: "What epoch in early cosmic history occurred when cooling temperatures allowed electrons to bind to protons, rendering the universe transparent to photons?",
        correct: "Recombination and Decoupling",
        w1: "Reionization",
        w2: "Inflationary Horizon",
        exp: "At temperature ~3,000 K (redshift z ~ 1100), hydrogen plasma transitioned to neutral gas, freeing photons from continuous Thomson scattering."
      },
      {
        q: "Which American radio astronomers discovered the Cosmic Microwave Background by accident in 1964 with the Bell Labs Holmdel Horn Antenna?",
        correct: "Arno Penzias and Robert Wilson",
        w1: "Edwin Hubble and Milton Humason",
        w2: "Vera Rubin and Kent Ford",
        exp: "Penzias and Wilson detected an isotropic, persistent background microwave noise in all sky directions, earning the 1978 Nobel Prize in Physics."
      },
      {
        q: "What NASA satellite launched in 1989 first measured the exact blackbody curve of the CMB and detected minute primordial temperature fluctuations?",
        correct: "COBE Cosmic Background Explorer",
        w1: "WMAP",
        w2: "Planck Satellite",
        exp: "COBE FIRAS instrument confirmed the CMB is the most perfect blackbody spectrum in nature, earning John Mather and George Smoot the 2006 Nobel Prize."
      },
      {
        q: "What term describes the tiny microkelvin temperature fluctuations across the CMB that reveal density variations which seeded all cosmic structure?",
        correct: "CMB Anisotropies",
        w1: "Acoustic Dipoles",
        w2: "Zeeman Splittings",
        exp: "Anisotropies of one part in 100,000 represent primordial acoustic density waves in the photon-baryon plasma, mapped into cosmic power spectra."
      }
    ],
    number: {
      q: "What is the average blackbody radiation temperature of the Cosmic Microwave Background in Kelvin?",
      target: 2.725,
      unit: "Kelvin",
      imperial: "2.7255 K (-270.42 °C)",
      exp: "High-precision satellite measurements establish the cosmic microwave background temperature at exactly 2.72548 +/- 0.00057 Kelvin."
    }
  },

  // Cycle 6: Dark Matter & Gravitational Lensing
  {
    mcqs: [
      {
        q: "What invisible non-baryonic matter constitutes approximately 85 percent of all matter in the universe, interacting only gravitationally?",
        correct: "Dark Matter",
        w1: "Dark Energy",
        w2: "Antimatter",
        exp: "Dark matter does not absorb, reflect, or emit electromagnetic radiation, but its gravitational scaffolding holds rotating galaxies and galaxy clusters together."
      },
      {
        q: "What pioneering astronomer provided definitive proof of dark matter in the 1970s by measuring flat, non-Keplerian orbital rotation curves in spiral galaxies?",
        correct: "Vera Rubin",
        w1: "Henrietta Leavitt",
        w2: "Jocelyn Bell Burnell",
        exp: "Vera Rubin and Kent Ford showed that stars at galaxy edges orbit just as fast as stars near the center, proving galaxies are embedded in massive dark matter halos."
      },
      {
        q: "What relativistic optical effect bends and magnifies light rays from distant background galaxies as they pass through massive foreground galaxy clusters?",
        correct: "Gravitational Lensing",
        w1: "Cosmic Aberration",
        w2: "Atmospheric Refraction",
        exp: "Predicted by General Relativity, mass curves spacetime to act as a cosmic lens, producing magnified Einstein rings, arcs, and multiple distorted images."
      },
      {
        q: "What colliding galaxy cluster system provided empirical direct proof of dark matter by showing gravitational mass separated from normal X-ray gas?",
        correct: "The Bullet Cluster 1E 0657-56",
        w1: "Coma Cluster",
        w2: "Virgo Cluster",
        exp: "In the collision, ordinary gas slowed down due to electromagnetic drag while collisionless dark matter passed straight through, mapped by gravitational lensing."
      },
      {
        q: "What class of hypothetical subatomic particles that interact only via gravity and the weak force are prime candidates for cold dark matter?",
        correct: "WIMPs Weakly Interacting Massive Particles",
        w1: "Axions",
        w2: "Gluons",
        exp: "WIMPs are predicted by supersymmetric extensions of the Standard Model, sought by deep underground cryogenic detectors like LUX-ZEPLIN and XENONnT."
      }
    ],
    number: {
      q: "What percentage of the total mass-energy content of the universe is composed of Dark Matter in the standard Lambda-CDM cosmological model?",
      target: 27,
      unit: "percent",
      imperial: "26.8% Dark Matter",
      exp: "Planck satellite cosmological measurements show the universe consists of 26.8% Dark Matter, 68.3% Dark Energy, and only 4.9% ordinary baryonic matter."
    }
  },

  // Cycle 7: Dark Energy & Accelerating Expansion
  {
    mcqs: [
      {
        q: "What mysterious repulsive pressure constitutes approximately 68 percent of the universe mass-energy, causing the cosmic expansion rate to accelerate?",
        correct: "Dark Energy",
        w1: "Dark Matter",
        w2: "Vacuum Plasma",
        exp: "Dark energy acts as a negative pressure on cosmological scales, overcoming gravitational attraction to drive the accelerating expansion of spacetime."
      },
      {
        q: "What standard candle stellar explosions with uniform intrinsic peak luminosity were observed in 1998 to discover the accelerating expansion of the universe?",
        correct: "Type Ia Supernovae",
        w1: "Type II Core Collapse Supernovae",
        w2: "Classical Novae",
        exp: "Type Ia supernovae result from thermonuclear destruction of carbon-oxygen white dwarfs at the Chandrasekhar limit, providing standardized cosmic yardsticks."
      },
      {
        q: "What mathematical term introduced by Albert Einstein in 1917 into his field equations acts as the mathematical representation of Dark Energy?",
        correct: "Cosmological Constant Lambda",
        w1: "Curvature Tensor",
        w2: "Stress-Energy Invariant",
        exp: "Einstein introduced Lambda to balance gravity for a static universe, later calling it his biggest blunder, but modern cosmology revived it as dark energy density."
      },
      {
        q: "What standard cosmological model combining Dark Energy, Cold Dark Matter, and General Relativity is the current standard model of cosmology?",
        correct: "Lambda-CDM Model",
        w1: "Steady State Model",
        w2: "Einstein-de Sitter Model",
        exp: "The Lambda-CDM model successfully predicts the CMB spectrum, large-scale galaxy clustering, and the light-element abundances from Big Bang nucleosynthesis."
      },
      {
        q: "Which trio of astrophysicists was awarded the 2011 Nobel Prize in Physics for discovering the accelerating expansion of the universe through distant supernovae?",
        correct: "Saul Perlmutter, Brian Schmidt, Adam Riess",
        w1: "Roger Penrose, Reinhard Genzel, Andrea Ghez",
        w2: "Rainer Weiss, Kip Thorne, Barry Barish",
        exp: "Leading the Supernova Cosmology Project and High-Z Supernova Search Team, they found distant supernovae were dimmer than expected, proving accelerating expansion."
      }
    ],
    number: {
      q: "What percentage of the total mass-energy density of the universe consists of Dark Energy in the standard Lambda-CDM cosmological model?",
      target: 68,
      unit: "percent",
      imperial: "68.3% Dark Energy",
      exp: "Planck mission precision CMB measurements establish that Dark Energy accounts for 68.3 percent of the total mass-energy density of the observable universe."
    }
  },

  // Cycle 8: Gravitational Waves & Spacetime Ripples
  {
    mcqs: [
      {
        q: "What ripples in the curvature of spacetime propagate at the speed of light, generated by accelerating massive systems like merging black holes?",
        correct: "Gravitational Waves",
        w1: "Seismic Torsion Waves",
        w2: "Magnetosonic Waves",
        exp: "Predicted by Einstein in 1916, gravitational waves squeeze and stretch spacetime transversely as they pass through matter."
      },
      {
        q: "What laser interferometer observatory with twin 4-km perpendicular arms in Washington and Louisiana made the historic first direct detection of gravitational waves in 2015?",
        correct: "LIGO Laser Interferometer Gravitational-Wave Observatory",
        w1: "VIRGO",
        w2: "GEO600",
        exp: "LIGO uses ultra-stable laser beams bouncing between suspended mirrors in vacuum tubes to detect metric spacetime distortions smaller than 1/10,000th of a proton diameter."
      },
      {
        q: "What landmark astronomical event detected on September 14, 2015 (GW150914) marked the first direct observation of gravitational waves by LIGO?",
        correct: "Binary Black Hole Merger",
        w1: "Binary Neutron Star Collision",
        w2: "Supernova Core Collapse",
        exp: "Two black holes of 36 and 29 solar masses merged into a single 62-solar-mass black hole, converting 3 solar masses into pure gravitational wave energy in milliseconds."
      },
      {
        q: "What historic 2017 multi-messenger astronomical event (GW170817) produced both gravitational waves and electromagnetic gamma rays from colliding neutron stars?",
        correct: "Binary Neutron Star Merger Kilonova",
        w1: "Black Hole-Neutron Star Merger",
        w2: "Magnetar Giant Flare",
        exp: "GW170817 was observed simultaneously across gravitational waves, gamma-rays, X-rays, and optical telescopes, confirming kilonova synthesis of heavy elements like platinum and gold."
      },
      {
        q: "What proposed space-based gravitational wave interferometer led by ESA and NASA will use three spacecraft separated by 2.5 million km to detect low-frequency ripples?",
        correct: "LISA Laser Interferometer Space Antenna",
        w1: "DECIGO",
        w2: "Big Bang Observer",
        exp: "LISA will form a giant triangular laser interferometer in heliocentric orbit to detect gravitational waves from supermassive black hole mergers across the universe."
      }
    ],
    number: {
      q: "What is the arm length in kilometers of each perpendicular vacuum tube in the Advanced LIGO gravitational wave detectors?",
      target: 4,
      unit: "km",
      imperial: "2.5 miles (4.0 km)",
      exp: "Each LIGO facility features two 4-kilometer (2.5-mile) long ultra-high vacuum arms through which infrared laser beams reflect back and forth."
    }
  },

  // Cycle 9: The Cosmic Web & Superclusters
  {
    mcqs: [
      {
        q: "What colossal cosmic structure encompasses the Milky Way and 100,000 neighboring galaxies bound within a 500-million-light-year gravitational basin?",
        correct: "Laniakea Supercluster",
        w1: "Virgo Supercluster",
        w2: "Shapley Supercluster",
        exp: "Mapped using peculiar velocity flow lines, Laniakea (meaning immense heaven in Hawaiian) defines the gravitational watershed pulling our local galactic neighborhood."
      },
      {
        q: "What mysterious gravitational mass anomaly in the Zone of Avoidance pulls the Milky Way and surrounding superclusters toward itself at 600 km/s?",
        correct: "The Great Attractor",
        w1: "The Shapley Concentration",
        w2: "The Perseus-Pisces Complex",
        exp: "Located behind the dust obscured plane of the Milky Way near the Norma Cluster, the Great Attractor is a dense gravitational concentration of galaxy clusters."
      },
      {
        q: "What vast, nearly empty spherical expanse of intergalactic space spanning over 300 million light-years in diameter contains almost no galaxies?",
        correct: "The Bootes Void",
        w1: "The Local Void",
        w2: "The Eridanus Supervoid",
        exp: "Also known as the Great Nothing, the Bootes Void should contain roughly 10,000 galaxies given average cosmic density, but astronomers have found only about 60."
      },
      {
        q: "What large-scale filamentary network of dark matter, gas, and galaxy clusters spanning hundreds of millions of light-years forms the structure of the universe?",
        correct: "The Cosmic Web",
        w1: "Filamentary Mesh",
        w2: "Local Filament Group",
        exp: "Galaxies form along dense dark matter filaments and cluster at intersections, separated by vast cosmic voids like foam on ocean waves."
      },
      {
        q: "What massive structure of 73 gravitationally associated quasars spanning 4 billion light-years in diameter was discovered in 2013?",
        correct: "Huge-LQG Large Quasar Group",
        w1: "Sloan Great Wall",
        w2: "Hercules-Corona Borealis Great Wall",
        exp: "Huge-LQG challenges the cosmological principle scale limits, spanning approximately 1.24 gigaparsecs (4 billion light-years) across the distant universe."
      }
    ],
    number: {
      q: "Approximately how many million light-years across is the diameter of the colossal Laniakea Supercluster containing the Milky Way?",
      target: 500,
      unit: "million light-years",
      imperial: "520 million light-years across",
      exp: "The Laniakea Supercluster spans approximately 500 to 520 million light-years (160 megaparsecs) in diameter and contains the mass of roughly $10^{17}$ solar masses."
    }
  },

  // Cycle 10: The Ultimate Fate of the Universe
  {
    mcqs: [
      {
        q: "What most widely supported cosmological end-state predicts that universal expansion will continue forever until all stars burn out and entropy reaches maximum?",
        correct: "The Big Freeze Heat Death",
        w1: "The Big Crunch",
        w2: "The Big Rip",
        exp: "In the Big Freeze, the universe asymptotically approaches thermodynamic equilibrium near absolute zero, with black holes eventually evaporating via Hawking radiation."
      },
      {
        q: "What catastrophic cosmological scenario would occur if phantom dark energy density increases over time, tearing apart galaxies, stars, planets, and atomic nuclei?",
        correct: "The Big Rip",
        w1: "The Big Bounce",
        w2: "Vacuum Decay",
        exp: "If the dark energy equation of state parameter $w < -1$, cosmic expansion accelerates infinitely, overcoming all fundamental nuclear forces in a final cosmic singularity."
      },
      {
        q: "What cyclical cosmological model proposes that gravitational attraction will eventually halt expansion and reverse it, collapsing space back into a hot singularity?",
        correct: "The Big Crunch",
        w1: "Conformal Cyclic Cosmology",
        w2: "Steady State Model",
        exp: "The Big Crunch requires cosmic mass density to exceed critical density; current measurements showing accelerating dark energy make this outcome unlikely."
      },
      {
        q: "What theoretical quantum decay process predicts that all baryonic atomic matter will eventually disintegrate over $10^{34}$ years as fundamental protons decay?",
        correct: "Proton Decay",
        w1: "Neutron Beta Decay",
        w2: "Hawking Annihilation",
        exp: "Grand Unified Theories predict that protons have a finite half-life exceeding $10^{34}$ years, eventually decaying into positrons and neutral pions."
      },
      {
        q: "What catastrophic quantum phase transition could occur if our universe Higgs field is in a metastable false vacuum, collapsing the universe at light speed?",
        correct: "False Vacuum Decay",
        w1: "Cosmic Thermalization",
        w2: "Inflationary Dissipation",
        exp: "A quantum tunneling event into a lower-energy true vacuum would create a bubble of altered physical constants expanding at the speed of light, destroying all matter."
      }
    ],
    number: {
      q: "In approximately how many trillion years will the last longest-lived red dwarf stars exhaust their hydrogen fuel, transitioning into the Degenerate Era?",
      target: 100,
      unit: "trillion years",
      imperial: "100 trillion years (10^14 years)",
      exp: "Small red dwarf stars can burn hydrogen efficiently for up to 100 trillion years ($10^{14}$ years), after which active stellar fusion in the universe permanently ceases."
    }
  }
];

buildQuiz({
  id: 'deep-space-black-holes-cosmology-60',
  theme: 'Deep Space: Black Holes, Galaxies & Big Bang',
  title: 'Deep Space: Black Holes, Galaxies & Big Bang',
  description: 'A 60-question grand master assessment on event horizon physics, supermassive black holes, Big Bang nucleosynthesis, CMB radiation, dark matter, and cosmic fate.',
  category: 'Astronomy, Physics & Chemistry',
  difficulty: 'moderate'
}, cosmologyCycles);

// -------------------------------------------------------------
// 12. quantum-physics-particle-world-60
// -------------------------------------------------------------
const quantumCycles = [
  // Cycle 1: Wave-Particle Duality & Early Quantum Theory
  {
    mcqs: [
      {
        q: "What German physicist initiated quantum mechanics in 1900 by proposing that electromagnetic energy is emitted and absorbed only in discrete packets called quanta?",
        correct: "Max Planck",
        w1: "Albert Einstein",
        w2: "Niels Bohr",
        exp: "Planck solved the blackbody ultraviolet catastrophe by proposing that energy is proportional to frequency ($E = hf$), introducing Planck constant."
      },
      {
        q: "For what discovery did Albert Einstein receive the 1921 Nobel Prize in Physics, proving that light behaves as discrete particle packets called photons?",
        correct: "The Photoelectric Effect",
        w1: "Special Relativity",
        w2: "General Relativity",
        exp: "Einstein 1905 paper explained that photons transfer energy to eject surface electrons only if photon frequency exceeds the metal work function threshold."
      },
      {
        q: "What French physicist proposed in 1924 that all moving matter particles, including electrons, possess an associated matter wavelength ($\lambda = h/p$)?",
        correct: "Louis de Broglie",
        w1: "Arthur Compton",
        w2: "Erwin Schrodinger",
        exp: "De Broglie wave-particle duality hypothesis demonstrated that electrons exhibit wave phenomena like interference, earning him the 1929 Nobel Prize in Physics."
      },
      {
        q: "What landmark 1927 experiment by scattering electrons off a crystalline nickel target provided the first direct physical proof of electron wave diffraction?",
        correct: "Davisson-Germer Experiment",
        w1: "Stern-Gerlach Experiment",
        w2: "Michelson-Morley Experiment",
        exp: "Clinton Davisson and Lester Germer observed peak electron diffraction scattering angles matching Bragg law for the calculated de Broglie matter wavelength."
      },
      {
        q: "What atomic model proposed in 1913 introduced quantized electron angular momentum where electrons emit photons only when jumping between discrete energy levels?",
        correct: "Bohr Model",
        w1: "Thomson Plum Pudding Model",
        w2: "Rutherford Planetary Model",
        exp: "Niels Bohr model successfully explained the Rydberg formula for the spectral emission lines of hydrogen gas by quantizing electron orbits."
      }
    ],
    number: {
      q: "What is the power exponent value n in Planck constant h = 6.626 x 10^-n J*s?",
      target: 34,
      unit: "power of 10",
      imperial: "6.626 x 10^-34 J*s",
      exp: "Planck constant $h$ is precisely defined in SI units as $6.62607015 \\times 10^{-34} \\text{ J}\\cdot\\text{s}$ (joule-seconds), fundamental to all quantum mechanics."
    }
  },

  // Cycle 2: Quantum Superposition & Wave Mechanics
  {
    mcqs: [
      {
        q: "What partial differential equation formulated in 1925 describes the spatial and temporal evolution of a quantum mechanical wave function $\Psi$?",
        correct: "Schrodinger Equation",
        w1: "Dirac Equation",
        w2: "Klein-Gordon Equation",
        exp: "The time-dependent Schrodinger equation $i\\hbar \\frac{\\partial}{\\partial t}\\Psi = \\hat{H}\\Psi$ forms the mathematical foundation of non-relativistic quantum systems."
      },
      {
        q: "What principle of quantum mechanics asserts that a physical system can exist in a linear combination of multiple distinct quantum states simultaneously?",
        correct: "Quantum Superposition",
        w1: "Pauli Exclusion",
        w2: "Correspondence Principle",
        exp: "Superposition allows a quantum particle to occupy multiple energy, position, or spin states until an observation causes wavefunction collapse."
      },
      {
        q: "According to the Born Rule formulated by Max Born in 1926, what does the squared absolute magnitude of the wave function $|\Psi|^2$ represent?",
        correct: "Probability density of finding a particle at a given point in space",
        w1: "Physical mass density of the smeared particle",
        w2: "Electric charge distribution per volume",
        exp: "Max Born statistical interpretation proved that quantum mechanics provides probabilistic predictions rather than deterministic trajectories."
      },
      {
        q: "What famous thought experiment proposed by Erwin Schrodinger in 1935 illustrates the paradox of quantum superposition applied to macroscopic objects?",
        correct: "Schrodinger Cat Paradox",
        w1: "Einstein Elevator",
        w2: "Maxwell Demon",
        exp: "Schrodinger imagined a cat in a sealed box with a radioactive atom, Geiger counter, and poison vial to highlight the counterintuitive nature of Copenhagen superposition."
      },
      {
        q: "What interpretation of quantum mechanics developed by Niels Bohr and Werner Heisenberg asserts that physical systems have no definite properties prior to measurement?",
        correct: "Copenhagen Interpretation",
        w1: "Many-Worlds Interpretation",
        w2: "De Broglie-Bohm Pilot Wave Theory",
        exp: "The Copenhagen interpretation posits that the act of physical measurement forces a probabilistic wave function into a single definite eigenvalue."
      }
    ],
    number: {
      q: "In what year CE did Erwin Schrodinger publish his wave equation paper introducing wave mechanics to quantum physics?",
      target: 1926,
      unit: "CE",
      imperial: "1926 CE",
      exp: "Erwin Schrodinger published his landmark four-part paper Quantization as an Eigenvalue Problem in Annalen der Physik in the first half of 1926."
    }
  },

  // Cycle 3: Uncertainty Principle & Quantum Tunneling
  {
    mcqs: [
      {
        q: "What fundamental principle states that the exact position and momentum of a particle cannot be simultaneously known with arbitrary precision?",
        correct: "Heisenberg Uncertainty Principle",
        w1: "Pauli Exclusion Principle",
        w2: "Equivalence Principle",
        exp: "Formulated by Werner Heisenberg in 1927, $\\Delta x \\Delta p \\ge \\frac{\\hbar}{2}$ reflects an intrinsic mathematical property of Fourier transform wave mechanics."
      },
      {
        q: "In quantum mechanics, what two physical properties form conjugate variable pairs whose measurement uncertainties are fundamentally bound?",
        correct: "Position and Momentum",
        w1: "Mass and Velocity",
        w2: "Charge and Spin",
        exp: "Non-commuting quantum operators like position-momentum ($[\\hat{x}, \\hat{p}] = i\\hbar$) and energy-time exhibit fundamental reciprocal uncertainty bounds."
      },
      {
        q: "What quantum phenomenon allows a subatomic particle to cross directly through a potential energy barrier higher than the particle kinetic energy?",
        correct: "Quantum Tunneling",
        w1: "Quantum Teleportation",
        w2: "Wavepacket Compression",
        exp: "Because a particle wave function decays exponentially inside a finite barrier rather than dropping instantly to zero, there is a non-zero probability of appearing on the other side."
      },
      {
        q: "What atomic-scale microscope technology uses quantum tunneling of electrons between an ultra-sharp metal tip and a surface to resolve individual atoms?",
        correct: "Scanning Tunneling Microscope STM",
        w1: "Atomic Force Microscope",
        w2: "Transmission Electron Microscope",
        exp: "Invented by Gerd Binnig and Heinrich Rohrer at IBM Zurich, the exponential sensitivity of tunneling current to tip-sample distance enables sub-nanometer imaging."
      },
      {
        q: "What nuclear radioactive decay process (such as alpha particle emission from uranium-238) is made possible entirely by quantum tunneling through the Coulomb barrier?",
        correct: "Alpha Decay",
        w1: "Beta Plus Decay",
        w2: "Gamma De-excitation",
        exp: "George Gamow explained in 1928 that alpha particles trapped inside atomic nuclei escape by tunneling through the strong nuclear-electrostatic potential barrier."
      }
    ],
    number: {
      q: "In what year CE was the Nobel Prize in Physics awarded to Gerd Binnig and Heinrich Rohrer for inventing the Scanning Tunneling Microscope?",
      target: 1986,
      unit: "CE",
      imperial: "1986 CE",
      exp: "Gerd Binnig and Heinrich Rohrer were awarded half the 1986 Nobel Prize in Physics for designing the scanning tunneling microscope, sharing with Ernst Ruska."
    }
  },

  // Cycle 4: Quantum Entanglement & Nonlocality
  {
    mcqs: [
      {
        q: "What 1935 paper by Einstein, Podolsky, and Rosen argued that quantum mechanics was incomplete due to spooky action at a distance between entangled states?",
        correct: "EPR Paradox",
        w1: "Gibbs Paradox",
        w2: "Klein Paradox",
        exp: "The EPR paper asserted that if measurements on one entangled particle instantly determine the state of another distant particle, local realism must be incomplete."
      },
      {
        q: "What Northern Irish physicist formulated a mathematical inequality in 1964 demonstrating that no local hidden-variable theory can reproduce quantum predictions?",
        correct: "John Stewart Bell",
        w1: "David Bohm",
        w2: "Alain Aspect",
        exp: "Bell Theorem established that quantum nonlocality is experimentally testable, showing quantum mechanics predicts statistical correlations exceeding any local classical physics."
      },
      {
        q: "What experimental milestone led by Alain Aspect in 1982 and awarded the 2022 Nobel Prize proved that nature violates Bell inequalities?",
        correct: "Bell Test Quantum Nonlocality Experiments",
        w1: "Double Slit Wave Cancellation",
        w2: "Stern-Gerlach Beam Splitting",
        exp: "Alain Aspect, John Clauser, and Anton Zeilinger proved that entangled photons exhibit non-local quantum correlations, ruling out local hidden-variable theories."
      },
      {
        q: "What quantum protocol transfers the complete quantum state of a qubit to a distant location using shared entanglement and classical communication channels?",
        correct: "Quantum Teleportation",
        w1: "Quantum Key Distribution",
        w2: "Superdense Coding",
        exp: "First demonstrated by Anton Zeilinger in 1997, quantum teleportation destroys the original qubit state while reconstructing an exact replica at the receiver."
      },
      {
        q: "What fundamental theorem of quantum mechanics proves that it is mathematically impossible to create an exact duplicate copy of an unknown quantum state?",
        correct: "No-Cloning Theorem",
        w1: "No-Communication Theorem",
        w2: "Spin-Statistics Theorem",
        exp: "Formulated by Wootters, Zurek, and Dieks in 1982, the linearity of quantum operators prevents copying quantum information, ensuring quantum cryptographic security."
      }
    ],
    number: {
      q: "In what year CE did John Stewart Bell publish his groundbreaking paper formulating Bell Inequalities for testing quantum nonlocality?",
      target: 1964,
      unit: "CE",
      imperial: "1964 CE",
      exp: "John S. Bell published On the Einstein Podolsky Rosen Paradox in 1964 in the journal Physics Physique Fizika, transforming quantum philosophy into experimental science."
    }
  },

  // Cycle 5: The Standard Model: Quarks & Leptons
  {
    mcqs: [
      {
        q: "What comprehensive quantum field theory framework classifies all known elementary particles and three of the four fundamental physical forces?",
        correct: "The Standard Model",
        w1: "String Theory",
        w2: "Grand Unified Theory",
        exp: "The Standard Model incorporates the electromagnetic, weak, and strong nuclear forces based on the gauge symmetry group $SU(3) \\times SU(2) \\times U(1)$."
      },
      {
        q: "How many distinct flavors of elementary quarks exist in the Standard Model: up, down, charm, strange, top, and bottom?",
        correct: "Six",
        w1: "Four",
        w2: "Eight",
        exp: "Quarks are divided into three generations of pairs: Up/Down, Charm/Strange, and Top/Bottom, carrying fractional electric charges and color charges."
      },
      {
        q: "What fractional electric charge in units of elementary charge e does an Up quark carry?",
        correct: "+2/3 e",
        w1: "-1/3 e",
        w2: "+1 e",
        exp: "Up, Charm, and Top quarks carry $+2/3 e$ electric charge, while Down, Strange, and Bottom quarks carry $-1/3 e$ electric charge."
      },
      {
        q: "What composite subatomic particle composed of three quarks (such as a proton composed of two up quarks and one down quark) is called?",
        correct: "Baryon",
        w1: "Meson",
        w2: "Lepton",
        exp: "Baryons are three-quark hadrons (protons: uud, neutrons: udd), whereas mesons are quark-antiquark pairs like pions and kaons."
      },
      {
        q: "What family of fundamental leptons includes the electron, muon, tau particle, and their three corresponding neutral neutrinos?",
        correct: "Leptons",
        w1: "Quarks",
        w2: "Vector Bosons",
        exp: "Leptons do not experience the strong nuclear force, interacting only via electromagnetic (if charged), weak nuclear, and gravitational forces."
      }
    ],
    number: {
      q: "How many total fundamental elementary matter fermions (6 quarks + 6 leptons) make up the Standard Model of particle physics?",
      target: 12,
      unit: "matter fermions",
      imperial: "12 fundamental matter fermions",
      exp: "There are exactly 12 elementary matter particles (fermions) arranged in three generations: 6 quarks (u, d, c, s, t, b) and 6 leptons ($e, \\mu, \\tau, \\nu_e, \\nu_\\mu, \\nu_\\tau$)."
    }
  },

  // Cycle 6: Gauge Bosons & Fundamental Forces
  {
    mcqs: [
      {
        q: "What massless gauge vector boson is the fundamental mediator particle of the electromagnetic interaction between charged particles?",
        correct: "Photon",
        w1: "Gluon",
        w2: "W Boson",
        exp: "Photons are spin-1 vector bosons described by quantum electrodynamics QED, traveling at the speed of light in vacuum."
      },
      {
        q: "What eight massless gauge bosons mediate the strong nuclear force that binds quarks together inside hadrons by carrying color charge?",
        correct: "Gluons",
        w1: "Photons",
        w2: "Z Bosons",
        exp: "Described by Quantum Chromodynamics QCD, gluons carry color-anticolor charges, resulting in color confinement and asymptotic freedom."
      },
      {
        q: "What massive vector bosons mediate the weak nuclear force responsible for radioactive beta decay and stellar nuclear fusion?",
        correct: "W and Z Bosons",
        w1: "Gluons",
        w2: "Gravitons",
        exp: "The $W^+$, $W^-$, and $Z^0$ bosons are heavy vector bosons with masses roughly 80 to 91 GeV/$c^2$, discovered at CERN in 1983."
      },
      {
        q: "What intrinsic quantum mechanical property of particles represents angular momentum measured in integer or half-integer units of reduced Planck constant?",
        correct: "Quantum Spin",
        w1: "Orbital Moment",
        w2: "Helicity Tensor",
        exp: "Particles with half-integer spin (1/2, 3/2) are fermions obeying Fermi-Dirac statistics, while integer spin particles (0, 1, 2) are bosons obeying Bose-Einstein statistics."
      },
      {
        q: "What quantum rule states that no two identical fermions (such as electrons in an atom) can occupy the exact same quantum state simultaneously?",
        correct: "Pauli Exclusion Principle",
        w1: "Hund Rule",
        w2: "Aufbau Principle",
        exp: "Wolfgang Pauli principle explains electron shell structures, chemical bonding properties, and electron degeneracy pressure supporting white dwarf stars."
      }
    ],
    number: {
      q: "What is the quantum spin number of all fundamental force-mediating gauge vector bosons (photons, gluons, W/Z bosons)?",
      target: 1,
      unit: "spin",
      imperial: "Spin-1 vector bosons",
      exp: "All fundamental gauge vector bosons in the Standard Model have integer spin of exactly 1 (spin-1 particles), distinguishing them from spin-1/2 matter fermions."
    }
  },

  // Cycle 7: The Higgs Mechanism & CERN Discoveries
  {
    mcqs: [
      {
        q: "What scalar elementary boson discovered at CERN Large Hadron Collider in July 2012 provides evidence for the mass-generating Higgs field?",
        correct: "Higgs Boson",
        w1: "Graviton",
        w2: "Axion",
        exp: "The Higgs boson is the only fundamental spin-0 scalar particle in the Standard Model, confirming the Brout-Englert-Higgs mechanism of electroweak symmetry breaking."
      },
      {
        q: "What particle accelerator spanning a 27-kilometer circular underground tunnel beneath the Franco-Swiss border is the world largest and most energetic collider?",
        correct: "Large Hadron Collider LHC",
        w1: "Tevatron",
        w2: "Relativistic Heavy Ion Collider",
        exp: "The LHC accelerates two beams of protons in opposite directions at 99.999999% the speed of light, colliding them at center-of-mass energies up to 13.6 TeV."
      },
      {
        q: "What British theoretical physicist predicted the existence of the Higgs mechanism in 1964 and was awarded the 2013 Nobel Prize in Physics?",
        correct: "Peter Higgs",
        w1: "Paul Dirac",
        w2: "Stephen Hawking",
        exp: "Peter Higgs shared the 2013 Nobel Prize with Francois Englert after ATLAS and CMS experiments at CERN verified the Higgs particle at 125 GeV."
      },
      {
        q: "What quantum scalar field permeating all space broke electroweak symmetry in the early universe, giving rest mass to quarks and W/Z bosons?",
        correct: "Higgs Field",
        w1: "Inflaton Field",
        w2: "Dirac Sea",
        exp: "Particles acquire inertia and rest mass via Yukawa coupling interactions as they travel through the non-zero vacuum expectation value of the Higgs field."
      },
      {
        q: "What hypothetical spin-2 elementary particle is theorized to mediate the gravitational force in quantum gravity theories, though not yet detected?",
        correct: "Graviton",
        w1: "Dilaton",
        w2: "Majorana Fermion",
        exp: "A quantum description of gravity requires a massless spin-2 tensor boson, but gravitons remain undetected due to the extreme weakness of the gravitational coupling."
      }
    ],
    number: {
      q: "What is the measured rest mass of the Higgs Boson in giga-electronvolts GeV/c2 discovered at CERN?",
      target: 125,
      unit: "GeV/c2",
      imperial: "125.1 GeV/c^2 (approx 133 proton masses)",
      exp: "Joint measurements from ATLAS and CMS experiments at CERN established the Higgs boson mass at approximately 125.11 +/- 0.11 GeV/$c^2$."
    }
  },

  // Cycle 8: Special Relativity & Spacetime Invariance
  {
    mcqs: [
      {
        q: "What 1905 theory formulated by Albert Einstein established that the laws of physics and the speed of light in vacuum are identical for all inertial observers?",
        correct: "Special Relativity",
        w1: "General Relativity",
        w2: "Quantum Electrodynamics",
        exp: "Einstein eliminated the need for a stationary luminiferous aether, unifying space and time into a four-dimensional Minkowski spacetime continuum."
      },
      {
        q: "What relativistic phenomenon causes a moving clock to tick slower relative to a stationary observer frame as velocity approaches the speed of light?",
        correct: "Time Dilation",
        w1: "Length Contraction",
        w2: "Relativistic Aberration",
        exp: "Governed by the Lorentz factor $\gamma = 1/\\sqrt{1 - v^2/c^2}$, atmospheric muon lifespans and atomic clocks on GPS satellites directly verify time dilation."
      },
      {
        q: "What iconic mass-energy equivalence equation demonstrates that matter contains colossal amounts of latent energy, where c is the speed of light?",
        correct: "E equals m c squared",
        w1: "F equals m a",
        w2: "p equals h over lambda",
        exp: "$E = mc^2$ demonstrates that mass and energy are interchangeable, explaining the massive energy output of nuclear fission and stellar fusion."
      },
      {
        q: "What relativistic effect causes the measured length of a moving object along its direction of motion to shorten relative to an observer at rest?",
        correct: "Lorentz Length Contraction",
        w1: "Spacetime Torsion",
        w2: "Geodesic Shear",
        exp: "As velocity $v$ approaches $c$, an object physical dimensions along the axis of travel contract by a factor of $1/\\gamma = \\sqrt{1 - v^2/c^2}$."
      },
      {
        q: "What famous 1887 optical interferometer experiment failed to detect any motion of Earth through the luminiferous aether, proving light speed is constant?",
        correct: "Michelson-Morley Experiment",
        w1: "Fizeau Experiment",
        w2: "Cavendish Experiment",
        exp: "Albert Michelson and Edward Morley observed null fringe shifts as Earth orbited, conclusively disproving the existence of a mechanical light-carrying aether."
      }
    ],
    number: {
      q: "What is the speed of light in vacuum c rounded to the nearest thousand kilometers per second?",
      target: 300000,
      unit: "km/s",
      imperial: "299,792 km/s (approx 186,282 mi/s)",
      exp: "The speed of light in vacuum is an exact universal constant defined as 299,792.458 km/s (approximately 300,000 km/s)."
    }
  },

  // Cycle 9: General Relativity & Curved Spacetime
  {
    mcqs: [
      {
        q: "What foundational principle of General Relativity states that gravitational acceleration is physically indistinguishable from acceleration in an elevator?",
        correct: "The Equivalence Principle",
        w1: "The Principle of Covariance",
        w2: "Mach Principle",
        exp: "Einstein realization that an observer in free fall feels no weight led directly to viewing gravity as spacetime curvature rather than a classical Newtonian force."
      },
      {
        q: "In General Relativity, what geometric path represents the shortest trajectory that freely falling particles and light rays follow through curved spacetime?",
        correct: "Geodesics",
        w1: "Null Manifolds",
        w2: "Worldsheet Curves",
        exp: "Planets do not orbit the Sun because of a pulling force; they travel along straight-line geodesics through four-dimensional spacetime curved by the Sun mass."
      },
      {
        q: "What relativistic effect causes clocks situated closer to a massive gravitational body to run slower than clocks located farther out in weaker gravity?",
        correct: "Gravitational Time Dilation",
        w1: "Sagnac Phase Shift",
        w2: "Frame Dragging",
        exp: "Clocks on Earth surface tick slightly slower than clocks on GPS satellites in high orbit, requiring daily relativistic timing corrections of 38 microseconds."
      },
      {
        q: "What 1919 total solar eclipse expedition led by Sir Arthur Eddington provided the first empirical verification of General Relativity by measuring starlight deflection?",
        correct: "Principe and Sobral Eclipse Expedition",
        w1: "Greenwich Transit",
        w2: "Lick Observatory Survey",
        exp: "Photographs of the Hyades star cluster near the eclipsed Sun showed starlight displaced by 1.75 arcseconds, exactly matching Einstein curved spacetime prediction."
      },
      {
        q: "What anomalous orbital perihelion precession of 43 arcseconds per century in a solar system planet was famously resolved by Einstein General Relativity in 1915?",
        correct: "Precession of Mercury Perihelion",
        w1: "Mars Retrograde Loop",
        w2: "Venus Orbital Resonance",
        exp: "Newtonian mechanics could not account for the extra 43 arcseconds of Mercury perihelion shift per century, which spacetime curvature around the Sun explained precisely."
      }
    ],
    number: {
      q: "In what year CE did Albert Einstein present his definitive field equations of General Relativity to the Prussian Academy of Sciences?",
      target: 1915,
      unit: "CE",
      imperial: "1915 CE",
      exp: "Albert Einstein published the gravitational field equations ($G_{\\mu\\nu} = \\frac{8\\pi G}{c^4} T_{\\mu\\nu}$) in November 1915, establishing the general theory of relativity."
    }
  },

  // Cycle 10: Quantum Computing & The Quantum Frontier
  {
    mcqs: [
      {
        q: "What fundamental unit of quantum information is the quantum analog of a classical binary bit, able to exist in superpositions of 0 and 1 states?",
        correct: "Qubit",
        w1: "Qutrit",
        w2: "Classical Bit",
        exp: "A qubit is represented as a state vector $|\\psi\\rangle = \\alpha|0\\rangle + \\beta|1\\rangle$ on the Bloch sphere, enabling parallel computational state spaces."
      },
      {
        q: "What polynomial-time quantum algorithm developed by Peter Shor in 1994 can efficiently factor large composite integers, threatening RSA public-key encryption?",
        correct: "Shor Algorithm",
        w1: "Grover Algorithm",
        w2: "Deutsch-Jozsa Algorithm",
        exp: "Shor algorithm uses the quantum Fourier transform to find the period of modular exponentiation functions in $O((\\log N)^3)$ time compared to exponential classical time."
      },
      {
        q: "What quantum search algorithm provides a quadratic speedup for searching unsorted databases of N items in $O(\\sqrt{N})$ operations?",
        correct: "Grover Algorithm",
        w1: "Simon Algorithm",
        w2: "Quantum Phase Estimation",
        exp: "Invented by Lov Grover in 1996, the algorithm uses amplitude amplification to locate a marked item in an unsorted database with square-root computational speedup."
      },
      {
        q: "What milestone is achieved when a programmable quantum processor executes a specific mathematical calculation that is practically impossible for any classical supercomputer?",
        correct: "Quantum Supremacy Advantage",
        w1: "Fault-Tolerant Coherence",
        w2: "Quantum Key Distribution",
        exp: "Demonstrated by Google Sycamore in 2019 and USTC Jiuzhang in 2020, quantum supremacy proves quantum hardware can outperform classical supercomputing."
      },
      {
        q: "What physical process causes delicate quantum superpositions to lose coherence due to thermal and electromagnetic entanglement with the surrounding environment?",
        correct: "Quantum Decoherence",
        w1: "Wavefunction Damping",
        w2: "Phase Jitter",
        exp: "Decoherence destroys quantum phase relationships, requiring quantum error correction codes like surface codes to build scalable fault-tolerant quantum computers."
      }
    ],
    number: {
      q: "In what year CE did Peter Shor formulate his revolutionary quantum algorithm for polynomial-time prime number factorization?",
      target: 1994,
      unit: "CE",
      imperial: "1994 CE",
      exp: "Peter Shor developed his quantum factorization algorithm at AT&T Bell Laboratories in 1994, sparking modern global interest in quantum computing."
    }
  }
];

buildQuiz({
  id: 'quantum-physics-particle-world-60',
  theme: 'Quantum Physics, Subatomic Particles & Relativity',
  title: 'Quantum Physics, Subatomic Particles & Relativity',
  description: 'A 60-question grand master assessment exploring wave-particle duality, Schrodinger mechanics, Bell entanglement, Standard Model quarks, and general relativity.',
  category: 'Astronomy, Physics & Chemistry',
  difficulty: 'moderate'
}, quantumCycles);

console.log('Finished generating Quizzes 10, 11, 12!');
